### ISSUE TITLE
undefined symbols during ./bootstrap building pkg_create 

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#1]
Hi, hope this is not noise, but since a couple days trying to build with il-gcc44 on OIpre5 I'm suddenly getting the following: (extract)... BTW it worked last week as I'm working to get gcc47 built correctly.

gcc -lssl -lcrypto -L/home/richard/src/pkgsrc/bootstrap/work/wrk/pkgtools/pkg_install/work/libarchive/.libs -L/home/richard/src/pkgsrc/bootstrap/work/wrk/pkgtools/pkg_install/work/libfetch -L/home/richard/src/pkgsrc/bootstrap/work/wrk/pkgtools/pkg_install/work/libnbcompat -L/usr/lib -Wl,-R/usr/lib -Wl,-R/usr/pkg/lib -L../lib -o pkg_create main.o perform.o pl.o util.o build.o -linstall -lfetch -lsocket -lnsl -larchive -lbz2 -lz -lnbcompat -lcrypto -lnbcompat
Undefined           first referenced
 symbol                 in file
lzma_memusage                       /home/richard/src/pkgsrc/bootstrap/work/wrk/pkgtools/pkg_install/work/libarchive/.libs/libarchive.a(archive_write_set_compression_xz.o)
lzma_lzma_preset                    /home/richard/src/pkgsrc/bootstrap/work/wrk/pkgtools/pkg_install/work/libarchive/.libs/libarchive.a(archive_write_set_compression_xz.o)
lzma_end                            /home/richard/src/pkgsrc/bootstrap/work/wrk/pkgtools/pkg_install/work/libarchive/.libs/libarchive.a(archive_write_set_compression_xz.o)
lzma_code                           /home/richard/src/pkgsrc/bootstrap/work/wrk/pkgtools/pkg_install/work/libarchive/.libs/libarchive.a(archive_write_set_compression_xz.o)
lzma_stream_encoder                 /home/richard/src/pkgsrc/bootstrap/work/wrk/pkgtools/pkg_install/work/libarchive/.libs/libarchive.a(archive_write_set_compression_xz.o)
lzma_alone_encoder                  /home/richard/src/pkgsrc/bootstrap/work/wrk/pkgtools/pkg_install/work/libarchive/.libs/libarchive.a(archive_write_set_compression_xz.o)
ld: fatal: symbol referencing errors. No output written to pkg_create

package compress/xz is installed on the system, so it seems (on this system at least) that the build omits to include liblzma .  Will try from scratch on smartos as soon as I can...
for what it's worth, I'm using (after . /opt/dtbld/bin/env.sh gcc4.4) the following command (with a /usr/pkg and /var/db/pkg clean):
pfexec env CC=/opt/gcc/4.4.4/bin/gcc GCCBASE=/opt/gcc/4.4.4 __GNUC="" __GNUC4="" ./bootstrap --abi=64

**Comment by jperkin** [comment]
You can try passing --prefer-pkgsrc=yes to the bootstrap command line to avoid possible broken packages in the core OS.

BTW there is no need to set the __GNUC stuff for pkgsrc, and I'm not sure what the env.sh script does but that is almost certainly not required either.  Just set a reasonable $PATH which includes ld etc and it should be fine.

**Comment by ghost** [comment]
Will try to get back to this some next week or so. did you get my email concerning ncurses problem and missing /opt/local/lib/*?
BTW, /usr/bin/env - set environment for command invocation  ... see $man /usr/bin/env

**Comment by jperkin** [comment]
I know what env does, I meant /opt/dtbld/bin/env.sh :)

I haven't seen an email about ncurses, where was it sent?

**Comment by ghost** [comment]
I realised that after I responded... sorry for the dumb reply.
Here is my mail attached:

## 

Richard PALO
TNT PACA, dénomination commerciale de la société BAOU
SAS au capital de 50.000 € - RCS TOULON 441 322 385 - APE 4322B
117, av Marcel Berre - ZI Camp Laurent - 83500 LA SEYNE SUR MER
tél:04.94.94.39.94 fax:04.94.87.86.67 mailto:Richard.PALO@baou.fr
» Avant d'imprimer, pensez aux conséquences environnementales «
