### ISSUE TITLE
ACCESSPERMS et co missing in sys/stat.h

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#12]
Came across a small anomaly in building gedit, namely a missing definition of ACCESSPERMS which is referenced in test/document-saver.c

Search the web I noticed (here https://mail.gnome.org/archives/commits-list/2010-June/msg09709.html)  the following patch workaround that has not been ( and probably will never be) integrated upstream in Gnome:

```
diff --git a/tests/document-saver.c b/tests/document-saver.c
index e5da2b6..ef97fe6 100644
--- a/tests/document-saver.c
+++ b/tests/document-saver.c
@@ -27,6 +27,11 @@
 #include <string.h>
 #include <sys/stat.h>

+/* linux/bsd has it. others such as Solaris, do not */
+#ifndef ACCESSPERMS
+#define ACCESSPERMS (S_IRWXU|S_IRWXG|S_IRWXO) 
+#endif
+
 #define DEFAULT_LOCAL_URI "/tmp/gedit-document-saver-test.txt"
 #define DEFAULT_REMOTE_URI "sftp://localhost/tmp/gedit-document-saver-test.txt";
 #define DEFAULT_CONTENT "hello world!"
```

indeed, illumos falls into this category, and I'm able to complete the build with this workaround.

The thing is, seems worthwhile to propose the patch to the illumos tree as opposed to dirty workarounds.

What is Joyent's feeling about an adaptation of the following found in netbsd sys/stat.h

```
    168 #if defined(_NETBSD_SOURCE)
    169 #define ACCESSPERMS (S_IRWXU|S_IRWXG|S_IRWXO)   /* 0777 */
    170                             /* 7777 */
    171 #define ALLPERMS    (S_ISUID|S_ISGID|S_ISTXT|S_IRWXU|S_IRWXG|S_IRWXO)
    172                             /* 0666 */
    173 #define DEFFILEMODE (S_IRUSR|S_IWUSR|S_IRGRP|S_IWGRP|S_IROTH|S_IWOTH)
    174 
    175 #define S_BLKSIZE   512     /* block size used in the stat struct */
    176 
    177 /*
    178  * Definitions of flags stored in file flags word.
    179  *
    180  * Super-user and owner changeable flags.
    181  */
    182 #define UF_SETTABLE 0x0000ffff  /* mask of owner changeable flags */
    183 #define UF_NODUMP   0x00000001  /* do not dump file */
    184 #define UF_IMMUTABLE    0x00000002  /* file may not be changed */
    185 #define UF_APPEND   0x00000004  /* writes to file may only append */
    186 #define UF_OPAQUE   0x00000008  /* directory is opaque wrt. union */
    187 /*  UF_NOUNLINK 0x00000010     [NOT IMPLEMENTED] */
    188 /*
    189  * Super-user changeable flags.
    190  */
    191 #define SF_SETTABLE 0xffff0000  /* mask of superuser changeable flags */
    192 #define SF_ARCHIVED 0x00010000  /* file is archived */
    193 #define SF_IMMUTABLE    0x00020000  /* file may not be changed */
    194 #define SF_APPEND   0x00040000  /* writes to file may only append */
    195 /*  SF_NOUNLINK 0x00100000     [NOT IMPLEMENTED] */
    196 #define SF_SNAPSHOT 0x00200000  /* snapshot inode */
    197 #define SF_LOG      0x00400000  /* WAPBL log file inode */
    198 #define SF_SNAPINVAL    0x00800000  /* snapshot is invalid */
    199 
    200 #ifdef _KERNEL
    201 /*
    202  * Shorthand abbreviations of above.
    203  */
    204 #define OPAQUE      (UF_OPAQUE)
    205 #define APPEND      (UF_APPEND | SF_APPEND)
    206 #define IMMUTABLE   (UF_IMMUTABLE | SF_IMMUTABLE)
    207 #endif /* _KERNEL */
    208 #endif /* _NETBSD_SOURCE */
```

similar for freebsd found http://src.illumos.org/source/xref/freebsd-head/sys/sys/stat.h

**Comment by jperkin** [comment]
This appears to be the only use of that define in pkgsrc, at least it's currently the only package which is failing to build because of it.  Thus I don't think it'd be useful enough to go into illumos, and I've patched the package in pkgsrc instead.

**Comment by ghost** [comment]
ok by me, which revision contains your patch?

**Comment by jperkin** [comment]
- On 2012-10-26 at 17:25 BST, risto3 wrote:

> ok by me, which revision contains your patch?

http://mail-index.netbsd.org/pkgsrc-changes/2012/10/26/msg080276.html

## 

Jonathan Perkin       www.perkin.org.uk
github.com/jperkin  twitter.com/jperkin

**Comment by ghost** [comment]
not really up to snuff on the workflow between github.com/joyent/pkgsrc and the upstream bits.
is there a magic incantation, or is it _patience_ until it hits joyent/pkgsrc/trunk?

**Comment by jperkin** [comment]
- On 2012-10-26 at 17:48 BST, risto3 wrote:

> not really up to snuff on the workflow between
> github.com/joyent/pkgsrc and the upstream bits.  is there a magic
> incantation, or is it _patience_ until it hits joyent/pkgsrc/trunk?

Just some patience :)

## 

Jonathan Perkin       www.perkin.org.uk
github.com/jperkin  twitter.com/jperkin
