### ISSUE TITLE
-fomit-frame-pointer considered harmful

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#121]
gcc should accept and ignore -fomit-frame-pointer instead of omitting the frame pointer.  This option has no positive benefits and causes the resulting binaries to be impossible to debug.  Since many automated build systems apply this argument even when the end user has not consciously chosen to create an undebuggable binary, the sensible thing to do is to simply ignore the option.

**Comment by jperkin** [comment]
I implemented this for 2013Q4 onwards.
