### ISSUE TITLE
Samba 4 packages

### ISSUE THREAD

**Issue by gzartman** [TritonDataCenter/pkgsrc-legacy#159]
It would be very useful to have Samba 4 packages for the Base64 image.  Most of the real windows active directory functions are only available in Samba 4

**Comment by mamash** [comment]
Available now in 2013Q3/2013Q4.

**Comment by stateless** [comment]
Was this issue closed in error? Reference in the changelog seems wrong.

"" #159: libproxy fails with autoconfiguration "http://proxy.domain.com" ""

**Comment by jperkin** [comment]
Yes, GitHub has a mis-feature where any #<number> in the commit message will match the current repository being pushed to.  As we include changelogs in pkgsrc updates they frequently match tickets we have open which have nothing to do with those changelogs.

We've reported this to GitHub and requested that they at least provide an option where you have to specify the full repository to get this auto-close to take effect, e.g. joyent/pkgsrc#<number> but they seem uninterested in doing this.

All we can do is keep re-opening these tickets, which I've done now.

**Comment by stateless** [comment]
Seems that samba4 work for pkgsrc is at: https://github.com/joyent/pkgsrc-wip/tree/joyent/samba

**Comment by jperkin** [comment]
Fixed properly in https://github.com/joyent/pkgsrc-wip/commit/fca72fe533d470210ed04d7fa9b51cfefc6e36f1, will be available in `pkgsrc-2014Q4` next week.
