### ISSUE TITLE
missing dependency for joyent/smtools

### ISSUE THREAD

**Issue by MerlinDMC** [TritonDataCenter/pkgsrc-legacy#166]
`sm-meminfo swap` assumes GNU df but doesn't depend on coreutils

**Comment by rmustacc** [comment]
We should just fix it so it doesn't assume a particular df.

**Comment by mamash** [comment]
I'm pretty sure there's no particular reason it actually uses GNU df. I'll let Derek know.

**Comment by dcrudgington** [comment]
Just put a fix in to use platform df instead.  Thanks for the heads up.

**Comment by mamash** [comment]
Fixed in 2013Q3 earlier.
