### ISSUE TITLE
www/nginx: add NAXSI and PAGESPEED

### ISSUE THREAD

**Issue by bsdhsr** [TritonDataCenter/pkgsrc-legacy#167]
Please consider editing the relevant files so that the package has these modules by default:

https://github.com/nbs-system/naxsi
https://github.com/pagespeed/ngx_pagespeed

These are awesome modules and having them available without needing to compile nginx would be amazing.

**Comment by mamash** [comment]
Unfortunately PageSpeed is next to impossible to build on any non-supported platform (which is anything but Linux and OS X in Google's eyes). NAXSI is possible, we'll see about that.

**Comment by bsdhsr** [comment]
I was not aware pagespeed was such a pain to build on other platforms. What a shame!

Looking forward for the possible addition of naxsi. Thanks!
