### ISSUE TITLE
Getting ap24-auth-kerb to build

### ISSUE THREAD

**Issue by nshalman** [TritonDataCenter/pkgsrc-legacy#168]
The patches from the Fedora project appear to fix the build.
http://pkgs.fedoraproject.org/cgit/mod_auth_kerb.git/tree/

The spec file applies them in this order:
Patch1: mod_auth_kerb-5.4-rcopshack.patch
Patch2: mod_auth_kerb-5.4-fixes.patch
Patch3: mod_auth_kerb-5.4-s4u2proxy.patch
Patch4: mod_auth_kerb-5.4-httpd24.patch
Patch5: mod_auth_kerb-5.4-delegation.patch
Patch6: mod_auth_kerb-5.4-cachedir.patch
Patch7: mod_auth_kerb-5.4-longuser.patch
Patch8: mod_auth_kerb-5.4-handle-continue.patch

It would be nice to have this for 2013Q4 if there's time.

**Comment by nshalman** [comment]
Pull request #172 supersedes this issue.

**Comment by njones11** [comment]
+1

I'm also being bitten by not having working mod_auth_kerb packages.
