### ISSUE TITLE
python-lockfile seems unusable

### ISSUE THREAD

**Issue by jeffpc** [TritonDataCenter/pkgsrc-legacy#170]
Based on this (http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=581061) bug report for Debian, it would seem that python-lockfile 0.9.x broke compatibility with other commonly used python modules. Debian maintainers reverted the package to 0.8.x.  It appears that even after several years, Debian still ships the 0.8.x package.

I ran into this issue with a c353c568-69ad-11e3-a248-db288786ea63 based zone.  I tried to set up calypso from upstream's git repo since the package is very old.

```
[root@test ~/calypso]# python2.7 ./calypso.py -fg
Traceback (most recent call last):
  File "./calypso.py", line 40, in <module>
    from daemon import pidlockfile
  File "/opt/local/lib/python2.7/site-packages/daemon/pidlockfile.py", line 33, in <module>
    class PIDLockFile(LinkFileLock, object):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
```

**Comment by jperkin** [comment]
Sorry it's taken so long to get to this.  I tested this on 2016Q1 and it appears that since this issue was created the problem has been fixed somewhere along the line:

```
$ git clone git://keithp.com/git/calypso
$ cd calypso
$ python2.7 ./calypso.py -fg
Traceback (most recent call last):
  File "./calypso.py", line 39, in <module>
    import daemon
ImportError: No module named daemon
$ pkg_add py27-daemon
$ python2.7 ./calypso.py -fg
enable debugging
```

As for the calypso package, it appears to be using the most recent release (1.3) so there's not much we can do there.
