### ISSUE TITLE
lua-sec: fatal: relocation error: R_AMD64_PC32: file /opt/local/lib/lua/5.2/ssl.so: symbol main: value 0x2801308e5d4 does not fit 

### ISSUE THREAD

**Issue by bsdhsr** [TritonDataCenter/pkgsrc-legacy#177]
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

> require "ssl"
> error loading module 'ssl.core' from file '/opt/local/lib/lua/5.1/ssl.so':
>         ld.so.1: lua: fatal: relocation error: R_AMD64_PC32: file /opt/local/lib/lua/5.1/ssl.so: symbol main: value 0x280130fe404 does not fit
> stack traceback:
>         [C]: ?
>         [C]: in function 'require'
>         /opt/local/share/lua/5.1/ssl.lua:9: in main chunk
>         [C]: in function 'require'
>         stdin:1: in main chunk
>         [C]: ?

**Comment by mamash** [comment]
I fixed this earlier (JPC sets for 2013Q3/2013Q4 and on should have a fixed version of the package).
