### ISSUE TITLE
SMF Manifest for DDclient package

### ISSUE THREAD

**Issue by gzartman** [TritonDataCenter/pkgsrc-legacy#178]
I created a SMF manifest for the current ddclient package in the Base64 repo.   The xml manifest is just a rework on a manifest I found from an older solaris service.  I created the xml in : /opt/local/lib/svc/manifest/ddclient.xml

<?xml version="1.0"?>

<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">

<service_bundle type='manifest' name='ddclient'>

<service
        name='network/ddclient'
        type='service'
        version='1'>

```
    <create_default_instance enabled='true' />

    <dependency
            name='network'
            grouping='require_all'
            restart_on='none'
            type='service'>
            <service_fmri value='svc:/network/initial:default' />
    </dependency>

    <exec_method
            type='method'
            name='start'
            exec='/opt/local/sbin/ddclient'
            timeout_seconds='0' />

    <exec_method
            type='method'
            name='stop'
            exec=':kill -15'
            timeout_seconds='3' />

    <stability value='Unstable'/>

    <template>
           <common_name>
                   <loctext xml:lang='C'>Dynamic DNS client</loctext>
           </common_name>
    </template>
```

</service>
</service_bundle>

**Comment by jperkin** [comment]
I've committed this with a couple of minor changes. Manifest will now exist in 2014Q2 packages.

Thanks for the contribution. In the future, putting the manifest in code sections will help, otherwise the formatting will make them unusable. Alternatively attach them as a separate file. Thanks!
