### ISSUE TITLE
add package bwm-ng

### ISSUE THREAD

**Issue by bahamas10** [TritonDataCenter/pkgsrc-legacy#185]
# summary

Add package `net/bwm-ng` (http://www.gropp.org/?id=projects&sub=bwm-ng) to pkgsrc

I attempted to follow the steps located here http://pkgsrc.joyent.com/creating.html but was unsuccessful.

```
dave @ [ dave-01 :: (SunOS) ] ~/pkgsrc/net/bwm-ng $ url2pkg http://www.gropp.org/bwm-ng/bwm-ng-0.6.tar.gz
/opt/local/bin/url2pkg must be run from a package directory (.../pkgsrc/category/package). at /opt/local/bin/url2pkg line 464.
```

Looking at the source, it checks for the existence of a file that is not there

``` perl
if (!-f "../../mk/bsd.pkg.mk") {
    die("$0 must be run from a package directory (.../pkgsrc/category/package).");
}
```

So most likely I'm supposed to run this out of a specific directory... either way I've attached the steps I use to compile `bwm-ng` on SmartOS.

Please let me know if there is more information I can supply
# compilation

To get this working on SmartOS, I simply run

```
wget http://www.gropp.org/bwm-ng/bwm-ng-0.6.tar.gz
tar xf bwm-ng-0.6.tar.gz 
cd bwm-ng-0.6/
./configure --prefix=/opt/local
make all
make install
```

and this installs the following (using `ginstall`)

```
/opt/local/bin/ginstall -c 'bwm-ng' '/opt/local/bin/bwm-ng'
/opt/local/bin/ginstall -c -m 644 './bwm-ng.1' '/opt/local/share/man/man1/bwm-ng.1'
```
# license

GPLv2

**Comment by mamash** [comment]
bwm-ng has already existed in pkgsrc as wip/bwm-ng. I added it to our build list now (we do not normally build all packages in the 'wip' subtree), so it should be available in the next rebuild of 2013Q3-2014Q1 (and on).

**Comment by jperkin** [comment]
url2pkg needs a working pkgsrc tree to function, hence the mk/bsd.pkg.mk errors. Is there anything I need to clarify in the documentation?
