### ISSUE TITLE
mpich pkg, bad library path, compilation fail

### ISSUE THREAD

**Issue by nickziv** [TritonDataCenter/pkgsrc-legacy#186]
The mpich package uses mpicc to compile C programs.
mpicc is a bash script located at /opt/local/bin/mpicc.

Currently mpicc fails with the following error when trying to compile any program:

```
] mpicc -o hw hw.c
ld: fatal: file /usr/lib/amd64/libgcc_s.so.1: version 'GCC_4.5.0' does
not exist:
        required by file
/opt/local/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.3/../../../../x86_64-sun-solaris2.11/lib/amd64/libgfortran.so.3
ld: fatal: file /usr/lib/amd64/libgcc_s.so.1: version 'GCC_4.5.0' does
not exist:
        required by file
/opt/local/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.3/../../../../x86_64-sun-solaris2.11/lib/amd64/libquadmath.so.0
ld: fatal: file processing errors. No output written to hw
collect2: error: ld returned 1 exit status
]
```

The problem is that the script has a "bad" LDFLAGS variable. It reads like so:

LDFLAGS="-L/opt/local/lib -Wl,-R/opt/local/lib -L/opt/local/lib
-L/opt/local/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.3
-Wl,-R/opt/local/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.3
-L/opt/local/gcc47/lib -Wl,-R/opt/local/gcc47/lib **-L/usr/lib/amd64**
-Wl,**-R/usr/lib/amd64** -L/opt/local/lib -Wl,-R/opt/local/lib "

The LDFLAGS variable should _not_ have any /usr/lib/amd64 paths. So they should be replaced with /opt/local/lib/amd64. Modifying LDFLAGS to read as follows fixed the problem, and mpicc works fine now:

LDFLAGS="-L/opt/local/lib -Wl,-R/opt/local/lib -L/opt/local/lib -L/opt/local/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.3 -Wl,-R/opt/local/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.3 -L/opt/local/gcc47/lib -Wl,-R/opt/local/gcc47/lib **-L/opt/local/lib/amd64** -Wl, **-R/opt/local/lib/amd64** -L/opt/local/lib -Wl,-R/opt/local/lib "

**Comment by mamash** [comment]
Nick, can you clarify which package set is this happening on? I couldn't quite reproduce on 2013Q4/x86_64, and I'm thinking maybe you're playing with the multiarch one?

**Comment by mamash** [comment]
Nevermind, was able to reproduce on a newer platform. The fix actually is to _not_ include the /usr/lib/amd64 path at all (no need to add /opt/local/lib/amd64, which won't have anything useful anyway). I'll see to implement this.

**Comment by nshalman** [comment]
this seems like an accidental closure...

edit: Does someone want to re-open it? (I can't...)
