### ISSUE TITLE
'hevea' package missing runtime dependency

### ISSUE THREAD

**Issue by nickziv** [TritonDataCenter/pkgsrc-legacy#193]
The hevea package, which is used to convert LaTeX files into HTML files, is written in Ocaml. It depends on the ocamlrun binary, which is not installed along with hevea, forcing the user to manually install the ocaml package.

**Comment by jperkin** [comment]
Sorry for taking so long to get to this issue.  The problem appears to have been fixed with the update to 2.23 in 02a480d66db4e601a7087ef598e01429241c5ff5.
