### ISSUE TITLE
openjdk7: JavaScript engine broken

### ISSUE THREAD

**Issue by alain-odea-vgh** [TritonDataCenter/pkgsrc-legacy#195]
```
# /opt/local/java/openjdk7/bin/jrunscript
Exception in thread "main" java.lang.NoClassDefFoundError: org/mozilla/javascript/ContextFactory
        at com.sun.script.javascript.RhinoScriptEngine.<clinit>(RhinoScriptEngine.java:71)
        at com.sun.script.javascript.RhinoScriptEngineFactory.getScriptEngine(RhinoScriptEngineFactory.java:74)
        at javax.script.ScriptEngineManager.getEngineByName(ScriptEngineManager.java:235)
        at com.sun.tools.script.shell.Main.getScriptEngine(Main.java:411)
        at com.sun.tools.script.shell.Main.processOptions(Main.java:169)
        at com.sun.tools.script.shell.Main.main(Main.java:44)
```

This breaks our use of Togglz and DustServlet.

Also reported to Joyent Support:
https://help.joyent.com/requests/154651

**Comment by alain-odea-vgh** [comment]
This issue also happens with openjdk7-1.7.51nb2 in PKGSRC 2014Q1 with the exact same symptoms.

**Comment by mamash** [comment]
I'm investigating this issue in our support system (based on your ticket), but just in case somebody is looking here...

The problem seems to be that the pkgsrc package for OpenJDK7 is fetching the Rhino JS engine externally, rather than using the one bundled with the OpenJDK7 tarball. The classes referenced in the error are thus in a different name space, which is all patched in several Java files properly, and end up included inside rhino.jar with the package. However, looks like run time tools do not know to look inside rhino.jar at all, for they never touch it.

**Comment by alain-odea-vgh** [comment]
Thank you @mamash.  I'm able to quickly test pre-releases packages as needed.

**Comment by mamash** [comment]
I believe I was able to fix this. Is there a simply enough to relay, more thorough test I can run? This works now at least:

```
-> /opt/local/java/openjdk7/bin/jrunscript
js> quit()
-> /opt/local/java/openjdk7/bin/jrunscript -q
Language ECMAScript 1.8 implemention "Mozilla Rhino" 1.7 release 3 PRERELEASE
```

**Comment by mamash** [comment]
You can test the following package (openjdk7-1.7.25nb3.tgz), it's a 64bit one, built against 2013Q4:

http://bit.ly/1qHB2Fm

**Comment by AlainODea** [comment]
Thank you @mamash!  You are the best.  I will test this today.

The jrunscript was our surface test.  If it works, it's likely to make DustServlet and Togglz work again.

**Comment by alain-odea-vgh** [comment]
@mamash the ScriptEngine for JavaScript works :)

Hello.java:

``` java
import javax.script.*;

public class Hello {
    public static void main(String[] args) throws Exception {
        ScriptEngineManager factory = new ScriptEngineManager();
        ScriptEngine engine = factory.getEngineByName("JavaScript");
        engine.eval("print('Hello, SmartOS!\\n')");
    }
}
```

Compile and run it:

```
# javac Hello.java 
# java Hello
Hello, SmartOS!
```

I'm testing our app now and will report back soon.

**Comment by alain-odea-vgh** [comment]
Tested to pass tests and fix all related issues for us.  Thanks again @mamash :)

**Comment by mamash** [comment]
Alain, the openjdk7-1.7.51nb3  package in 2014Q1 contains the fix now. Will that work for you, or do you need it backported to e.g. 2013Q4?

**Comment by AlainODea** [comment]
@mamash it would be handy if it were backported.  If not, it's a good opportunity for us to improve deployment if we need to respin so it's your call :)

**Comment by mamash** [comment]
This was backported to 2013Q4 too earlier.

**Comment by alain-odea-vgh** [comment]
@mamash thank you very much again for this. You are a life saver.
