### ISSUE TITLE
compiler_lib_search_dirs libtool incorrect when compiling 64bit

### ISSUE THREAD

**Issue by briankwest** [TritonDataCenter/pkgsrc-legacy#200]
Not sure where this bug is or if its been corrected already or even how to correct it.

Trying to compile a 64bit build of FreeSWITCH on SmartOS we end up with compiler_lib_search_dirs in libtool with these values in order:

(64bit) /opt/local/lib/ 
(64bit) /opt/local/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.3 
(64bit) /opt/local/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.3/../../../../x86_64-sun-solaris2.11/lib/amd64 
(64bit) /opt/local/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.3/../../../amd64 
(64bit) /lib/amd64 
(64bit) /usr/lib/amd64 
(32bit) /opt/local/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.3/../../../../x86_64-sun-solaris2.11/lib 
(32bit) /opt/local/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.3/../../.. 
(64bit) /opt/local/gcc47/x86_64-sun-solaris2.11/lib/amd64 
(64bit) /opt/local/gcc47/lib/amd64 

When linking to -llibstdc++ since the 32bit directory is before the two 64bit directories that contain libstdc++.so for 64bit.

Resulting in /opt/local/gcc47/lib/libstdc++.so: wrong ELF class: ELFCLASS32

Any idea how to fix this?  I do not have the same problem on Solaris 11.1, It also excludes any paths that are 32bit from compiler_lib_search_dirs, I've also tried CC='gcc -m64' and CXX='g++ -m64' it fails.

If I force the LDFLAGS like so:

LDFLAGS='-L/opt/local/gcc47/lib/amd64' ./configure --enable-64 

It works, but I shouldn't have to do that step.

Thoughts?

**Comment by briankwest** [comment]
Seems everything in /opt/local/lib/ has the offending -L/opt/local/gcc47/lib in their .la files all of which are 64bit packages.

/b

**Comment by briankwest** [comment]
cd /opt/local/lib/
perl -i -pe 's/gcc47\/lib /gcc47\/lib\/amd64 /g' *.la

Actually worked and allowed the build to not mess up.

**Comment by jperkin** [comment]
This is fixed in pkgsrc-2014Q2 which will be released shortly. Thanks for the report!
