### ISSUE TITLE
www/nginx: NetBSD MESSAGE file displayed after install

### ISSUE THREAD

**Issue by abyxcos** [TritonDataCenter/pkgsrc-legacy#203]
When installing nginx-1.4.7nb6, the NetBSD MESSAGE file gets printed out with inappropriate instructions for setting up log rotations. Printout reproduced below.
# 

$NetBSD: MESSAGE,v 1.2 2013/02/18 20:32:09 imil Exp $

Consider adding something like following lines to /etc/newsyslog.conf:

/var/log/nginx/access.log www:www 640 7 \* 24 Z  /var/db/nginx/nginx.pid SIGUSR1
/var/log/nginx/error.log  www:www 640 7 \* 24 Z  /var/db/nginx/nginx.pid SIGUSR1
#

**Comment by abyxcos** [comment]
Based on my reading of logadm(1m), the correct suggestion is likely as follows:

``` conf
===========================================================================
Consider adding something like following lines to /etc/logadm.conf:

/var/log/nginx/access.log -C 7 -a 'kill -SIGUSR1 `cat /var/db/nginx/nginx.pid`'
/var/log/nginx/error.log  -C 7 -a 'kill -SIGUSR1 `cat /var/db/nginx/nginx.pid`'
===========================================================================
```

**Comment by mamash** [comment]
pkgsrc is multiplatform by design, so its actually inappropriate to have either implementation suggested that way. However, we have a long standing Joyent ticket to implement modular log rotating logic to pick between e.g. logadm, logrotate etc. and automatically handle adding/removal, as an ultimate fix for such.

**Comment by abyxcos** [comment]
I agree with the sentiment, @jperkin sent me over here to file a ticket regarding a conditional display though. I feel that nginx may be one of the exceptions as it's a fairly popular package. Does pkgsrc/pkgin have a method to handle MESSAGE.platform files?

Regarding the logging, does that look roughly right?

**Comment by mamash** [comment]
Actually the Nginx package we carry (at least those built in the past year) already come with logadm logic in place. Once the package is installed, the following command is executed that adds the config to logadm.conf:

`logadm -C 5 -c -s 100m -z 1 -w /var/log/nginx/*.log`

We added a similar bit to many other packages.

The MESSAGE is unfortunate, though probably driven by the same sentiment that you just mentioned: that it's a popular package. However, logrotate is by no means a NetBSD-specific tool. Maybe we should just drop the file in our local branch and be done with it.
