### ISSUE TITLE
Missing header files in php54-json and php55-json packages

### ISSUE THREAD

**Issue by yruss972** [TritonDataCenter/pkgsrc-legacy#207]
Hi,

We're running into issues compiling php extensions via PECL due to missing the header file:
ext/json/php_json.h

The extension packages include only the .so files:
# pkgin pc php55-json

Information for http://pkgsrc.joyent.com/packages/SmartOS/2014Q1/x86_64/All/php55-json-5.5.10.tgz:
Files:
/opt/local/lib/php/20130620/json.so
# pkgin pc php54-json

Information for http://pkgsrc.joyent.com/packages/SmartOS/2014Q1/x86_64/All/php54-json-5.4.26.tgz:
Files:
/opt/local/lib/php/20120301/json.so

Presumably these should be installed with the extensions.

**Comment by mamash** [comment]
Yonah, out of curiosity, which PECL extensions depend on the JSON headers? And yes, traditionally only the shared libs are installed with _all_ the PHP packages in pkgsrc, but I know I hit this before with mailparse vs. mbstring headers, so it should be fixed.

**Comment by jperkin** [comment]
Fixed in https://github.com/NetBSD/pkgsrc/commit/842cd37885101cbff7646bf97536a7e701091bbf.
