### ISSUE TITLE
rabbitmq package does not work out of the box

### ISSUE THREAD

**Issue by djensen47** [TritonDataCenter/pkgsrc-legacy#210]
1. Spin up a Joyent SmartOS instance. (When running SmartOS on VMWare I do not experience this issue).
2. Install rabbitmq
   `pkgin install rabbitmq`
3. At this point rabbitmq _should_ be working. It is not. Attempts to enable `svcadm enable rabbitmq` will fail
4. It turns out that epmd needs to be running. If epmd is running, kill it first
   `svcadm disable rabbitmq`
   `svcadm enable epmd`
   `svcadm enable rabbitmq`

Joyent employees can refer to this ticket: http://help.joyent.com/requests/153357

**Comment by mamash** [comment]
This is desired. The epmd service comes with the erlang service, not rabbitmq. When you enable rabbitmq for the first time, it's 'offline' and inspecting the service with `svcs -vx rabbitmq` will tell you the reason (that the dependency service is not running). Once you enable epmd too, rabbitmq will start up automatically (no need to disable/re-enable).

You can also `svcadm enable -r rabbitmq` to enable its dependencies as well.

**Comment by chorrell** [comment]
Would it be possible to have that command mentioned in the post install instructions?

I think the initial `/usr/sbin/svcadm enable svc:/pkgsrc/epmd:default` get's overlooked since it scrolls past) so having just this for rabbitmq might be better:

```
 /usr/sbin/svcadm enable -r svc:/pkgsrc/rabbitmq:default
```

**Comment by mamash** [comment]
Starting with 2014Q4, the command suggested was changed to 'svcadm enable -r'.
