### ISSUE TITLE
2014Q2 postgresql93-server broken

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/pkgsrc-legacy#211]
Hey All,

The SMF manifest seems to be broken and the file /opt/local/lib/svc/method/postgresql is also missing.

Regards

**Comment by sjorge** [comment]
Some more testing (I know some of them are a bad idea but due to this bug I am rebuilding this zone with the previous base image)
- source compile has same issue
- seems all the 9x series is effected did not try other version
- switching to the Q1 repo and pulling in only postgresql93-server works (switched back after)
- additionally building from the Q1 source also works.

Regards

**Comment by sjorge** [comment]
Actually a lot is broken :O same for clamav's freshclam SMF, possibly others!

**Comment by sjorge** [comment]
+mysql also effected

**Comment by mamash** [comment]
I'm looking at it, Jorge. Sounds like a regression in placeholder substitution. We'll identify all affected packages and rebuild.

**Comment by sjorge** [comment]
Alright, for now I've reverted my stuff to the prev. base64. All is fine there.

**Comment by jperkin** [comment]
Sorry about that, rebuilds are currently in progress, and I've also added a regression test which should hopefully catch these in the future before the package is released.

**Comment by sjorge** [comment]
Cool, well stuff happens from time to time so don't sweat it too much. I'm just surprised it took so long for a user to catch it!

**Comment by mamash** [comment]
This was fixed in yesterday's rebuilds of 2014Q2.
