### ISSUE TITLE
powerdns and pdns-recursor could use a SMF manifest

### ISSUE THREAD

**Issue by jeffpc** [TritonDataCenter/pkgsrc-legacy#215]
They are two daemons but they lack SMF manifests making the packages less useful.

**Comment by alcir** [comment]
Someone has already written such SMF manifests?

**Comment by mamash** [comment]
I've added a simple manifest to powerdns for the authoritative server together with the update to 3.4.1 that I just committed into upstream pkgsrc (to be released with 2014Q4).
