### ISSUE TITLE
dtrace: failed to compile script ../dix/Xserver.d: Preprocessor not found

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#22]
I'd like to keep dtrace, but since gcc is now in /opt/pkg/gcc\* and not in the standard solaris place the following happens by default during compile:

```
/usr/sbin/dtrace -G -C -o dtrace-dix.o -s ../dix/Xserver.d .libs/*.o
dtrace: failed to compile script ../dix/Xserver.d: Preprocessor not found
gmake[2]: *** [dtrace-dix.o] Error 1
gmake[2]: Leaving directory `/tmp/pkgsrc/x11/modular-xorg-server/work/xorg-server-1.6.5/dix'
gmake[1]: *** [all] Error 2
gmake[1]: Leaving directory `/tmp/pkgsrc/x11/modular-xorg-server/work/xorg-server-1.6.5/dix'
gmake: *** [all-recursive] Error 1
```

manually, this can work with the xcpppath indicated as follows:

```
richard@devzone:/tmp/pkgsrc/x11/modular-xorg-server/work/xorg-server-1.6.5/dix$ /usr/sbin/dtrace -G -C -xcpppath=/opt/pkg/gcc47/bin/cpp   -o dtrace-dix.o -s ../dix/Xserver.d .libs/*.o                                                               
<command-line>:0:0: warning: "__STDC__" redefined [-Wbuiltin-macro-redefined]
```

is there a way to globally _fix_ dtrace to find the correct 'cpppath', perhaps in mk.conf?
A patch to the makefile to hardcode `-xcpppath=` seems doomed to failure, but perhaps a combination using CPPPATH?

here is the makefile bits:

```
richard@devzone:/tmp/pkgsrc/x11/modular-xorg-server/work/xorg-server-1.6.5/dix$ grep -i dtrace Makefile*
Makefile:DTRACE = /usr/sbin/dtrace
Makefile:EXTRA_DIST = buildatoms BuiltInAtoms Xserver.d Xserver-dtrace.h.in
Makefile:# Generate dtrace header file for C sources to include
Makefile:BUILT_SOURCES = Xserver-dtrace.h
Makefile:Xserver-dtrace.h: $(srcdir)/Xserver.d
Makefile:       $(DTRACE) -C -h -o $@ -s $(srcdir)/Xserver.d \
Makefile:               || cp Xserver-dtrace.h.in $@
Makefile:# Generate dtrace object code for probes in libdix
Makefile:dtrace-dix.o: $(top_srcdir)/dix/Xserver.d $(am_libdix_la_OBJECTS)
Makefile:       $(DTRACE) -G -C -o $@ -s $(top_srcdir)/dix/Xserver.d .libs/*.o
Makefile:dix.O: dtrace-dix.o $(am_libdix_la_OBJECTS)
Makefile.am:EXTRA_DIST = buildatoms BuiltInAtoms Xserver.d Xserver-dtrace.h.in
Makefile.am:if XSERVER_DTRACE
Makefile.am:# Generate dtrace header file for C sources to include
Makefile.am:BUILT_SOURCES = Xserver-dtrace.h
Makefile.am:Xserver-dtrace.h: $(srcdir)/Xserver.d
Makefile.am:    $(DTRACE) -C -h -o $@ -s $(srcdir)/Xserver.d \
Makefile.am:            || cp Xserver-dtrace.h.in $@
Makefile.am:# Generate dtrace object code for probes in libdix
Makefile.am:dtrace-dix.o: $(top_srcdir)/dix/Xserver.d $(am_libdix_la_OBJECTS)
Makefile.am:    $(DTRACE) -G -C -o $@ -s $(top_srcdir)/dix/Xserver.d .libs/*.o
Makefile.am:dix.O: dtrace-dix.o $(am_libdix_la_OBJECTS)
Makefile.in:@XSERVER_DTRACE_TRUE@noinst_PROGRAMS = dix.O$(EXEEXT)
Makefile.in:DTRACE = @DTRACE@
Makefile.in:EXTRA_DIST = buildatoms BuiltInAtoms Xserver.d Xserver-dtrace.h.in
Makefile.in:# Generate dtrace header file for C sources to include
Makefile.in:@XSERVER_DTRACE_TRUE@BUILT_SOURCES = Xserver-dtrace.h
Makefile.in:@XSERVER_DTRACE_FALSE@dix.O$(EXEEXT): $(dix_O_OBJECTS) $(dix_O_DEPENDENCIES) 
Makefile.in:@XSERVER_DTRACE_FALSE@      @rm -f dix.O$(EXEEXT)
Makefile.in:@XSERVER_DTRACE_FALSE@      $(LINK) $(dix_O_OBJECTS) $(dix_O_LDADD) $(LIBS)
Makefile.in:@XSERVER_DTRACE_TRUE@Xserver-dtrace.h: $(srcdir)/Xserver.d
Makefile.in:@XSERVER_DTRACE_TRUE@       $(DTRACE) -C -h -o $@ -s $(srcdir)/Xserver.d \
Makefile.in:@XSERVER_DTRACE_TRUE@               || cp Xserver-dtrace.h.in $@
Makefile.in:# Generate dtrace object code for probes in libdix
Makefile.in:@XSERVER_DTRACE_TRUE@dtrace-dix.o: $(top_srcdir)/dix/Xserver.d $(am_libdix_la_OBJECTS)
Makefile.in:@XSERVER_DTRACE_TRUE@       $(DTRACE) -G -C -o $@ -s $(top_srcdir)/dix/Xserver.d .libs/*.o
Makefile.in:@XSERVER_DTRACE_TRUE@dix.O: dtrace-dix.o $(am_libdix_la_OBJECTS)
Makefile.in:@XSERVER_DTRACE_TRUE@       ld -r -o $@ .libs/*.o
```

**Comment by rmustacc** [comment]
The default cpp for DTrace has never come from gcc. Rather it defaults to /usr/ccs/lib/cpp. /usr/ccs/lib should almost always just be a symlink to /usr/lib, and hence it should use /usr/lib/cpp. Do you not have a /usr/lib/cpp, or a corresponding symlink?

**Comment by ghost** [comment]
This is in a minimal devzone with the gz running oi_151a7 (I can attach the installed packages if needed)..

No /usr/lib/cpp and here is /usr/ccs.
`
richard@devzone:/home$ ls -l /usr/ccs    
total 6
drwxr-xr-x   3 root     bin           25 oct. 20 15:08 bin
drwxr-xr-x   3 root     bin           37 nov.  8 17:57 lib
richard@devzone:/home$ ls -l /usr/ccs/lib
total 37
drwxr-xr-x   2 root     bin           27 nov.  8 17:57 amd64
lrwxrwxrwx   1 root     root          17 oct. 20 15:08 cm4defs -> ../../lib/cm4defs
lrwxrwxrwx   1 root     root          14 oct. 20 15:08 help -> ../../lib/help
lrwxrwxrwx   1 root     root          27 oct. 20 15:08 libcurses.so -> ../../../lib/libcurses.so.1
lrwxrwxrwx   1 root     root          22 oct. 20 15:08 libform.so -> ../../lib/libform.so.1
lrwxrwxrwx   1 root     root          24 oct. 20 15:08 libgen.so -> ../../../lib/libgen.so.1
lrwxrwxrwx   1 root     root          19 oct. 20 15:08 libl.so -> ../../lib/libl.so.1
lrwxrwxrwx   1 root     root          24 oct. 20 15:08 libmalloc.so -> ../../lib/libmalloc.so.1
lrwxrwxrwx   1 root     root          22 oct. 20 15:08 libmenu.so -> ../../lib/libmenu.so.1
lrwxrwxrwx   1 root     root          23 oct. 20 15:08 libpanel.so -> ../../lib/libpanel.so.1
lrwxrwxrwx   1 root     root          28 oct. 20 15:08 libtermcap.so -> ../../../lib/libtermcap.so.1
lrwxrwxrwx   1 root     root          27 oct. 20 15:08 libtermlib.so -> ../../../lib/libcurses.so.1
lrwxrwxrwx   1 root     root          19 oct. 20 15:08 liby.so -> ../../lib/liby.so.1
lrwxrwxrwx   1 root     root          20 oct. 20 15:08 link_audit -> ../../lib/link_audit
lrwxrwxrwx   1 root     root          25 nov.  8 17:57 llib-lcurses -> ../../../lib/llib-lcurses
lrwxrwxrwx   1 root     root          28 nov.  8 17:57 llib-lcurses.ln -> ../../../lib/llib-lcurses.ln
lrwxrwxrwx   1 root     root          20 nov.  8 17:57 llib-lform -> ../../lib/llib-lform
lrwxrwxrwx   1 root     root          23 nov.  8 17:57 llib-lform.ln -> ../../lib/llib-lform.ln
lrwxrwxrwx   1 root     root          22 nov.  8 17:57 llib-lgen -> ../../../lib/llib-lgen
lrwxrwxrwx   1 root     root          25 nov.  8 17:57 llib-lgen.ln -> ../../../lib/llib-lgen.ln
lrwxrwxrwx   1 root     root          20 nov.  8 17:57 llib-lmenu -> ../../lib/llib-lmenu
lrwxrwxrwx   1 root     root          23 nov.  8 17:57 llib-lmenu.ln -> ../../lib/llib-lmenu.ln
lrwxrwxrwx   1 root     root          21 nov.  8 17:57 llib-lpanel -> ../../lib/llib-lpanel
lrwxrwxrwx   1 root     root          24 nov.  8 17:57 llib-lpanel.ln -> ../../lib/llib-lpanel.ln
lrwxrwxrwx   1 root     root          26 nov.  8 17:57 llib-ltermcap -> ../../../lib/llib-ltermcap
lrwxrwxrwx   1 root     root          29 nov.  8 17:57 llib-ltermcap.ln -> ../../../lib/llib-ltermcap.ln
lrwxrwxrwx   1 root     root          25 nov.  8 17:57 llib-ltermlib -> ../../../lib/llib-lcurses
lrwxrwxrwx   1 root     root          28 nov.  8 17:57 llib-ltermlib.ln -> ../../../lib/llib-lcurses.ln
lrwxrwxrwx   1 root     root          19 oct. 20 15:08 svr4.make -> ../../lib/svr4.make
lrwxrwxrwx   1 root     root          21 nov.  8 17:57 values-Xa.o -> ../../lib/values-Xa.o
lrwxrwxrwx   1 root     root          21 nov.  8 17:57 values-Xc.o -> ../../lib/values-Xc.o
lrwxrwxrwx   1 root     root          23 nov.  8 17:57 values-xpg4.o -> ../../lib/values-xpg4.o
lrwxrwxrwx   1 root     root          23 nov.  8 17:57 values-xpg6.o -> ../../lib/values-xpg6.o
lrwxrwxrwx   1 root     root          21 nov.  8 17:57 values-Xs.o -> ../../lib/values-Xs.o
lrwxrwxrwx   1 root     root          21 nov.  8 17:57 values-Xt.o -> ../../lib/values-Xt.o
`

**Comment by ghost** [comment]
just tried symlinking /opt/pkg/gcc47/bin/cpp into /usr/ccs/lib and it seems ok.
a bit of a _kludge_, no?

**Comment by ghost** [comment]
I get a little bit further, but now:

```
/usr/sbin/dtrace -G -C -o dtrace.o -s ../dix/Xserver.d .libs/*.o ../dix/.libs/*.o
cpp: error trying to exec 'cc1': execvp: No such file or directory
dtrace: failed to compile script ../dix/Xserver.d: Preprocessor failed to process input program
gmake[1]: *** [dtrace.o] Error 1
gmake[1]: Leaving directory `/tmp/pkgsrc/x11/modular-xorg-server/work/xorg-server-1.6.5/os'
```

I found cc1 here:

```
richard@devzone:/home/richard$ find /opt -name cc1
/opt/pkg/gcc47/libexec/gcc/x86_64-sun-solaris2.11/4.7.0/cc1
```

in my global zone I find:

```
richard@x3200:~$ find /usr -name cc1                                                                                                                                  
/usr/sfw/libexec/gcc/i386-pc-solaris2.11/3.4.3/cc1
```

what about this one?

**Comment by ghost** [comment]
this one was strange, probably a pkgsrc bmake thing.
If I manually go into the work directory and invoke the same command

```
richard@devzone:/tmp/pkgsrc/x11/modular-xorg-server/work/xorg-server-1.6.5/os$ /usr/sbin/dtrace -G -C -o dtrace.o -s ../dix/Xserver.d .libs/*.o ../dix/.libs/*.o
<command-line>:0:0: warning: "__STDC__" redefined [-Wbuiltin-macro-redefined]
```

I can go on a bit... which I believe means I probably have to do a bmake clean and start over since adding the symlink... arggg.
will see how it goes, and then I'll try a clean rebuild, before reporting back on this on.

**Comment by ghost** [comment]
no, it does have problems with cc1
here is the bmake log 
https://gist.github.com/9ce44b0b5b4e886a056d/dfe1c710bcee630713f7224318d8aecd7ece1e17

BTW, I've noticed that there is perhaps a build problem with cpp in the gcc47 binary downloaded with bootstrap-2012Q3-illumos.tar.gz, not that I'm sure it is the problem here...

```
richard@devzone:/home/richard$ /usr/ccs/lib/cpp -v /dev/null
Using built-in specs.
COLLECT_GCC=/usr/ccs/lib/cpp
Target: x86_64-sun-solaris2.11
Configured with: ../gcc-4.7.0/configure --enable-languages='c obj-c++ objc fortran c++' --enable-shared --enable-long-long --with-local-prefix=/opt/pkg/gcc47 --enable-libssp --enable-threads=posix --with-boot-ldflags='-static-libstdc++ -static-libgcc -Wl,-R/opt/pkg/lib' --disable-nls --enable-__cxa_atexit --with-gxx-include-dir=/opt/pkg/gcc47/include/c++/ --without-gnu-ld --with-ld=/usr/bin/ld --with-gnu-as --with-as=/opt/pkg/gnu/bin/as --prefix=/opt/pkg/gcc47 --build=x86_64-sun-solaris2.11 --host=x86_64-sun-solaris2.11 --infodir=/opt/pkg/gcc47/info --mandir=/opt/pkg/gcc47/man
Thread model: posix
gcc version 4.7.0 (GCC) 
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 /opt/pkg/gcc47/libexec/gcc/x86_64-sun-solaris2.11/4.7.0/cc1 -E -quiet -v /dev/null -mtune=generic -march=x86-64
ignoring nonexistent directory "/opt/pkg/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.0/../../../../x86_64-sun-solaris2.11/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/pkg/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.0/include
 /opt/pkg/gcc47/include
 /opt/pkg/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.0/include-fixed
 /usr/include
End of search list.
# 1 "/dev/null"
# 1 "<command-line>"
# 1 "/dev/null"
COMPILER_PATH=/opt/pkg/gcc47/libexec/gcc/x86_64-sun-solaris2.11/4.7.0/:/opt/pkg/gcc47/libexec/gcc/x86_64-sun-solaris2.11/4.7.0/:/opt/pkg/gcc47/libexec/gcc/x86_64-sun-solaris2.11/:/opt/pkg/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.0/:/opt/pkg/gcc47/lib/gcc/x86_64-sun-solaris2.11/:/usr/ccs/bin/
LIBRARY_PATH=/opt/pkg/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.0/:/opt/pkg/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.0/../../../../x86_64-sun-solaris2.11/lib/amd64/:/opt/pkg/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.0/../../../amd64/:/lib/amd64/:/usr/lib/amd64/:/opt/pkg/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.0/../../../../x86_64-sun-solaris2.11/lib/:/opt/pkg/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.0/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
```

looks like there is a bit of confustion around the include directories ...

**Comment by rmustacc** [comment]
Not having a proper cpp set up for DTrace, nor having /usr/lib/cpp is an OI packaging bug. Making /usr/lib/cpp a symlink to a GCC cpp is not the right answer. If you read filesystem(5), /usr/ccs/lib these days is expected to just be /lib. Furthermore, historically /usr/lib/cpp is a pre-ANSI cpp.

**Comment by ghost** [comment]
well, I reluctantly did a `pkg install cpp` after removing the symlink:

```
richard@devzone:/home/richard/src/pkgsrc/x11/modular-xorg-server$ pkg contents -m cpp
set name=pkg.fmri value=pkg://openindiana.org/developer/macro/cpp@0.5.11,5.11-0.151.1.7:20121003T215552Z
set name=org.opensolaris.consolidation value=sunpro
set name=info.classification value=org.opensolaris.category.2008:Development/C
set name=variant.arch value=i386
set name=variant.opensolaris.zone value=global value=nonglobal
set name=description value="Solaris cpp"
set name=pkg.description value="Solaris cpp"
set name=pkg.summary value="Solaris cpp"
dir group=bin mode=0755 owner=root path=usr/ccs
dir group=bin mode=0755 owner=root path=usr/ccs/bin
dir group=bin mode=0755 owner=root path=usr/ccs/lib
dir group=bin mode=0755 owner=root path=usr/lib
link path=usr/ccs/lib/cpp target=../../lib/cpp
legacy arch=i386 category=system desc="Solaris cpp" hotline="Please contact your local service provider" name="Solaris cpp" pkg=SUNWcpp vendor="Sun Microsystems, Inc." version=5.11,REV=2009.02.13
license 30289f31a30afdb54f35f881c7f65da833b46af6 chash=f41a6e247474f09f908d1260d5e919b0e53abc4a license=SUNWcpp.copyright pkg.csize=4000 pkg.size=9569
file eb2bfe0293b3b23f635bfa6024528f904b68f273 chash=8dd3385cf3b01499dd6edb340976f4a26b0ce55a elfarch=i386 elfbits=32 elfhash=f6580e06326c54d70651b97f121454cbdb60f4a2 group=bin mode=0755 owner=root path=usr/lib/cpp pkg.csize=27677 pkg.size=69140
depend fmri=consolidation/sunpro/sunpro-incorporation type=require
depend fmri=system/library@0.5.11-0.151.1.7 type=require
richard@devzone:/home/richard/src/pkgsrc/x11/modular-xorg-server$ /usr/ccs/lib/cpp -v /dev/null
unknown flag -v
# 1 "/dev/null" 
richard@devzone:/home/richard/src/pkgsrc/x11/modular-xorg-server$ /usr/ccs/lib/cpp -V /dev/null                                                                                                                      
cpp: Software Generation Utilities (SGU) SunOS/SVR4
# 1 "/dev/null" 
```

and a the build using `bmake` was successful.

Not so sure I like adding the "old" cpp.  Is dtrace considered to be always on the core system? Perhaps it would be a possibility to make a pkgsrc package version to ease this type of thing?
(and provide dtrace to systems that don't necessarily have it).

**Comment by ghost** [comment]
On Fri, Nov 09, 2012 at 07:24:34AM -0800, risto3 wrote:

> Not so sure I like adding the "old" cpp.  Is dtrace considered to be always on the core system? Perhaps it would be a possibility to make a pkgsrc package version to ease this type of thing?
> (and provide dtrace to systems that don't necessarily have it).

The K&R cpp is required on any system for development, and realistically
for a lot of other things as well, like dtrace -C and various programs
that rely on it to preprocess their configuration files.  That it is
also needed for dtrace -G to work should not be surprising.  Your
distribution is broken if it makes it easy to install a system without
cpp.  It is also broken if it makes cpp optional without documenting all
the things that will break if it is missing (the attempt to do so should
be sufficiently difficult to rapidly convince the authors that cpp
simply is not optional).  Adding pkgsrc packages for things like dtrace
and cpp that are basic parts of any functional system is not the correct
answer.  That would introduce dependencies from the base system into
pkgsrc; for example, see plockstat(1).  Please do not break pkgsrc to
accommodate insane distributions that deny the existence of dependencies
within the system.

**Comment by ghost** [comment]
Thanks! for the explanation I was looking for regarding dtrace and _this_ cpp needing to be on the core system.  The pkgsrc part was an _otherwise..._ ergo moot.

Why are they not **both** installed by default when creating a zone (this is all in a minimal, exclusive IP ipkg zone), notably during `zoneadm -z <zonename> install`.

I will file a bug.
