### ISSUE TITLE
py-uwsgi: sendfile and event fixes

### ISSUE THREAD

**Issue by oddsignals** [TritonDataCenter/pkgsrc-legacy#220]
uwsgi had some Solaris-specific bugs that have been fixed in the UWSGI master branch. As they impact normal use of uwsgi (pretty severely for some use cases) it would be nice to have them patched in pkgsrc.

Relevant commits are here:
https://github.com/unbit/uwsgi/commit/9780e5fc5e4f0b23ba52b36dfabb7c9cc8609527
https://github.com/unbit/uwsgi/commit/13df278cc4bf82245ba405bafe25a0effb13032b
https://github.com/unbit/uwsgi/commit/8cd13f2ad9018c7c96d0c1265dc5e685757778a0

**Comment by oddsignals** [comment]
I also wrote a service manifest for uwsgi based on the one for nginx, which might be useful to include in the package:
https://gist.github.com/oddsignals/ddeaa0449012193a851f#file-uwsgi-xml

**Comment by wiedi** [comment]
for 2014Q3 py-uwsgi has been updated to 2.0.7, which includes the three fixes.
