### ISSUE TITLE
Installing percona55-cluster-1.1 installs percona-cluster-5.6.x

### ISSUE THREAD

**Issue by cornet** [TritonDataCenter/pkgsrc-legacy#227]
Installing the percona55-cluster-1.1 package ends up installing percona-cluster-5.6.15nb1

I believe the problem might lie with the percona55-cluster-galera-25.3.5 package which has the following dependency: percona-cluster>=5.5.28

<pre>
# cat /opt/local/etc/pkgin/repositories.conf 
http://pkgsrc.joyent.com/packages/SmartOS/2014Q2/x86_64/All

# pkgin install percona55-cluster-1.1
calculating dependencies... done.

nothing to upgrade.
12 packages to be installed: icu-53.1 p5-Data-ShowTable-3.3nb10 p5-DBI-1.631nb1 check-0.9.10 boost-libs-1.55.0nb1 qpress-1.1 quickbackup-percona-3.5nb20140212 percona55-cluster-xtrabackup-2.2.3 percona55-cluster-galera-25.3.5 percona-cluster-5.6.15nb1 p5-DBD-percona55-cluster-4.027nb1 percona55-cluster-1.1 (96M to download, 455M to install)
</pre>

**Comment by cornet** [comment]
So my workaround was to do

```
pkgin install percona-cluster-5.5.34nb1 percona55-cluster-1.1
```

While everything installed correctly it looks like percona-cluster-5.5.34nb1 has been built against galera 23 which isn't in the repo so you end up with the following error when you try and start mysqld

<pre>
41120 16:47:16 [Note] WSREP: wsrep_load(): loading provider library '/opt/local/lib/mysql/plugin/libgalera_smm.so'
141120 16:47:16 [ERROR] WSREP: provider interface version mismatch: need '23', found '25'
141120 16:47:16 [ERROR] WSREP: wsrep_load(): interface version mismatch: my version 23, provider version 25
141120 16:47:16 [ERROR] WSREP: wsrep_load(/opt/local/lib/mysql/plugin/libgalera_smm.so) failed: Invalid argument (22). Reverting to no provider.
141120 16:47:16 [Note] WSREP: Read nil XID from storage engines, skipping position init
141120 16:47:16 [Note] WSREP: wsrep_load(): loading provider library 'none'
141120 16:47:16 [ERROR] Aborting
</pre>

**Comment by mamash** [comment]
I was fixing this earlier in March. Please re-open if you encounter any further issues.
