### ISSUE TITLE
GNU Radio

### ISSUE THREAD

**Issue by fmartinp** [TritonDataCenter/pkgsrc-legacy#228]
GNUradio is not part of the binaries of 2014Q3. How could I install GNURADIO using pkgin?

Thanks.

**Comment by jperkin** [comment]
gnuradio does not currently build on SmartOS, the latest bulk build report is here:

http://us-east.manta.joyent.com/pkgsrc/public/reports/upstream-trunk32/20150324.2241/gnuradio-core-3.7.6/build.log

Patches to make it work are welcome.
