### ISSUE TITLE
apache-cassandra bundles missing snappy native extensions

### ISSUE THREAD

**Issue by MerlinDMC** [TritonDataCenter/pkgsrc-legacy#229]
The Cassandra packages bundle a rather old `snappy-java-1.0.5` that is lacking support for SunOS.

This can be solved by bundling an own build of `snappy-java-1.0.5` with added SunOS native extensions or by bundling a newer `snappy-java-1.1.x` from upstream which includes support for SunOS out of the box.

side note @mamash: `devel/snappy-java10` fails to build cleanly

**Comment by mamash** [comment]
apache-cassandra-2.1.2 in 2014Q3 now depends on snappy-java10 and links in the native snappy-java lib (instead of the one that came with the Cassandra bin tarball). I have yet to commit this change to upstream pkgsrc, but that's the case of Cassandra 2.x either.
