### ISSUE TITLE
golang 1.4 should support cgo

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#230]
golang 1.4 should be integrated into pkgsrc so that cgo can be supported.  Once this is present upstream (or added to the Joyent repo), it will need the changes found at wesolows/golang#master in order to work properly on SmartOS.  While we expect these changes will be integrated into golang upstream prior to 1.5 release, should it be necessary to patch 1.5 as well, those changes may be found in wesolows/golang#dev.cc.

**Comment by mamash** [comment]
pkgsrc trunk was updated to 1.4 earlier today. Upstream freeze for 2014Q4 will start on Sunday, so I'll try to gather your patches and integrate upstream before then.

**Comment by mamash** [comment]
Keith, would you agree that some of the patches might be hostile to non-SunOS platforms? E.g. looking at src/cmd/5l/asm.c here:

https://github.com/wesolows/golang/compare/jnwhiteh:master...master

**Comment by ghost** [comment]
No, they're intended to work on all platforms.  Does that change induce a regression on some foreign system?

The only change in that set that you don't want is the VERSION one (you probably already have an analogue to it since it's needed to build without Mercurial).

**Comment by jperkin** [comment]
cgo-enabled packages are available as of 2014Q4/14.4.x
