### ISSUE TITLE
Incorrect /etc/logadm.conf entry for py27-denyhosts package

### ISSUE THREAD

**Issue by chorrell** [TritonDataCenter/pkgsrc-legacy#231]
When installing the  py27-denyhosts package the following logadm.conf entry is created

```
/var/log/denyhosts.log -C 5 -c -s 50m -z 1
```

Tha's actually incorrect as the default name for the denyhosts log is `/var/log/denyhosts` (no *.log extension).

**Comment by mamash** [comment]
I fixed this and rebuilt the 2014Q3 packages last night.

**Comment by chorrell** [comment]
Great, thanks!
