### ISSUE TITLE
Quagga daemons don't run

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc-legacy#234]
When running any of the quagga daemons an error similar to the following is returned:

```
vty_read_config: failed to open configuration file /opt/local/etc/zebra/zebra.conf: Permission denied
can't open configuration file [/opt/local/etc/zebra/zebra.conf]
```

Modifying the permissions of the config file or any/all directories in the path to the config file makes no difference.

**Comment by bahamat** [comment]
The following patch clears it up. I'll be submitting a pull request momentarily.

```
diff --git a/net/quagga/Makefile b/net/quagga/Makefile
index 3ce636b..caad5c1 100644
--- a/net/quagga/Makefile
+++ b/net/quagga/Makefile
@@ -2,7 +2,7 @@
 #

 DISTNAME=      quagga-0.99.22.3
-PKGREVISION=   1
+PKGREVISION=   2
 CATEGORIES=    net
 MASTER_SITES=  http://download.savannah.gnu.org/releases/quagga/

@@ -22,6 +22,7 @@ CONFIGURE_ARGS+=      --sysconfdir=${PKG_SYSCONFDIR:Q}
 CONFIGURE_ARGS+=       --enable-exampledir=${PREFIX}/share/examples/quagga
 #CONFIGURE_ARGS+=      --enable-pkgsrcrcdir=${PREFIX}/${RCD_SCRIPTS_EXAMPLEDIR}
 CONFIGURE_ARGS+=       --localstatedir=${VARBASE}/run/zebra
+CONFIGURE_ARGS+=       --disable-capabilities

 CONFLICTS+=            zebra-[0-9]*

```

**Comment by mamash** [comment]
Hi bahamat,

I've had a Joyent internal ticket for quagga for some time, just didn't get to it yet. I was planning to apply the patch from upstream Illumos:

https://github.com/illumos/illumos-userland/blob/master/components/quagga/patches/75-privs-basicprivset.patch

However, I just tested building quagga from pkgsrc trunk (the package was updated to 0.99.23.1 in December) and it seems to run just fine with no changes or patching whatsoever. E.g. I can start zebra or ospfd and use vtysh to connect to it, I didn't go much further.

I couldn't find anything relevant in the changelog, but I can't reproduce the problem. Could you test net/quagga as it shows in either trunk or pkgsrc_2014Q4 _without_ your changes?

https://github.com/joyent/pkgsrc/tree/joyent/release/2014Q4/net/quagga

The problem that remains is that the package assumes /var/run/quagga for PID files, which is a poor choice on SunOS where /var/run goes away between reboots, so I need to fix that in our package.

**Comment by bahamat** [comment]
Building from the joyent/release/2014Q4 branch I still get permission errors reading the config.

**Comment by mamash** [comment]
Thanks. I tried again today and I can't reproduce what I saw with my eyes yesterday! In other words, breaking for me too. Mind boggling...

I'd rather patch the capabilities than disable though - would you mind testing with the patch I linked above? I can test launching the daemons, but you'll likely be more capable of checking if they work.

**Comment by bahamat** [comment]
Yeah, that patch worked for me.

I dropped it in as `patches/patch-lib-privs.c` and set `PKGREVISION=2` in the `Makefile` and made sure not to include `--disable-capabilities`.

After installing I don't get the permission errors anymore and I was able to establish full peering with OSPF to my router and successfully exchange routes.

So that patch looks good to me.

**Comment by mamash** [comment]
Thanks for confirming, Brian. I'll integrate in upstream CVS and cherry-pick into at least 2014Q3 for a fixed package.

**Comment by mamash** [comment]
I'd like to integrate the supplied SMF manifest and methods too, will bundle the update together.

**Comment by mamash** [comment]
quagga-0.99.23.1nb1 in 2014Q3 has the fix (and SMF) now.
