### ISSUE TITLE
tmux does not allow 'open' on OSX.

### ISSUE THREAD

**Issue by ccrusius** [TritonDataCenter/pkgsrc-legacy#246]
You can't 'open' from tmux. If you try, say, 'open file.pdf', you'll get 'The window server could not be contacted.'

Strictly speaking this is an issue with tmux, as seen in https://trac.macports.org/ticket/18357, that has been open for 6 years. It can be fixed by a change in compile flags, see https://trac.macports.org/changeset/127986.

**Comment by bahamat** [comment]
What version of OS X? It works for me on Yosemite (10.10.2).

**Comment by ccrusius** [comment]
10.10.2 here too. Works outside tmux, fails inside it.

**Comment by jperkin** [comment]
Thanks for the report!  This is fixed upstream in http://mail-index.netbsd.org/pkgsrc-changes/2015/06/23/msg126276.html and will be a part of the 2015Q2 release.
