### ISSUE TITLE
build chat/weechat with perl support

### ISSUE THREAD

**Issue by bahamas10** [TritonDataCenter/pkgsrc-legacy#252]
context: https://twitter.com/bahamas10_/status/582603364384509952
work around: http://daveeddy.com/2015/03/30/weechat-perl-plugin-on-smartos/

basically, most plugins written for weechat are in perl (though I believe that is changing) and weechat by default compiles with perl enabled.  From the comments of my blog post

> The weechat port has an option for perl, so assuming you've got a ports tree downloaded, install chat/weechat with "sudo bmake PKG_OPTIONS="charset gnutls perl" install clean"
> - yourimouton (disqus)

**Comment by jperkin** [comment]
Ok, 2015Q1 will come with the full set of options enabled:

```
PKG_OPTIONS.weechat+= lua perl python ruby wide-curses
```

Hopefully that will cater for all tastes :)

**Comment by bahamas10** [comment]
I don't know how it took me this long to see your reply, but :+1: awesome!
