### ISSUE TITLE
ImportError when importing select module with python27-2.7.9 in 2014Q4/x86_64

### ISSUE THREAD

**Issue by gkoh** [TritonDataCenter/pkgsrc-legacy#253]
Just upgraded an OmniOS zone from 2014Q2/x86_64 to 2014Q4/x86_64.
The updated python27 is failing to import the select module needed by a number of applications.

Reproduced like this:

```
$ python2.7
Python 2.7.9 (default, Mar 19 2015, 15:32:58) 
[GCC 4.7.3] on sunos5
Type "help", "copyright", "credits" or "license" for more information.
>>> import select
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: ld.so.1: python2.7: fatal: relocation error: file /opt/local/lib/python2.7/lib-dynload/select.so: symbol epoll_create: referenced symbol not found
>>> 
```

**Comment by gkoh** [comment]
I have currently worked around this by copying select.so from the python27-2.7.7.nb2 package over the installed library.

**Comment by mamash** [comment]
For 2014Q4 SmartOS packages, we started using a more modern platform (joyent_20141030T081701Z) that has several new features, so 2014Q4 is not guaranteed to work on older ones. The 2014Q3 SmartOS package set is likely the last your system will support.

**Comment by jperkin** [comment]
I'll take a look at disabling epoll for this, we will try to retain compatibility where possible.

**Comment by gkoh** [comment]
On Tue, 2015-03-31 at 00:43 -0700, Filip Hajny wrote:

> For 2014Q4 SmartOS packages, we started using a more modern platform
> (joyent_20141030T081701Z) that has several new features, so 2014Q4 is
> not guaranteed to work on older ones. The 2014Q3 SmartOS package set
> is likely the last your system will support.

I see.
I'm running OmniOS r151012 for reference.
I assume these modern features will eventually make their way to other
Illumos based distributions.

**Comment by gkoh** [comment]
On Tue, 2015-03-31 at 01:26 -0700, Jonathan Perkin wrote:

> I'll take a look at disabling epoll for this, we will try to retain
> compatibility where possible.

That would greatly appreciated, thanks!
Part of the appeal of updating to 2014Q4 is the LTS-like support.

**Comment by gkoh** [comment]
This appears to be fixed in 2015Q1, not sure if there is any intent to backport to 2014Q4?
I'm happy to close if not.

**Comment by jperkin** [comment]
Yes, for 2015Q1 I disabled some of the newer features to ensure better binary compatibility. We can't backport this to 2014Q4 without rebuilding pretty much every package, and we aren't willing to do that for an LTS release.
