### ISSUE TITLE
more features for exim, znc & proftpd

### ISSUE THREAD

**Issue by wiedi** [TritonDataCenter/pkgsrc-legacy#254]
Currently we have to compile a few packages ourselves to enable non-default PKG_OPTIONS.
If the SmartOS builds could already include these that would be helpful:

```
PKG_OPTIONS.exim+= spf exim-lookup-sqlite exim-lookup-redis
PKG_OPTIONS.znc+= sasl
PKG_OPTIONS.proftpd+= mysql tls
```

**Comment by jperkin** [comment]
Done, these will be enabled in 2015Q1, thanks!

**Comment by mamash** [comment]
It should be possible to split proftpd into separate packages (e.g. proftpd-mysql), at least such exists in Ubuntu. Otherwise we lock the user to a specific MySQL flavor/version once proftpd is installed.

**Comment by jperkin** [comment]
I opened joyent/pkgsrc#257 for that, and yeh we should do that for others we've enabled where possible.
