### ISSUE TITLE
Homepage starting instructions for new users omits database creation

### ISSUE THREAD

**Issue by gilesburdett** [TritonDataCenter/pkgsrc-legacy#259]
The current advice to get a new user started on OS X (http://pkgsrc.joyent.com/install-on-osx/) leaves the system without a database and the following error message:

pkgin: Can't open database /var/db/pkgin/pkgin.db: unable to open database file: No such file or directory

Before the user can successfully pkgin avail, they have to run pkgin update as root to build the missing database, so the instructions on the homepage would be better as:

```
: Download, check, and install bootstrap kit to /usr/pkg.
$ curl -Os http://pkgsrc.joyent.com/packages/Darwin/bootstrap/bootstrap-2014Q4-x86_64.tar.gz
$ shasum bootstrap-2014Q4-x86_64.tar.gz
1ba17cc922304aa4508d1cb8765e936af5a9f5ff   bootstrap-2014Q4-x86_64.tar.gz
$ sudo tar -zxpf bootstrap-2014Q4-x86_64.tar.gz -C /

: Add paths
$ PATH=/usr/pkg/sbin:/usr/pkg/bin:$PATH
$ MANPATH=/usr/pkg/man:$MANPATH

>>
: Create a local database of available packages.
$ sudo pkgin update
==
<<

: Number of packages available
$ pkgin avail | wc -l
   11487
```

**Comment by jperkin** [comment]
This was fixed a while back, thanks for the report!
