### ISSUE TITLE
python 2.6 in 2015Q1 on OSX looking for hardcoded directory

### ISSUE THREAD

**Issue by anadrome** [TritonDataCenter/pkgsrc-legacy#262]
Attempting an upgrade after installing the 2014Q4 bootstrap (was previously on 2014Q3), on OSX 10.10, I get a number of missing dylib warnings similar to this one, referencing what seems to be a hardcoded path from the build machine:

/Users/pbulk/build-2014Q4/geography/qlandkartegt-garmindev/work/garmindev-0.3.4/qlandkartegt/libwhatGarmin.dylib, needed by python26-2.6.9nb4 is not present in this system.

**Comment by jperkin** [comment]
Hm interesting, thanks.  There are pkgsrc checks which should warn about things like this, I'll ensure they are enabled in future builds (and work correctly with the OS X toolchain).

**Comment by anadrome** [comment]
Oops, sorry, I misreported the version. I actually see this in 2015Q1, which I seem to have accidentally grabbed, meaning to grab 2014Q4. I'm also seeing other weird things in 2015Q1, e.g. running upgrade on a completely fresh install wants to install 1634 new packages (mostly py26-_, py27-_, and p5-\* stuff, but also e.g. ImageMagick). I blew it away and went back to 2014Q4, and everything works fine there.

**Comment by jperkin** [comment]
Yeh, upgrades across branches can be messy, a number of people have reported the large number of packages that pkgin wants to upgrade thing on SmartOS too - maybe @iMilnb has some ideas there?  Again that's something we definitely want to fix.
