### ISSUE TITLE
2015Q1: libc.so.1 (ILLUMOS_0.6) => (version not found)

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#263]
Hi,

running OI151a9:
$ pkg publisher -H openindiana.org

```
        Publisher: openindiana.org
            Alias:
       Origin URI: http://pkg.openindiana.org/dev/
          SSL Key: None
         SSL Cert: None
      Client UUID: c58034a4-2c82-11e0-b822-801111c37813
  Catalog Updated: Wed Dec 10 16:08:49 2014
          Enabled: Yes
 Signature Policy: verify
```

With Illumos version:
$ grep -E "OpenIndiana Build.*illumos" /var/adm/messages.0 | tail -1
Apr 24 19:01:04 ze genunix: [ID 958253 kern.notice] ^MOpenIndiana Build oi_151a9 64-bit (illumos 52e13e00ba)

Installed according to guide: http://pkgsrc.joyent.com/install-on-illumos/

Yet, trying to do anything:
$ /opt/local/bin/pkgin avail
ld.so.1: pkgin: fatal: libc.so.1: version 'ILLUMOS_0.6' not found (required by file /opt/local/bin/pkgin)
ld.so.1: pkgin: fatal: libc.so.1: open failed: No such file or directory
Killed

$ ldd /opt/local/bin/pkgin
        libcrypto.so.1.0.0 =>    /opt/local/lib/libcrypto.so.1.0.0
        libssl.so.1.0.0 =>       /opt/local/lib/libssl.so.1.0.0
        libbz2.so.0 =>   /opt/local/lib/libbz2.so.0
        libz.so.1 =>     /opt/local/lib/libz.so.1
        libarchive.so.13 =>      /opt/local/lib/libarchive.so.13
        libtermcap.so.1 =>       /lib/libtermcap.so.1
        libnsl.so.1 =>   /lib/libnsl.so.1
        libsocket.so.1 =>        /lib/libsocket.so.1
        libsqlite3.so.0 =>       /opt/local/lib/libsqlite3.so.0
        libumem.so.1 =>  /lib/libumem.so.1
        libc.so.1 =>     /lib/libc.so.1
        libc.so.1 (ILLUMOS_0.6) =>       (version not found)
        libdl.so.1 =>    /lib/libdl.so.1
        libgcc_s.so.1 =>         /opt/local/gcc47/i486-sun-solaris2.11/lib/./libgcc_s.so.1
        libiconv.so.2 =>         /opt/local/lib/libiconv.so.2
        liblzma.so.5 =>  /opt/local/lib/liblzma.so.5
        libmd.so.1 =>    /lib/libmd.so.1
        libpthread.so.1 =>       /lib/libpthread.so.1
        librt.so.1 =>    /lib/librt.so.1
        libc.so.1 (ILLUMOS_0.8) =>       (version not found)
        libmp.so.2 =>    /lib/libmp.so.2
        libc.so.1 (ILLUMOS_0.8) =>       (version not found)
        libcurses.so.1 =>        /lib/libcurses.so.1
        libm.so.2 =>     /lib/libm.so.2

Is it possible to fix this problem somehow?
Thank you and best regards.

Predrag Zečević

**Comment by jperkin** [comment]
While we try to make our binaries as portable as possible, we do require a reasonably up-to-date illumos.  `ILLUMOS_0.6` was introduced over 1.5 years ago with the introduction of `getloginx` which should be plenty of time for it to reach your distribution of choice. Make sure you are running the latest version available.

**Comment by jperkin** [comment]
I should have mentioned, if you want to use packages on old distributions then you should be able to use any of the sets from 2014Q3 or earlier, which were all built on a very old version of SmartOS and will be more portable across legacy installs.  2014Q4 and onwards were moved to newer releases to make use of recent illumos features.

**Comment by jperkin** [comment]
FWIW I've now added a note to this effect at the top of http://pkgsrc.joyent.com/install-on-illumos/

**Comment by ghost** [comment]
Hi Jonathan,

thank you for fast update!

With best regards.
Predrag Zečević

Am Mon, 27 Apr 2015 05:52:39 -0700
 schrieb Jonathan Perkin notifications@github.com:

**Comment by zssfred** [comment]
> FWIW I've now added a note to this effect at the top of http://pkgsrc.joyent.com/install-

> FWIW I've now added a note to this effect at the top of http://pkgsrc.joyent.com/install-on-illumos/

is https://pkgsrc.joyent.com/packages/SmartOS/2019Q3/tools/All still accessible?

Thanks.

Fred

**Comment by jperkin** [comment]
Yes but only by accident, that branch was EOL over 2 years ago.

**Comment by zssfred** [comment]
> Yes but only by accident, that branch was EOL over 2 years ago.

Is there an easy way to mirror the legacy pkgsrc repo from Joyent like yum? It seems the stepping of illumos libc is not so slow. For smartos always points to the latest repo release, is it possible to check the API compatibility before "pkgin in"?
Is there a precise and clear map about illumos libc evolving?

Thanks.

Fred

**Comment by jperkin** [comment]
All of the EOL releases are available from Manta (us-east.manta.joyent.com), and you could use something like <https://www.npmjs.com/package/manta-sync> to grab them.  The path is `/pkgsrc/public/packages/SmartOS/`

As for compatibility, I've only changed the build requirement a couple of times over the years so it's easy enough to know whether a platform is compatible with the pkgsrc release.  It's also probably worth stating that even the newest requirements for trunk and 2021Q4 are 20210826, and you would want to be running at least that platform anyway due to the number of vulnerabilities present in older releases.

That said, the platform requirements are:

* 20141030 for releases up to and including 2019Q3
* 20161222 for 2019Q4 up to and including 2020Q4
* 20210826 for 2021Q4 and trunk

**Comment by zssfred** [comment]
> 



> All of the EOL releases are available from Manta (us-east.manta.joyent.com), and you could use something like https://www.npmjs.com/package/manta-sync to grab them. The path is `/pkgsrc/public/packages/SmartOS/`

It seems that to access Manta we need a Joyent account, right?

> 
> As for compatibility, I've only changed the build requirement a couple of times over the years so it's easy enough to know whether a platform is compatible with the pkgsrc release. It's also probably worth stating that even the newest requirements for trunk and 2021Q4 are 20210826, and you would want to be running at least that platform anyway due to the number of vulnerabilities present in older releases.
> 
> That said, the platform requirements are:
> 
> * 20141030 for releases up to and including 2019Q3
> * 20161222 for 2019Q4 up to and including 2020Q4
> * 20210826 for 2021Q4 and trunk

Super! It would be better that we can get these clear hints when we want to query.

Thanks.

Fred
