### ISSUE TITLE
ansible 1.6.10 expects python in /usr/bin instead of /opt/local/bin

### ISSUE THREAD

**Issue by marcovl71** [TritonDataCenter/pkgsrc-legacy#268]
Ansible 1.6.10 from base-64 15.1.1 (0edf00aa-0562-11e5-b92f-879647d45790) with default settings looks for python 2 interpreter in /usr/bin instead of /opt/local/bin.

This is fine if the target host one tries to manage is not SmartOS (like some Linux distros).
But if the intent is to run ansible from within a SmartOS VM (zone) and to manage target zones then it would make more sense for ansible to look for python in /opt/local/bin

Currently this means that one has to append ansible_python_interpreter=/opt/local/bin/python to each target host which is a SmartOS VM (zone).

[root@ansible /opt/local/etc/ansible]# head -1 hosts
192.168.3.216

[root@ansible /opt/local/etc/ansible]# ansible -m ping 192.168.3.216
192.168.3.216 | FAILED >> {
    "failed": true, 
    "msg": "/bin/sh[1]: /usr/bin/python: not found [No such file or directory]\r\n", 
    "parsed": false
}

[root@ansible /opt/local/etc/ansible]# head -1 hosts
192.168.3.216 ansible_python_interpreter=/opt/local/bin/python

[root@ansible /opt/local/etc/ansible]# ansible -m ping 192.168.3.216
192.168.3.216 | success >> {
    "changed": false, 
    "ping": "pong"
}

**Comment by mamash** [comment]
I have never used Ansible, is there a concept of "this OS has X at Y" at all? Or does it simply assume that all the OS of the world will have /usr/bin/python?

**Comment by drscream** [comment]
There is (or well was) a discussion on https://github.com/ansible/ansible/issues/6345 also some documentation on http://docs.ansible.com/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine

**Comment by jperkin** [comment]
Having thought about this for a while and having started using ansible recently on SmartOS, I'm going to close this as WontFix. Whilst changing it to `/opt/local/bin/python` would make it work out of the box on SmartOS, the ansible documentation and common expectation is that `/usr/bin/python` is the default and it seems reasonably common that users will be used to setting `ansible_python_interpreter` appropriately for targets which do not have `/usr/bin/python`.  You would have to do this anyway if executing your playbooks from a non-SmartOS host.

There is no concept of per-OS defaults at present in the ansible code itself, so this would have to be a global change, forcing you to instead set `ansible_python_interpreter` for all target hosts which do not have `/opt/local/bin/python`, making inventories unnecessarily different depending on the machine you are executing from, and breaking the principle of least astonishment for users comfortable with ansible who switch to running their existing playbooks on a SmartOS host.

The ansible inventory format makes this a single line change for all SmartOS hosts if you correctly group them, so it's pretty simple to handle this, i.e.:

``` ini
[smartos_hosts]
192.168.3.216
192.168.3.217
192.168.3.218
192.168.3.219

[smartos_hosts:vars]
ansible_python_interpreter=/opt/local/bin/python
```

Thanks.
