### ISSUE TITLE
update puppet to 3.8.1

### ISSUE THREAD

**Issue by igalic** [TritonDataCenter/pkgsrc-legacy#275]
Puppet and its dependencies (Hiera, Facter) are lagging behind about half a year.
Ignoring the very incompatible Puppet 4.x for a moment, it would be nice to get an update of Puppet to at least 3.8.1.

**Comment by igalic** [comment]
my recommendation is to use Ruby 2.1 with this release.

**Comment by mamash** [comment]
I pushed an update to 3.8.2 to upstream pkgsrc just now, it will show up in the 2015Q3 release. Both facter and hiera are fairly recent there already.

**Comment by igalic** [comment]
@mamash thank you so much!
any idea when puppet 4.x will be able to land?
(i just tried to find builds from @puppetlabs for any platform that's not linux, and… it seems not to exist… not even pe):

**Comment by mamash** [comment]
I'm sorry, I have yet to investigate 4.x. We could go with sysutils/puppet3 and sysutils/puppet if we need to keep both out there.
