### ISSUE TITLE
Add Apache Traffic Server

### ISSUE THREAD

**Issue by igalic** [TritonDataCenter/pkgsrc-legacy#276]
from their [website](https://trafficserver.apache.org)

> Apache Traffic Server™ software is a fast, scalable and extensible HTTP/1.1 compliant caching proxy server.

Also an SSL Terminator, and HTTP/2 Proxy, and, and and…

I'd really love to see this in the repository!

**Comment by mamash** [comment]
I added trafficserver to the pkgsrc-joyent repo for now, because it doesn't build on NetBSD and I do not have time to figure out why. It's available in the 2014Q4 LTS package repository now.

https://github.com/joyent/pkgsrc-joyent/tree/master/trafficserver
