### ISSUE TITLE
pkgsrc not updating

### ISSUE THREAD

**Issue by saysjonathan** [TritonDataCenter/pkgsrc-legacy#287]
It appears that this repo is no longer automatically updating an commits are now 8 days behind CVS. I assume this is related to [jsonn/pkgsrc](https://github.com/jsonn/pkgsrc) not updating. I've contacted [jsonn](https://github.com/jsonn) but have not yet received a response.

Is there anything you can do to fix this?

**Comment by jperkin** [comment]
Yes, unfortunately we rely on Joerg's repository conversion as our upstream, and it appears he is on vacation.  I'd love to set up our own conversion but it's a complicated process to do correctly (going via fossil as an intermediatory).  I'll ask Joerg about getting a copy of his current setup when he returns.

Sorry about that.

**Comment by saysjonathan** [comment]
Thanks for the verification. I'll keep working from my CVS checkout for now.

Did Joerg ever document why fossil was actually required as an intermediary? I know he was trying to get a bit-exact import but I never saw the reason for using cvs2fossil instead of git-cvsimport.

**Comment by jperkin** [comment]
I believe it's the only way to get an accurate conversion, but I'll leave it to Joerg to confirm when he returns.
