### ISSUE TITLE
Clang 3.6.1 doesn't work out of the box as of 2015Q2 release

### ISSUE THREAD

**Issue by affixalex** [TritonDataCenter/pkgsrc-legacy#288]
Hi,

I'm using Joyent pkgsrc 2015Q2 on OmniOS r151014 to create environments with vagrant.

Clang depends upon the gcc48 package (as opposed to just gcc48-libs), and it searches for crtbegin.o, crtend.o, and libgcc.a in the wrong locations, which necessitates symlinks (or rpath hacks) to get a working clang executable.

```
  config.vm.provision "shell", inline: <<-SHELL
    pkg install -v system/header \
      developer/versioning/git \
      developer/library/lint \
      developer/build/gnu-make

    curl -s http://pkgsrc.joyent.com/packages/SmartOS/bootstrap/bootstrap-2015Q2-x86_64.tar.gz | gzcat | (cd /; tar -xpf -)

    echo "export PATH=/usr/gnu/bin:/opt/local/bin:/opt/local/sbin:$PATH" >> ~vagrant/.profile

    #/opt/local/bin/pkgin -yV up
    /opt/local/bin/pkgin -yV install gcc48
    /opt/local/bin/pkgin -yV install clang

    mkdir /opt/local/gcc48/lib/gcc/x86_64-sun-solaris2.11/4.8.4/amd64
    cd /opt/local/gcc48/lib/gcc/x86_64-sun-solaris2.11/4.8.4/amd64
    ln -s ../libgcc.a .
    ln -s ../crtbegin.o .
    ln -s ../crtend.o .
  SHELL
```

.

**Comment by bahamat** [comment]
In 2014Q3 I had to also append the linker path.

```
# ln -s . /opt/local/gcc48/lib/gcc/x86_64-sun-solaris2.11/4.8.4/amd64
# export LDFLAGS=-L/opt/local/gcc48/lib/amd64
# clang $LDFLAGS -o hello hello.c
# ./hello
Hello World
```

**Comment by chrisridd** [comment]
Comparing the gcc47/48/49 packages, it looks like the crt*.o files moved into the compiler packages in gcc48 and gcc49, so the compiler packages should be a runtime dependency of clang. (I'd prefer if the crt*.o files were in the later gcc lib packages too, but that might be fighting against the flow somewhat.)

It looks like Makefile.common has some hacks to fix some embedded absolute paths, but those hacks mention gcc 4.5, and clearly needs updating to remove obsolete gcc versions and to add supported gcc versions. This is the major bug.

I can't even build lang/clang from a clean checkout of pkgsrc, so it is difficult to work on a patch.

This is all broken upstream as well.

How did lang/clang pass any tests?!

**Comment by jperkin** [comment]
This will be fixed in 2015Q4, I spent some time on this a while ago and it is now possible to build a reasonably large set of packages using clang.

**Comment by chrisridd** [comment]
Great, thanks!

Which branch has the fix?

**Comment by jperkin** [comment]
None yet, the fix is here https://github.com/joyent/pkgsrc/commit/229401288630442931cb5a19b7138e3c40bd74ab

**Comment by jperkin** [comment]
This was released in 2015Q4.
