### ISSUE TITLE
Ansible & Sun_SSH

### ISSUE THREAD

**Issue by travispaul** [TritonDataCenter/pkgsrc-legacy#289]
Would you be interested in this patch: https://github.com/ansible/ansible/pull/12093 it will look a bit different for the version of ansible in pkgsrc, but I just wanted to check before I put any effort into it :)

All it does is allow anisble to work more easily "out-of-the-box", but it can be worked around in ansible.cfg

**Comment by travispaul** [comment]
This has been merged upstream (in the devel branch): https://github.com/ansible/ansible/pull/12107#issuecomment-135793520

**Comment by mamash** [comment]
This appeared in 2.1.0.0, which has been available in the 2016Q2 release.
