### ISSUE TITLE
mpg321 dumps core due to uninitialised variable

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#29]
This problem is properly a bug in the original mpg321 rather than pkgsrc, but there is no bug tracking system for mpg321 so I will file it here in addition to sending the author a note.

This is triggered by building with libumem.  We reliably see:

Loading modules: [ libumem.so.1 libc.so.1 ld.so.1 ]

> $C
> 08047128 libc.so.1`_lwp_kill+0x15(1, 6, 8047158, feaf4349, feb11000, feafee13)
> 08047148 libc.so.1`raise+0x2b(6, feafee13, 8047168, feaf4375)
> 08047168 libumem.so.1`umem_do_abort+0x2b(feb11000, feffb0a4, 80471b8, feaf68ca, 
> feafee13, feaff095)
> 08047178 libumem.so.1`umem_err_recoverable+0x5a(feafee13, feaff095, feffb0a4, 
> feaff053, 0, 1)
> 080471b8 libumem.so.1`process_free+0xc2(0, 0, 80742e0, 8047714)
> 080471d8 libumem.so.1`free+0x1c(feffb0a4, 805f2e8, 8047284, 810cfd8, ffffffff, 0
> )
> 08047b58 main+0x7c1(4, 8047b84, 8047b98, 8047b78, 80545f2, 805c1a0)
> 08047b78 _start+0x83(4, 8047c64, 8047c6b, 8047c6e, 8047c7a, 0)

When the process is cleaning up and about to exit.  The problem is simple; it's checking pointers in an uninitialised structure against NULL and then freeing them (which is both redundant and broken).  The fix is trivial:

--- mpg321-0.3.2-orig/mpg321.c  2012-03-25 12:27:49.000000000 +0000
+++ mpg321-0.3.2-fixed/mpg321.c 2012-12-11 00:35:49.800885209 +0000
@@ -522,6 +522,8 @@
     int frames_id;
     mad_decoder_position = 0;
     output_buffer_position = 0;
+
- ```
    bzero(&playbuf, sizeof (playbuf));
  ```
  
   old_dir[0] = '\0';

**Comment by jperkin** [comment]
Updated mpg321 to 0.3.2 in pkgsrc trunk and incorporated this patch.
