### ISSUE TITLE
Not updating again

### ISSUE THREAD

**Issue by saysjonathan** [TritonDataCenter/pkgsrc-legacy#291]
It appears that this repo is again no longer automatically updating an commits are now 3 days behind jsonn/pkgsrc & CVS.

**Comment by mamash** [comment]
This repo is only synced manually. Look at the upstream mirror (jsonn/pkgsrc) if you want the latest always (updated automatically based on the upstream CVS every couple of hours).

**Comment by saysjonathan** [comment]
I'll be switching over.

This should really be noted somewhere however. According to the repo description it's automatically updated. I understand this was a fork of jsonn/pkgsrc but you could at least update the description to be more truthful. Updating [pkgsrc.joyent.com](https://pkgsrc.joyent.com/docs/building/) with the correct repo for urgent updates would be nice as well.
