### ISSUE TITLE
nginx missing on Darwin

### ISSUE THREAD

**Issue by rzezeski** [TritonDataCenter/pkgsrc-legacy#296]
I notice nginx is missing from Darwin 2015Q2 and 2015Q3. Was this intentional?

**Comment by jperkin** [comment]
Looks like the PLIST expects .so, probably needs handling .dylib for OSX:

http://us-east.manta.joyent.com/pkgsrc/public/reports/Darwin/2015Q3/i386/20151002.1029/nginx-1.8.0/install.log

I can look at fixing this for 2015Q3.

**Comment by rzezeski** [comment]
Thanks for looking into it. FWIW, I'm using 2015Q3. I just thought I'd mention it was missing from Q2 as well.

**Comment by jperkin** [comment]
This is now available for 64-bit 2015Q3, 32-bit should follow in the next few hours.
