### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by chasset** [TritonDataCenter/pkgsrc-legacy#297]
During the install process, the 4th step - `sudo tar -zxpf bootstrap-2015Q3-i386.tar.gz -C /` - issues the following error :
`./var/db/pkgin/cache/: Cannot extract through symlink var`
`tar: Error exit delayed from previous errors.`

**Comment by rmustacc** [comment]
Can you include information about what platform you're installing on are?

**Comment by chasset** [comment]
Mac OS X 10.11.1

**Comment by chorrell** [comment]
I get the same issue on Mac OS X 10.11.1 as well:

```
[christopher@MacBook ~/Downloads]$ sudo tar -zxpf bootstrap-2015Q3-x86_64.tar.gz -C /
./var/db/pkgin/cache/: Cannot extract through symlink var
tar: Error exit delayed from previous errors.
```

Following these instructions: https://pkgsrc.joyent.com/install-on-osx/

**Comment by chorrell** [comment]
Also:

```
[christopher@MacBook ~/Downloads]$ ls -AlFh / |grep var
lrwxr-xr-x@   1 root         wheel    11B 23 Oct 19:35 var@ -> private/var
```

Did that change from a previous OS X release?

**Comment by rmustacc** [comment]
No, it hasn't at least compared to my instance of 10.8. I wonder if there's an issue with the whole image protection here and trying to traverse it for some reason.

**Comment by chorrell** [comment]
fwiw, this doesn't happen with 2015Q2:

```
[christopher@MacBook ~/Downloads]$ sudo tar -zxpf bootstrap-2015Q2-x86_64.tar.gz -C /
Password:
```

```
christopher@MacBook ~/Downloads]$ ls -AlFh /var/db/pkgin/
total 21792
drwxr-xr-x  2 root  wheel    68B 24 Oct 11:32 cache/
-rw-r--r--  1 root  wheel    11M 24 Oct 11:33 pkgin.db
-rw-r--r--  1 root  wheel   466B 24 Oct 11:33 sql.log
```

**Comment by chorrell** [comment]
So the bootstrap-2015Q2-x86_64.tar.gz tarball doesn't include `/var/db/pkgin/cache/`

Is including that directory path in the 2015Q3 tarball necessary?

**Comment by chorrell** [comment]
As a workaround, this seems to work:

```
sudo tar -zxpf bootstrap-2015Q3-x86_64.tar.gz --exclude=var -C /
```

**Comment by jperkin** [comment]
I included it in the bootstrap as it prevents errors when running pkgin without an initial database, and also helps on other platforms which do not include `/var/db` by default (notably OmniOS).

If I can't find a reasonable workaround then I'll just have to remove it from the OSX bootstraps.  El Capitan is proving to be a real pain.

**Comment by bahamat** [comment]
I think the path should be `/private/var/db/pkgin/cache`.

**Comment by jperkin** [comment]
I've fixed this in the trunk bootstrap (< https://pkgsrc.joyent.com/packages/Darwin/bootstrap/bootstrap-trunk-x86_64.tar.gz>) and it will be included in release branches from now on too.  Thanks!
