### ISSUE TITLE
List of available packages

### ISSUE THREAD

**Issue by chasset** [TritonDataCenter/pkgsrc-legacy#298]
Hello,

I install pkgsrc 64bits on a Mac OS X 10.11.1 with XQuartz 2.7.7
I would like to install some software like kate or krusader which are in the [following list](http://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/README-all.html). But I am not able to find them using `pkgin search "kate"`.
Have I done something wrong?
Best regards,

Pierre-Olivier

**Comment by rmustacc** [comment]
Hi, not all packages in pkgsrc are available for every platform. There may be build failures or other issues or they may not have been ported to the platform in question. In this case, it's likely that kate or one of its dependent packages from KDE is not currently building correctly. @jperkin might have more information as to why.

**Comment by chasset** [comment]
So, do you have an up to date list of packages for MacOSX?

**Comment by rmustacc** [comment]
You can run `pkgin av` to obtain the list of available packages.

**Comment by chasset** [comment]
thanks
