### ISSUE TITLE
pkgsrc installation on El Capitan

### ISSUE THREAD

**Issue by tlcarpenter** [TritonDataCenter/pkgsrc-legacy#303]
Is installation of pkgrc bootstrap 2015Q3 x86_64 supported on El Capitan? I'm new to using pkgsrc and tried to cook-book my way through the 64-bit Mavericks steps

http://pkgsrc.joyent.com/install-on-osx/

on my El Capitan 10.11.1 system but get the following error

"./var/db/pkgin/cache/: Cannot extract through symlink var"

Haven't looked into this but wonder if this error may be a result of El Capitan's "System Integrity Protection / rootless".
- Tom

**Comment by jperkin** [comment]
Yeh, this is something other El Capitan users have noticed - let me construct a bootstrap kit using the full path, I'll have one available for testing shortly.

**Comment by tlcarpenter** [comment]
Thank you.
- Tom

**Comment by jperkin** [comment]
Ok, please try this (signed if you care):

https://us-east.manta.joyent.com/jperkin/public/tmp/bootstrap-2015Q3-x86_64.tar.gz
https://us-east.manta.joyent.com/jperkin/public/tmp/bootstrap-2015Q3-x86_64.tar.gz.asc

Thanks.

**Comment by tlcarpenter** [comment]
Downloaded/installed the modified 'bootstrap' package and was able to install and run the Claws Mail binary. Thanks again.

**Comment by jperkin** [comment]
Thanks!  I've updated the live bootstraps for both 32-bit and 64-bit.
