### ISSUE TITLE
setting system's PATH variable for pkgsrc

### ISSUE THREAD

**Issue by tlcarpenter** [TritonDataCenter/pkgsrc-legacy#304]
Is there an Apple and/or pkgsrc preferred method of setting a system-wide PATH variable appropriate for pkgsrc binary packages? There are suggestions to use OS X's "path_helper" mechanism (which XQuartz uses), edit /etc/paths, and probably others. Another approach I've seen mentioned is to have individual users modify their .profile or .bash_profile. I'd like to include the pkgsrc bootstrap package, along with a few applications installed from binary packages, in an image file I'd deploy to multiple machines, but I want (well, I think I want) to define the system PATH variable to eliminate the need for users to do such things as edit their .profile/.bash_profile. I suppose one could also go the route of creating/modifying .profile or .bash_profile in "/System/Library/User Template/English.lproj"...I just want to do things the "Apple way" to minimize the chances of future Apple updates breaking things for installed pkgsrc binary packages. Your thoughts?

**Comment by jperkin** [comment]
It looks like `/etc/paths.d` is the sensible path forward.  I've always added to my own .profile so wasn't aware of this previously, but it looks like a nice solution.  I'll add something to the docs along the lines of:

``` bash
printf "/opt/pkg/sbin\n/opt/pkg/bin\n" >/etc/paths.d/10-pkgsrc
```

and may even include that file as part of the bootstrap tarball so that it's done automatically, unless there are any particular reasons not to.  Input welcome here.

**Comment by JohnDDuncanIII** [comment]
I think that is a sane solution. Our friends over at the [saveosx project](https://github.com/cmacrae/saveosx/blob/master/bootstrap) (whose bootstrap I have been using recently) have been doing it for awhile now.

**Comment by tlcarpenter** [comment]
...guess the Apple tech I was chatting with may have given me an answer about the significance of path_helper filenames with numeric prefixes after all

http://www.softec.lu/site/DevelopersCorner/MasteringThePathHelper

"But, how does it construct these paths ?
...Moreover, it should have been specified that it reads these file in alphabetical order, so you may use filenames to decide what should comes first in your path, since path order is significant..."

**Comment by jperkin** [comment]
I've enabled this in the trunk tarball (https://pkgsrc.joyent.com/packages/Darwin/bootstrap/bootstrap-trunk-x86_64.tar.gz) as `/etc/paths.d/10-pkgsrc`.  Thanks for the suggestion!
