### ISSUE TITLE
rabbitmq-plugins doesn't seem to work in 2015Q3

### ISSUE THREAD

**Issue by benjamin-bergia** [TritonDataCenter/pkgsrc-legacy#305]
I am using the the base-64 15.3.0 image. 
The package version is rabbitmq-3.5.4

On a brand new zone run:

```
pkgin in rabbitmq
svcadm enable epmd
svcadm enable rabbitmq
rabbitmq-plugins list
```

Gives something like:
`/opt/local/sbin/rabbitmq-plugins[20]: .[100]: local: not found [No such file or directory]`

I tried to set `RABBITMQ_PLUGINS_DIR` to `/opt/local/lib/erlang/lib/rabbitmq_server-3.5.4/plugins`
But it doesn't seem to be related.

**Comment by benjamin-bergia** [comment]
After comparing with the SDC rabbitmq0 zone ( which run an older version ).
Both scripts  `/opt/local/sbin/rabbitmq-env` and `/opt/local/sbin/rabbitmq-plugins` seem to have been rewritten in bash. 

When running the new version it seems to block at the local variable declarations.

The current quick&dirty fix is removing the `local` but I am curious about the reason behind this problem.

**Comment by mamash** [comment]
Thanks for the notice. The real problem was in rabbitmq-env, which had a correct Bash shebang, but as it was sourced from rabbitmq-plugins (which didn't), it wasn't applied.

I fixed this in pkgsrc trunk now and also cleaned up rabbitmq-env while at it. It will show up in 2015Q4.

**Comment by benjamin-bergia** [comment]
Cool thank you very much.
