### ISSUE TITLE
hashicorp/vault patch for SmartOS/Solaris

### ISSUE THREAD

**Issue by doublerebel** [TritonDataCenter/pkgsrc-legacy#309]
I was recommended by @rmustacc in #smartos to file an issue here for tracking purposes.

I would like to see hashicorp/vault in pkgsrc, when compiled it is a self-contained binary that only needs a minimal configuration file.

The main patch needed is in my PR [hashicorp/vault#862](https://github.com/hashicorp/vault/pull/862).  However, a couple terminal calls and readPassword must be patched with a Solaris variant as well.

**Comment by doublerebel** [comment]
RE: terminal/ReadPassword calls, a similar patch is needed at [hashicorp/consul#159](https://github.com/hashicorp/consul/issues/159), to build Consul on SmartOS.

**Comment by mamash** [comment]
GitHub auto-closing trolls at work.

**Comment by mamash** [comment]
vault 0.5.2 doesn't seem to require any patching and I just imported it into the pkgsrc tree as security/vault.

**Comment by doublerebel** [comment]
@mamash Hi, I do not see vault available from pkgsrc in Q2. I see [consul was added in 2016Q2](https://github.com/joyent/pkgsrc/blob/pkgsrc_2016Q2/doc/CHANGES-2016#L2466) as well, and I see it in my 2016Q2 release when using pkgin on the JPC.  consul [has an additional commit, to add `EXTRACT_USING = bsdtar`](https://github.com/joyent/pkgsrc/blob/pkgsrc_2016Q2/sysutils/consul/Makefile#L12), could that be also necessary for vault?

I don't know how pkgsrc works in this regard and why vault would miss inclusion, despite being included in the Q2 repo and the [Q2 release notes](https://github.com/joyent/pkgsrc/blob/pkgsrc_2016Q2/doc/CHANGES-2016#L2464).

**Comment by mamash** [comment]
Here's the build failure for vault 0.5.2 in 2016Q2:

http://us-east.manta.joyent.com/pkgsrc/public/reports/2016Q2/x86_64/20160926.0941/vault-0.5.2/build.log

It's been updated since, which likely fixed the problem and 0.6.1 is available in the brand new 2016Q3 package set.

**Comment by mamash** [comment]
I'm not sure why it worked for me in May - I may have tested the package with Go older than what eventually went into 2016Q2?

**Comment by doublerebel** [comment]
Thanks, just wanted to check on it.  I had no idea where to look for those build logs!
