### ISSUE TITLE
Best "resource" for asking questions about fifo

### ISSUE THREAD

**Issue by mamalos** [TritonDataCenter/pkgsrc-legacy#313]
Hi everybody,

I think the subject is clear. Is there a mailing-list, a forum, an IRC channel or a google group? By googling I found  some logs of #project-fifo irc channel. Is it public and is it used for this purpose? And if so, which server is it hosted on?

The reason I am asking is because I am trying to setup fifo for our company and a few questions have arisen, so I would like to know where these questions can be discussed. I'm already a member of smartos-discuss mailing list, but I think that it is more SmartOS specific.

Sorry for asking this question here, but I didn't find any other place, and thanks for your answers in advance!

**Comment by jperkin** [comment]
I belive it's on Freenode, but I don't use fifo so I'm not sure.  https://project-fifo.net/ appears to have various links to support/bug trackers.
