### ISSUE TITLE
quagga zebra config dir mis-located

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc-legacy#316]
On 2015Q4, the zebra SMF service fails to start with the following:

```
[ Jan 23 10:06:07 Enabled. ]                                                    
[ Jan 23 10:06:07 Executing start method ("/opt/local/lib/svc/method/quagga zebra"). ]
touch: cannot create /etc/quagga/zebra.conf.new: No such file or directory      
[ Jan 23 10:06:07 Method "start" exited with status 95. ]                       
```

Creating a symlink from `/etc/quagga` to `/opt/local/etc/zebra` prevents the error, but obviously shouldn't be needed.

**Comment by jperkin** [comment]
Fixed in https://github.com/joyent/pkgsrc/commit/8b51a622671b5d6264dbbc8380fcae8dd2e65a10 and 2015Q4 is currently rebuilding to pick up this fix, thanks!
