### ISSUE TITLE
haproxy is missing from 2015Q4

### ISSUE THREAD

**Issue by nifoc** [TritonDataCenter/pkgsrc-legacy#317]
It looks like (at least?) the `haproxy` package is missing from the 2015Q4 release.

```
# uname -a
SunOS d8e33a09-cdd2-6f63-f355-a59483b86f44 5.11 joyent_20151112T202630Z i86pc i386 i86pc Solaris
# pkgin search haproxy
No results found for haproxy
```

I tried looking at [2015Q4/x86_64/All/](https://pkgsrc.joyent.com/packages/SmartOS/2015Q4/x86_64/All/), but that doesn't seem to include/mention the `haproxy` package either.

Not entirely sure what is going, because for 2015Q3 everything works as expected.

**Comment by jperkin** [comment]
This is currently failing due to

http://us-east.manta.joyent.com/pkgsrc/public/reports/2015Q4/x86_64/20160126.2254/haproxy-1.6.2/configure.log

I'll take a look at fixing this.

**Comment by jperkin** [comment]
Fixed in https://github.com/joyent/pkgsrc/commit/727dfea5d1536d7452aba33de9382faa1d76fa4b and 2015Q4 is currently being rebuilt to pick up this fix, thanks!

**Comment by nifoc** [comment]
Please pardon my ignorance, but how long does it usually take for a rebuild to finish? It looks like the `haproxy` isn't available again yet.

**Comment by jperkin** [comment]
Ok, now it's failing with a different error:

http://us-east.manta.joyent.com/pkgsrc/public/reports/2015Q4/x86_64/20160131.1105/haproxy-1.6.2/build.log

I'll take a look at this tomorrow.

**Comment by jperkin** [comment]
This is now fixed and available in the 2015Q4 repositories.
