### ISSUE TITLE
2015Q4 nmap missing

### ISSUE THREAD

**Issue by discostur** [TritonDataCenter/pkgsrc-legacy#318]
Hi,

can't find any nmap package in 2015Q4

Greets
Kilian

**Comment by jperkin** [comment]
Currently unavailable due to its dependency, liblinear, not building:

http://us-east.manta.joyent.com/pkgsrc/public/reports/2015Q4/x86_64/20160127.1555/liblinear-2.1/build.log

I'll take a look.

**Comment by jperkin** [comment]
This should now be available (give it a little while for mirrors to catch up if not).  Thanks.
