### ISSUE TITLE
pkgin: download mismatch: /var/db/pkgin/cache/git-docs-2.6.4.tgz

### ISSUE THREAD

**Issue by nifoc** [TritonDataCenter/pkgsrc-legacy#319]
Zone: base-64-lts 15.4.0

```
[root@d8e33a09-cdd2-6f63-f355-a59483b86f44 ~]# uname -a
SunOS d8e33a09-cdd2-6f63-f355-a59483b86f44 5.11 joyent_20151112T202630Z i86pc i386 i86pc Solaris
[root@d8e33a09-cdd2-6f63-f355-a59483b86f44 ~]# pkgin -v
pkgin 0.9.3 for SunOS-5.11 x86_64 (using SQLite 3.9.2)
[root@d8e33a09-cdd2-6f63-f355-a59483b86f44 ~]# pkgin in git-docs
calculating dependencies... done.

nothing to upgrade.
1 packages to be installed (605K to download, 2209K to install):

git-docs-2.6.4

proceed ? [Y/n] y
downloading packages...
git-docs-2.6.4.tgz                                                                                                100%  605KB 605.2KB/s 605.2KB/s   00:00
pkgin: download mismatch: /var/db/pkgin/cache/git-docs-2.6.4.tgz
```

Among other things, this causes the `build-essential` to not install, because it depends on `git-docs`.

I tried running `pkgin clean`, but that didn't help.

**Comment by nifoc** [comment]
I think the package repository (`2015Q4/x86_64`) is currently being updated.

Might that be the cause?

**Comment by jperkin** [comment]
Yeh, unfortunately there is always a window during rsync where things may get out of sync.  Normally this window is very very small so not usually noticed, but 2015Q4 had an OpenSSL rebuild over the past few days which causes a large number of packages to be rebuilt, slowing down the rsync and causing the mismatch between the packages and pkg_summary.xz depending on what has currently been synced.

Unfortunately there's no good solution to this, short of atomically switching out the entire packages directory, which isn't currently practical, but may be something we'll need to implement anyway.

**Comment by nifoc** [comment]
Thanks for the explanation, that makes perfect sense!

I'm going to close this, because everything is working again now.
