### ISSUE TITLE
minimal-64-lts (15.4.0) php-fpm is broken on install

### ISSUE THREAD

**Issue by trentster** [TritonDataCenter/pkgsrc-legacy#320]
just a FYI the minimal-64-lts (15.4.0) php-fpm is broken on install. The config file "/opt/local/etc/php-fpm.conf" references at the bottom an include for "include=/opt/local/etc/php-fpm.d/*.conf" there is however no "/opt/local/etc/php-fpm.d" directory on the system which causes the service to go into maintenance with an "exit status 96"

**Comment by mamash** [comment]
Ah, this is a change in PHP 7.0, it didn't used to be enabled in 5.x.

**Comment by jperkin** [comment]
Sorry, forgot to close this, was resolved a week or so ago.

**Comment by jperkin** [comment]
Looks like I didn't actually push this!  Working on that now.

**Comment by jperkin** [comment]
Ok this is fixed for real this time with `php70-fpm-7.0.3nb1.tgz` in the 2015Q4 repos.
