### ISSUE TITLE
tmux eating unicode multibyte characters

### ISSUE THREAD

**Issue by tidux** [TritonDataCenter/pkgsrc-legacy#324]
Hello,

Please rebuild or relink tmux to allow for the proper display of UTF-8.  The lack of high-multibyte support causes garbled control characters or vanished characters instead of the desired output.  You can see this by splitting a tmux window horizontally - you'll see a row of x's instead of the unicode characters that allow for cleaner splits.  Programs that can otherwise handle high-unicode characters properly like bash and vim exhibit similar problems when run inside tmux.  The GNU Screen package is built correctly to allow the display of such characters.

**Comment by tidux** [comment]
Weechat is also displaying similar unicode problems inside of screen, even though it links against libncursesw.

**Comment by jperkin** [comment]
I can't reproduce this with a 15.4.0 zone.  See attached screenshot with weechat running inside tmux, both the split pane characters and the UTF-8 I posted to myself in the IRC session display as expected.

Check your `LC_*` and `LANG` environment variables?  You can see mine in the screenshot.

![tmux-utf8](https://cloud.githubusercontent.com/assets/128042/13252342/1937ffd8-da2e-11e5-8266-de716bfda501.png)

**Comment by tidux** [comment]
After setting LC_ALL manually to en_US.UTF-8 the only packages still displaying problems are weechat and `mosh`.  Irssi and tmux do not display this problem with LC_ALL set.

**Comment by mamash** [comment]
I just tried with the current Darwin trunk package set, and I'm sorry to say can't replicate this with mosh and a UTF-8 locale (which mosh requires anyway). Please re-open with steps to reproduce, if you feel this is still a problem.
