### ISSUE TITLE
aria2 missing in 2015Q4

### ISSUE THREAD

**Issue by jjlawren** [TritonDataCenter/pkgsrc-legacy#325]
Found this when upgrading from 2014Q4 where it was available.

**Comment by mamash** [comment]
Yup, the build is breaking currently due to misidentified epoll support. We'll fix this.

**Comment by mamash** [comment]
Package now in 2015Q4. Thanks for the report!

**Comment by jjlawren** [comment]
Thanks for the quick fix!
