### ISSUE TITLE
HAProxy: Default configuration file missing from 2015Q4

### ISSUE THREAD

**Issue by benjamin-bergia** [TritonDataCenter/pkgsrc-legacy#330]
It looks like the new package from 2015Q4 doesn't include a default configuration file.

**Comment by mamash** [comment]
Upstream stopped installing any config file in 1.6. We can add the [example config files](http://git.haproxy.org/?p=haproxy-1.6.git;a=tree;f=examples;h=6ab330224c94ee669ff7f5dc962077f12cfdf7d9;hb=HEAD) to $PREFIX/share/examples/haproxy, but none of them is fit to serve as one designated as a default config file (well, the old one wasn't either)..

**Comment by benjamin-bergia** [comment]
Oh I see.  I didn't notice the example files. If examples are already installed by the packages don't bother with the default configuration file.
Thank you for checking anyway

**Comment by mamash** [comment]
They haven't been included so far, I just made that commit to upstream pkgsrc's Makefile, as part of updating haproxy to 1.6.4.
