### ISSUE TITLE
Framework build of Python on MacOSX

### ISSUE THREAD

**Issue by affixalex** [TritonDataCenter/pkgsrc-legacy#331]
What I'm aiming for here is to use Joyent pkgsrc to form a data science workflow using Python 3.5 and Jupyter notebook on OSX which can then be moved directly into production with the same package versions. Inline rendering in Jupyter notebook using matplotlib relies upon a framework build of Python, which is not currently how Python is built by pkgsrc on Darwin.

To reproduce this...

```
curl -Os https://pkgsrc.joyent.com/packages/Darwin/bootstrap/bootstrap-trunk-x86_64-20160211.tar.gz
sudo tar -zxpf bootstrap-trunk-x86_64-20160211.tar.gz -C /
rm bootstrap-trunk-x86_64-20160211.tar.gz
PATH=/opt/pkg/sbin:/opt/pkg/bin:$PATH
sudo pkgin -y update
sudo pkgin in python35-3.5.1nb2 py35-pip-7.1.2 zeromq-4.1.4 py35-sqlite3-3.5.1nb6
sudo -H pip install --upgrade pip 
sudo -H pip install jupyter matplotlib==1.5.1
```

This is the default, but to be explicit:

```
mkdir /.matplotlib && echo "backend: macosx" >> ~/.matplotlib/matplotlibrc
```

You may then run [benchmark.py](https://gist.github.com/hypoalex/d3950ba4ea7fe8159377) to receive an error along the lines of:

```
from matplotlib.backends import _macosx
    RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to
    function correctly if Python is not installed as a framework. See the Python documentation for more
    information on installing Python as a framework on Mac OS X. Please either reinstall Python as a
    framework, or try one of the other backends. If you are Working with Matplotlib in a virtual
    enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

The `--enable-framework` [Python ./configure option](https://github.com/python/cpython/blob/master/configure#L1463) can be used to enable a framework build. I believe that in order to actually function correctly, a symlink to /Library/Frameworks would be necessary but I'm not totally sure about this (and obviously it would be preferable to keep everything within /opt/pkg).

You may also run `jupyter notebook` then create a new Python 3 file and paste in the contents of [plot.py](https://gist.github.com/hypoalex/b0b9e937dbc70e7fedfd) to receive the same error in a jupyter console. The result here should be an inline rendering of the plot. 

A cursory look points to something along the lines of:

```
.if ${OPSYS} == "Darwin"
CONFIGURE_ARGS+= "--enable-framework"
```

I'll give this a try at some point this week and submit a PR if it works.

**Comment by affixalex** [comment]
Forgot to say, thanks so much for maintaining the OSX binary repository! It's a huge convenience.

**Comment by affixalex** [comment]
This actually works fine ![as you can see here](https://cloud.githubusercontent.com/assets/146552/13777321/6fd74d08-ea7d-11e5-9b23-a7e9023bd962.png). This approach is preferable to a Darwin framework build because it works across platforms and is totally self-contained. I'm leaving a note here in case anyone else runs into this issue.

```
sudo pkgin in gcc5-5.3.0nb1 python35-3.5.1nb2 py35-pip-7.1.2 zeromq-4.1.4 py35-qt4-4.11.4nb2 py35-sqlite3-3.5.1nb6
sudo ln -s /opt/pkg/gcc5/bin/gfortran /opt/pkg/bin/gfortran
sudo -H pip install --upgrade pip 
sudo -H pip install fake-factory flask jupyter pandas scipy sklearn matplotlib==1.5.1
sudo -H pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp35-none-any.whl
```

The important part for inline rendering in Jupyter notebook is including `%matplotlib inline` as the first line of your file, otherwise you'll invoke a separate QT window (which might be desirable in some cases).

**Comment by jperkin** [comment]
Ok cool, good to know.  From my brief look at the Framework stuff it didn't look workable anyway, as we would need to have special PLIST handling for every python package due to the files moving to the framework directory, and that would be non-trivial and a lot of work.
