### ISSUE TITLE
pgBouncer: postgres home directory not created

### ISSUE THREAD

**Issue by benjamin-bergia** [TritonDataCenter/pkgsrc-legacy#332]
I just installed pgbouncer from 2015Q4. 
pgBouncer use the postgres user. Apparently, the home directory of the user (/var/pgsql) is not created during installation. This directory is also used as the `working_directory` of the SMF manifest which means that out of the box pgbouncer doesn't work.

I wonder if it wouldn't be better to have a different system user for pgbouncer since not everybody is installing it in the same zone than postgresql.

**Comment by mamash** [comment]
You're right, and the directory is actually not used at all. I just updated the package to 1.7.2 in upstream CVS trunk, and made it create its own user with the home set to its log file dir.

**Comment by benjamin-bergia** [comment]
Thank you :)
