### ISSUE TITLE
gcc48-4.8.4.tgz not in Darwin trunk repository

### ISSUE THREAD

**Issue by affixalex** [TritonDataCenter/pkgsrc-legacy#333]
I want to note that my bug reports are meant constructively! GCC 5.3 (and gfortran) are present and work fine, I'm not sure how to mark a report as low priority but this definitely qualifies.

Essentially this is just a note. 

```
alex@amnesiac ~ $ sudo pkgin in blas-3.5.0nb1
calculating dependencies... done.

nothing to upgrade.
7 packages to be installed (46M to download, 161M to install):

mpfr-3.1.4 mpcomplex-1.0.3 isl-0.14.1 gmp-6.1.0 cloog-0.18.1 gcc48-4.8.4 blas-3.5.0nb1

proceed ? [Y/n] 
downloading packages...
pkgin: http://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/gcc48-4.8.4.tgz: Not Found
```

**Comment by jperkin** [comment]
Not a problem!  Thanks, I'll take a look at this (there's a known issue at the moment with some packages sneaking into pkg_summary when the build failed, due to stale cached data).

**Comment by mamash** [comment]
This was resolved earlier.
