### ISSUE TITLE
math/R: dependency on 'libR.dynlib'

### ISSUE THREAD

**Issue by uebayasi** [TritonDataCenter/pkgsrc-legacy#337]
If I try installing 'R' on Mac OS X using 2015Q3, 'pkgin in R' fails because of missing dependency on 'libR.dynlib' (not preceding subdirectory).  I managed to remove the corresponding entry in /var/db/pkgin/pkgin.db by using sqlite3(1) command.  Then I could install 'R' and it seems working.

**Comment by jperkin** [comment]
Known issue with older packages.  We added extra checks, and the packages from trunk no longer have unresolved dependencies.  I'll be releasing the trunk packages shortly.  Thanks!
