### ISSUE TITLE
Xvfb fails on multiarch-2012Q4

### ISSUE THREAD

**Issue by jessegit** [TritonDataCenter/pkgsrc-legacy#34]
Xvfb fails to start on multiarch-2012Q4:

% Xvfb :7 -screen 0 1280x1024x24
Fatal server error:
Couldn't add screen 0
%

After tracing the problem to the same place as the following message archive points to:

http://www.openwall.com/lists/musl/2012/10/26/10

and transplanting

int XaceHook(int hook, ...) {

from https://raw.github.com/robclark/xserver/master/Xext/xace.c (totally random url, I took the first google hit with the fixed function) Xvfb starts.

The Xvfb crashed after using it so I'm assuming other places in the code do not handle gcc 4.7.2 too well either. Proper fix is apparently upgrading the xserver to a newer version.

**Comment by jperkin** [comment]
This was fixed with the modular-xorg updates as part of pkgsrc-2013Q2.
