### ISSUE TITLE
netperf lost in 2015Q4

### ISSUE THREAD

**Issue by rmustacc** [TritonDataCenter/pkgsrc-legacy#340]
It looks like the multiarch build no longer has netperf in 2015Q4 though it is there in 2014Q4.

**Comment by jperkin** [comment]
I've fixed this on trunk and backported to 2015Q1, it should be available in the build currently running.

**Comment by jperkin** [comment]
2015Q4, of course...

**Comment by jperkin** [comment]
FYI this is now available.
