### ISSUE TITLE
Guacamole complains about libpng

### ISSUE THREAD

**Issue by TyrfingMjolnir** [TritonDataCenter/pkgsrc-legacy#341]
http://guac-dev.org/doc/gug/installing-guacamole.html#required-dependencies
## From ./configure

checking for png_write_png in -lpng... no
## configure: error: "libpng is required for writing png messages"

I followed this guide: http://guac-dev.org/doc/gug/installing-guacamole.html#building-guacamole-server to the extent possible.
## config.log

configure:12752: gcc -std=gnu99 -o conftest -g -O2  -L/usr/local/lib conftest.c -lpng   >&5
Undefined                       first referenced
 symbol                             in file
inflateReset2                       /opt/local/lib//libpng.so
ld: fatal: symbol referencing errors. No output written to conftest

**Comment by mamash** [comment]
That's related to zlib support in png. The pkgsrc libz (/opt/local/lib/libz.so.1) needs to be used, rather than the platform one (/usr/lib/libz.so.1); it's more recent and defines the inflateReset2 symbol (and our png package was built against it).

The configure compile line you're quoting doesn't seem to be passing proper search paths. Does it support specifying search paths for libpng and/or libz explicitly using configure args or env variables?

**Comment by TyrfingMjolnir** [comment]
http://guac-dev.org/doc/gug/installing-guacamole.html#optional-dependencies

## Obstacle one gone, removed as below

cd /opt/local/lib
ln -s libpng16.so.16.20.0 libpng.so
cd /opt/local/src/guacamole-server-0.9.9
./configure LDFLAGS="-L/opt/local/lib -lsocket"

## New obstacle

---

## guacamole-server version 0.9.9

   Library status:

```
 freerdp ............. yes
 pango ............... no
 libssh2 ............. yes
 libssl .............. yes
 libtelnet ........... no
 libVNCServer ........ yes
 libvorbis ........... yes
 libpulse ............ no
 libwebp ............. yes
```

   Protocol support:

```
  RDP ....... yes
  SSH ....... no
  Telnet .... no
  VNC ....... yes
```

   Init scripts: no

Type "make" to compile guacamole-server.

Neither ssh nor pango
Libpulse and libtelnet are not available as packages in SunOS

config.log: http://termbin.com/smcd

**Comment by mamash** [comment]
We'd added libtelnet in the past and libpulse has always been part of the pulseaudio. Jonathan added a guacamole package to pkgsrc this month, so that will show up in 2016Q2. Please test that as it becomes available.
