### ISSUE TITLE
security/pam_radius fails due to expecting different libpam header layout in base

### ISSUE THREAD

**Issue by Kurlon** [TritonDataCenter/pkgsrc-legacy#343]
Trying to build pam_radius 1.4.0 results in a configure failure complaining that /usr/include/security/pam_modules.h is present but cannot be compiled.  Digging in further shows this failure during configure:

```
configure:4543: checking security/pam_modules.h usability
configure:4543: gcc -c -g -O2 -Wall -D_GNU_SOURCE  conftest.c >&5
In file included from conftest.c:83:0:
/usr/include/security/pam_modules.h:38:2: error: unknown type name 'pam_handle_t'
  pam_handle_t *pamh,
  ^
/usr/include/security/pam_modules.h:45:2: error: unknown type name 'pam_handle_t'
  pam_handle_t *pamh,
  ^
/usr/include/security/pam_modules.h:52:2: error: unknown type name 'pam_handle_t'
  pam_handle_t *pamh,
  ^
/usr/include/security/pam_modules.h:59:2: error: unknown type name 'pam_handle_t'
  pam_handle_t *pamh,
  ^
/usr/include/security/pam_modules.h:66:2: error: unknown type name 'pam_handle_t'
  pam_handle_t *pamh,
  ^
/usr/include/security/pam_modules.h:80:2: error: unknown type name 'pam_handle_t'
  pam_handle_t *pamh,
  ^
/usr/include/security/pam_modules.h:92:2: error: unknown type name 'pam_handle_t'
  pam_handle_t *pamh,  /* PAM handle */
  ^
/usr/include/security/pam_modules.h:95:18: error: unknown type name 'pam_handle_t'
  void (*cleanup)(pam_handle_t *pamh, void *data, int pam_end_status)
                  ^
/usr/include/security/pam_modules.h:104:8: error: unknown type name 'pam_handle_t'
  const pam_handle_t *pamh,
        ^
```

Looking at the header files in base I can see where pam_handle_t is defined in /usr/include/security/pam_appl.h.  Looking at libpam's src repository pam_handle_t is normally defined in _pam_types.h and pulled into pam_modules.h as an include.  If I manually include the pam_handle_t typedef into pam_modules.h then pam_radius_auth builds.

I'm not sure what the proper way to work around this is, patch the configure script to skip the compile test on that one header file, force it to manually drag in pam_appl.h when it tests, or something else.

**Comment by jclulow** [comment]
I don't think there is anything _"non-standard"_ here.  Looking at the illumos manual page [pam_sm(3PAM)](http://illumos.org/man/3PAM/pam_sm), we see that a PAM service module is expected to include `security/pam_appl.h` before including `security/pam_modules.h`.  This also appears to be the case in the OpenGroup documentation and documents for other platforms like Mac OS X.

I suspect `pam_radius` should be fixed to have the correct includes.

**Comment by Kurlon** [comment]
I was referencing against libpam's src, didn't know about that particular man page so I'll add that to my notes.  So, it sounds like I need to figure out how to coax configure to force including pam_appl.h when testing for other includes, and make sure that propagates to the make script as well?

**Comment by jclulow** [comment]
Are there platforms that ship `security/pam_modules.h` without also shipping `security/pam_appl.h`?  It seems like the code should just always test for, and include, both together.

**Comment by Kurlon** [comment]
On other platforms that use libpam, `security/pam_modules.h` and `security/pam_appl.h` both have include statements to pull in `security/_pam_types.h`.  At that point you can include `pam_modules.h` and automatically get the required typedef without explicitly including the other files.  This is the behavior the configure script for pam_radius is expecting.  Weather or not `pam_modules.h` and `pam_appl.h` are actually useful for anything on their own beyond a basic gcc test pass I can't say.

I'm going to dig a bit into FreeRadius' src to see if I can find the change that broke pam_radius on Sun as I know it used to build cleanly in the past.

**Comment by Kurlon** [comment]
Found a commit in the pam_radius git that appears to address this issue directly from Jan of 2015:
https://github.com/FreeRADIUS/pam_radius/commit/f6e2fb9a2dd04e23e7ca16350e6c3a8ccbd52d33

I should be able to patch `configure` and `configure.ac` to match, which will get pam_radius building again while waiting for a new release that includes this fix in it.

**Comment by Kurlon** [comment]
Confirmed, the fix from pam_radius's head applies cleanly and results in a viable binary.  I'll see if I can't correct the package and make a proper pull request next.

**Comment by Kurlon** [comment]
Updated patch-configure and new patch-configure.ac attached.

[pam-radius-patches.zip](https://github.com/joyent/pkgsrc/files/198020/pam-radius-patches.zip)

**Comment by Kurlon** [comment]
If I do up a pull request, would you prefer I go against head or the current stable tag?

**Comment by mamash** [comment]
Head is better, we'd apply manually anyway, as the upstream is CVS.

**Comment by Kurlon** [comment]
Pull request filed.  I'm way too rusty at this.

**Comment by mamash** [comment]
Committed upstream, thanks!
