### ISSUE TITLE
Status of stud and import hitch

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc-legacy#344]
The official stud repository has been updated with a note officially declaring it abandoned. See bumptech/stud@663d9c3.

The author recommends hitch (https://hitch-tls.org) as a replacement. Hitch itself is a renamed fork of stud. See varnish/hitch@d02b4d0.

Hitch should be imported to pkgsrc, and it may be worth while to replace stud with a transition package.

**Comment by mamash** [comment]
Can't get hitch to work for the moment - segfaults on any attempt to use the binary.

**Comment by mamash** [comment]
Imported as wip/hitch for now.

**Comment by bahamat** [comment]
If I can get a copy I'll dtrace it and I can file a bug upstream.

**Comment by mamash** [comment]
Have a look at http://us-east.manta.joyent.com/pkgsrc/public/tmp/hitch-1.1.1.tgz, it should install on a 15.4.x 64bit VM.

**Comment by mamash** [comment]
The 1.2.0 released recently seems to have fixed the problem, builds and runs fine for me. I'll bring it into pkgsrc.

**Comment by mamash** [comment]
hitch-1.2.0 is available in 2015Q4, let us know how it works.
