### ISSUE TITLE
gdb is missing from 2015.Q4

### ISSUE THREAD

**Issue by sodre** [TritonDataCenter/pkgsrc-legacy#347]
GDB has been lost in 2015.Q4

**Comment by mamash** [comment]
GDB also installs libbfd and libopcodes by default, which are also provided by the binutils package, and pbulk doesn't like the conflict. I fixed this in upstream CVS now and will backport to 2015Q4.

**Comment by mamash** [comment]
Back now in 2015Q4, thanks for the report!

**Comment by sodre** [comment]
Awesome. Thanks!

Patrick
