### ISSUE TITLE
sendmail 8.14.5nb2  2012Q4

### ISSUE THREAD

**Issue by smartOSuser** [TritonDataCenter/pkgsrc-legacy#35]
=> Automatic manual page handling
pkg_create: can't stat `/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/bin/hoststat'
pkg_create: can't stat`/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/bin/mailq'
pkg_create: can't stat `/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/bin/newaliases'
pkg_create: can't stat`/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/bin/purgestat'
pkg_create: can't stat `/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/libexec/sendmail/sendmail'
pkg_create: can't stat`/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/man/man1/mailq.1'
pkg_create: can't stat `/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/man/man1/newaliases.1'
pkg_create: can't stat`/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/man/man5/aliases.5'
pkg_create: can't stat `/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/man/man8/sendmail.8'
===> Building binary package for sendmail-8.14.5nb2
=> Creating binary package /opt/pkgsrc/packages/All/sendmail-8.14.5nb2.tgz
pkg_create: can't stat`/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/bin/hoststat'
pkg_create: can't stat `/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/bin/mailq'
pkg_create: can't stat`/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/bin/newaliases'
pkg_create: can't stat `/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/bin/purgestat'
pkg_create: can't stat`/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/libexec/sendmail/sendmail'
pkg_create: can't stat `/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/man/man1/mailq.1'
pkg_create: can't stat`/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/man/man1/newaliases.1'
pkg_create: can't stat `/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/man/man5/aliases.5'
pkg_create: can't stat`/opt/pkgsrc/mail/sendmail/work/.destdir/opt/local/man/man8/sendmail.8'
pkg_create: lstat failed for file bin/hoststat: No such file or directory
**\* Error code 2

Stop.
bmake: stopped in /opt/pkgsrc/mail/sendmail
**\* Error code 1

Stop.
bmake: stopped in /opt/pkgsrc/mail/sendmail

**Comment by jperkin** [comment]
There are currently around 3,000 packages in pkgsrc which do not build or package correctly under SmartOS.  Without supplying patches to fix issues there's not much benefit in having issues logged for failures, we already have bulk build reports which tell us what's broken, so I'm going to close this.  Feel free to work on and submit a patch though!

**Comment by smartOSuser** [comment]
i have been following your pkgsrc build articles on your  http://www.perkin.org.uk and really appreciate them. I will see what I can do about fixing this.
