### ISSUE TITLE
tmux 2.1 package for mac

### ISSUE THREAD

**Issue by jtmkrueger** [TritonDataCenter/pkgsrc-legacy#351]
This is currently missing, and I'm willing to create it myself if someone would be kind enough to point me to some instructions!

**Comment by bahamat** [comment]
It's [here](../tree/trunk/misc/tmux/Makefile).

And I have it installed:

```
i: uname -sr
Darwin 15.4.0
i: pkgin avail | grep tmux
tmux-2.1nb1          BSD-licensed terminal multiplexer (GNU Screen alternative)
i: pkg_info -e tmux
tmux-2.1
```

**Comment by jtmkrueger** [comment]
hm, I get different output:

```
▶ uname -sr
Darwin 14.5.0

~/Code/mea-apis  sled ✔                                                                                                                                                                                                                                                                                                                                               72d
▶ pkgin avail | grep tmux
tmux-2.0nb2          BSD-licensed terminal multiplexer (GNU Screen alternative)

```

do I need to do some sort of update? I'm on a mac, if that makes any sort of difference, and I'm pretty newb with pkgsrc.

**Comment by bahamat** [comment]
Ah, it's because I'm on trunk (https://pkgsrc.joyent.com/packages/Darwin/bootstrap/).

We'll be replacing quarterly releases for OS X with rolling-release trunk soon, which is why there hasn't been a 2015Q4 release. The official trunk release for OS X will be coming soon, but feel free to switch to trunk ahead of the release if you like.

**Comment by jtmkrueger** [comment]
what's the path to switch to trunk? All I've done is follow [these](https://pkgsrc.joyent.com/install-on-osx/) instructions, so I might not be set up to switch.

**Comment by bahamat** [comment]
You can either rebootstrap, (use `pkgin show-keep` to list all of the packages you have installed so you can install them after bootstrapping), or you can edit the following files
- /opt/pkg/etc/pkg_install.conf
- /opt/pkg/etc/pkgin/repositories.conf

Switch `2015Q3` (or whatever you have) to `trunk`.

Then run:

```
pkgin -f up
pkgin full-upgrade
```

**Comment by jtmkrueger** [comment]
ok, I made those switches, ran the commands, but now I'm getting an error when I run pkgin commands:

```
~                                                                                                                                                                                                                                                                                                                                                                         ⍉
▶ pkgin -y update
dyld: Library not loaded: /opt/pkg/lib/libarchive.13.dylib
  Referenced from: /opt/pkg/bin/pkgin
  Reason: image not found
[1]    59778 trace trap  pkgin -y update
```

probably a simple solution, but I'm not sure what to do next...

**Comment by bahamat** [comment]
Can you give me the full transcript leading up to that?

**Comment by jtmkrueger** [comment]
sure, [here's a gist](https://gist.github.com/jtmkrueger/025fe6bf2ae89f373c464dc77268a9a4)

**Comment by jtmkrueger** [comment]
and [here's the error log](https://gist.github.com/jtmkrueger/54a4a317e2cdf384a2f6041ed195a57a)

**Comment by bahamat** [comment]
What does `pkg_info -e libarchive` show?

If it's missing, run this

```
pkg_add -C /dev/null https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/libarchive-3.1.2nb2.tgz
```

**Comment by jtmkrueger** [comment]
hm, it is missing, but when I try and run that I get this:

```
~                                                                                                                                                                                                                                                                                                                                                                         ⍉
▶ pkg_add -C /dev/null https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/libarchive-3.1.2nb2.tg
SSL support disabled
SSL support disabled
pkg_add: Can't process https://pkgsrc.joyent.com:443/packages/Darwin/trunk/x86_64/All/libarchive-3*: Authentication error
pkg_add: no pkg found for 'https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/libarchive-3.1.2nb2.tg', sorry.
pkg_add: 1 package addition failed
```

what do I need to do to enable ssl support?

**Comment by bahamat** [comment]
It has to be recompiled. Do this then:

```
/usr/bin/curl -o /tmp/libarchive-3.1.2nb2.tgz https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/libarchive-3.1.2nb2.tgz
pkg_add -C /dev/null -U /tmp/libarchive-3.1.2nb2.tgz
```

**Comment by jtmkrueger** [comment]
looks like I'm missing something:

```
~
▶ /usr/bin/curl -o /tmp/libarchive-3.1.2nb2.tgz https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/libarchive-3.1.2nb2.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  792k  100  792k    0     0   695k      0  0:00:01  0:00:01 --:--:--  695k

~
▶ pkg_add -C /dev/null -U /tmp/libarchive-3.1.2nb2.tgz
can't read '/Users/jkrueger/.gnupg/pubring.gpg'pkg_add: cannot read keyring: No such file or directory
```

**Comment by bahamat** [comment]
You should be able to `touch /Users/jkrueger/.gnupg/pubring.gpg` and rerun pkg_add.

**Comment by jtmkrueger** [comment]
now it can't verify the signature: 

```
▶ pkg_add -C /dev/null -U /tmp/libarchive-3.1.2nb2.tgz
pkg_add: unable to verify signature: Signature key id 6d94c02e1f32a9ad not found
```

do I need to stick the key in the file I touched?

**Comment by bahamat** [comment]
`-C /dev/null` is supposed to bypass that.

At this point, I think it may be a better option to rebootstrap.

**Comment by jtmkrueger** [comment]
when you say rebootstrap, do you mean follow the instructions at https://pkgsrc.joyent.com/install-on-osx/ ?

**Comment by bahamat** [comment]
Yes, except using the bootstrap file for trunk instead of the one specified there.

Rename `/opt/pkg` to `/opt/pkg_old`, then you can reference `/opt/pkg_old/.pkgdb/` to see which packages you had installed, then follow the normal bootstrap instructions with the new bootstrap package.

**Comment by jtmkrueger** [comment]
great, I'm back in action with tmux 2.1

Am I going to need to do this every time a new release comes out? or should my database update accordingly now?

**Comment by bahamat** [comment]
No, trunk will be on a rolling release. You won't need any more fork lifts. It also means that you'll get access to newer software sooner (no more sitting on an older release while there's an update available but out of reach).

**Comment by jtmkrueger** [comment]
That's good to hear, and thanks so much for helping me out, I really appreciate it!
