### ISSUE TITLE
url2pkg returns error

### ISSUE THREAD

**Issue by jtmkrueger** [TritonDataCenter/pkgsrc-legacy#352]
No matter where I try and run it, I get

`/opt/pkg/bin/url2pkg must be run from a package directory (.../pkgsrc/category/package). at /opt/pkg/bin/url2pkg line 517.`

Did running through the install instructions for osx on the installation web page actually install pkgsrc?

If so, where do I need to create my directory?

_EDIT_

I've tried creating directories from root, and also in `/opt/pkg`

**Comment by bahamat** [comment]
You need to check out a copy of pkgsrc and run it from inside a package directory within the pkgsrc tree.

E.g. to import a package named `foo`:

```
git clone https://github.com/joyent/pkgsrc
cd pkgsrc
mkdir misc/foo
cd misc/foo
url2pkg http://www.example.com/foo.tgz
```

**Comment by mamash** [comment]
The guide at https://pkgsrc.joyent.com only installs the binary pkgsrc bootstrap that lets you install binary packages. The docs to install the actual pkgsrc tree are here:

https://pkgsrc.joyent.com/docs/building/

**Comment by jtmkrueger** [comment]
Perfect, thanks for the link!
