### ISSUE TITLE
smstools missing from pkgsrc

### ISSUE THREAD

**Issue by jussisallinen** [TritonDataCenter/pkgsrc-legacy#353]
smstools would be useful in pkgsrc, it's used to interact with GSM modems for sending Short Message Service (SMS) messages to GSM network.

http://smstools3.kekekasvi.com/
http://pkgsrc.se/wip/smstools

**Comment by mamash** [comment]
Thanks, Jussi. I updated wip/smstools to the last available version and will add it to our builds.

**Comment by mamash** [comment]
smstools-3.1.15 now available in 2015Q4.
