### ISSUE TITLE
php extensions and configuration files

### ISSUE THREAD

**Issue by xen0l** [TritonDataCenter/pkgsrc-legacy#355]
When installing php extentions (e.g. php70-json), one has to add 'extension=json.so' line to php.ini. It would be pretty useful if extension delivered a file, which contains that line in /opt/local/etc/php.d/json.conf and php.ini was configured to include *.conf files from /opt/local/etc/php.d. It would help and simplify operator's job.

**Comment by jperkin** [comment]
pkgsrc deliberately does not do this.  This could cause havoc with running systems, where a system administrator may want to install a package but it brings in a bunch of PHP modules they do not want to automatically enable for reasons of security or conflict with existing modules, and may not even notice if they don't carefully parse the dependencies being pulled in.

The default is always to install disabled.  This avoids magic and unwanted side-effects, and ensures a consistent environment where the administrator makes deliberate choices about the services they want to run.
