### ISSUE TITLE
GNU screen gone from Darwin 2015Q3

### ISSUE THREAD

**Issue by melloc** [TritonDataCenter/pkgsrc-legacy#358]
It looks like the screen package disappeared between 2015Q1 and 2015Q3.

**Comment by jperkin** [comment]
Thanks Cody, this is fixed in 8fc7feffb14a13c4974010c27a52374c7676772e and a screen package will be in the new trunk set which I'll be releasing shortly.

**Comment by mamash** [comment]
This was fixed earlier.
