### ISSUE TITLE
tmux missing in 2016Q1 release

### ISSUE THREAD

**Issue by RSully** [TritonDataCenter/pkgsrc-legacy#360]
I see tmux in git, but not listed here: http://pkgsrc.joyent.com/packages/SmartOS/2016Q1/x86_64/All/

`pkgin search` returns no results

**Comment by KrisShannon** [comment]
Current tmux in pkgsrc won't build due to tmux/tmux#212

**Comment by mamash** [comment]
I backported the update to 2016Q1 today.
