### ISSUE TITLE
Too old sqlgrey in pkgsrc

### ISSUE THREAD

**Issue by jussisallinen** [TritonDataCenter/pkgsrc-legacy#366]
Current version of sqlgrey in pkgsrc is 1.6.8 (2007), latest version is 1.8.0 (2012).

https://sourceforge.net/projects/sqlgrey/files/sqlgrey-1.8%20%28stable%29/

**Comment by mamash** [comment]
They still list 1.6.8 as the latest stable on their home site, which is likely the reason why the package hasn't been updated in pkgsrc.

**Comment by jussisallinen** [comment]
That's true, they must have forgotten to update the page :-)

**Comment by mamash** [comment]
Updated in upstream CVS. Thanks for the notice!
