### ISSUE TITLE
postgresql95-contrib missing ?

### ISSUE THREAD

**Issue by benjamin-bergia** [TritonDataCenter/pkgsrc-legacy#368]
Hi,

apparently postgresql 9.5 doesn't have a separate contrib package (like 9.4 does). Is it an omission or is it now included in the postgresql95-server by default ?

**Comment by mamash** [comment]
postgresql94-contrib started as an experiment to see if it makes sense to create such packages. Normally parts of contrib exist as separate packages (e.g. postgresql95-datatypes).

**Comment by benjamin-bergia** [comment]
Oh ok .... my bad

I found pretty much all the extensions that I need but:
- pg_trgm
- btree_gin

Would it be possible to get them included in datatypes ? I think it's pretty common extensions.

**Comment by benjamin-bergia** [comment]
Sorry I closed the issue by mistake. Is it possible to get these two extensions included in datatypes ?

**Comment by mamash** [comment]
Yep. I'm going through the missing stuff and I'll see individually whether to tack them onto existing packages (e.g. btree_gin belongs into datatypes) or create new separate ones.

**Comment by benjamin-bergia** [comment]
@mamash Thanks

**Comment by mamash** [comment]
After discussing this with another pkgsrc developer who also works on PostgreSQL packages, we decided to make things simple and in line with other worlds, so starting with 2016Q2, there will be a fat postgresql9[1-5]-contrib package. I just made the commits to pkgsrc trunk, the 2016Q2 freeze period starts tomorrow.

**Comment by benjamin-bergia** [comment]
@mamash Thanks for the update. I will close this issue.
