### ISSUE TITLE
MySQL 5.7 missing from pkgsrc

### ISSUE THREAD

**Issue by jussisallinen** [TritonDataCenter/pkgsrc-legacy#369]
pkgsrc is missing MySQL 5.7, currently it only provides 5.6.x and older.

**Comment by mamash** [comment]
I'd started to work on this, but too many things changed with 5.7 and I won't make it for the 2016Q2 freeze that's scheduled for today.

**Comment by mamash** [comment]
Our preliminary version was just wrapped up by Adam Ciarcinski, and imported into upstream pkgsrc. It will show up in 2016Q3.

**Comment by jacques** [comment]
Thank you Filip! :)
