### ISSUE TITLE
zsh missing from trunk-0.99.0

### ISSUE THREAD

**Issue by calmh** [TritonDataCenter/pkgsrc-legacy#37]
```
[root@trunk-lab ~]# which zsh
no zsh in /opt/local/bin /opt/local/sbin /usr/bin /usr/sbin
[root@trunk-lab ~]# pkgin se zsh
No results found for zsh
[root@trunk-lab ~]#
```

My beloved login shell, faithful to me since many years, nowhere to be found. :(

**Comment by jperkin** [comment]
I've fixed this upstream, it should appear in the repository within a couple of days.

**Comment by calmh** [comment]
Awesome, thanks. It's great to have the Development Preview dataset, your work is appreciated.
