### ISSUE TITLE
Emacs on OS X runs only in the terminal

### ISSUE THREAD

**Issue by iamitava** [TritonDataCenter/pkgsrc-legacy#370]
I installed emacs-24.5 from the trunk packages (using pkgin); running `/opt/pkg/bin/emacs` runs emacs in the terminal – I was expecting a graphical (Cocoa) version. This is the first package I installed (I wanted to see how pkgsrc works on OS X), so I could have easily missed something (and this might not be an _Issue_ at all!).

I'm on El Capitan (10.11.5). Installed package is http://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/emacs-24.5.tgz

**Comment by jperkin** [comment]
Thanks for the report!  The build was defaulting to the x11 option, which I've now changed in [this commit](http://mail-index.netbsd.org/pkgsrc-changes/2016/05/31/msg141545.html).

This ensures the package uses the Cocoa framework by default on Darwin, though in my testing you need to launch with "open -a emacs" or the full path to `/opt/pkg/Applications/Emacs.app/Contents/MacOS/Emacs` to get the toolbar menus to appear.

The build host is currently in the middle of a build, but will pick up this change on the next run.  I'd estimate the new package will be available by the weekend, look out for `emacs24-24.5nb11`.

**Comment by iamitava** [comment]
Thanks @jperkin! The missing toolbar menu seems to be an OS X bug, I have seen that earlier too :(
