### ISSUE TITLE
PowerDNS in pkgsrc 2016Q1 Security Update Mandatory

### ISSUE THREAD

**Issue by jussisallinen** [TritonDataCenter/pkgsrc-legacy#371]
pdns shipped in pkgsrc 2016Q1 is out of date and warns about mandatory security update:

pdns[25751]: [ID 702911 daemon.error] PowerDNS Security Update Mandatory: Upgrade now, see https://doc.powerdns.com/md/security/powerdns-advisory-2015-03/

**Comment by mamash** [comment]
Thanks for the notice, I'll upgrade the pkgsrc package to the latest in trunk.

Is that really an 'error' I see there in the log, i.e. the binary refuses to even run?

**Comment by mamash** [comment]
Upstream trunk has been updated to 3.4.9. I'll make sure to backport to the LTS releases too (e.g. 2015Q4).

**Comment by mamash** [comment]
The 2015Q4 LTS packages were just bumped.
