### ISSUE TITLE
Please package nginx >= 1.10

### ISSUE THREAD

**Issue by allquixotic** [TritonDataCenter/pkgsrc-legacy#373]
Sometimes living on the bleeding edge of nginx releases comes with bugs and backwards compatibility problems, but at the same time, a lot of new features are being added to recent nginx. Some SmartOS users will want these new features.

Right now I see nginx 1.8.1 and 1.9.10 in the pkgsrc. This represents the old stable (1.8.x) and the old mainline (1.9.x), and 1.9.10 in particular is several minors off the latest minor release. The latest stable branch, however, is 1.10.x, and the latest mainline is 1.11.x. 

I like that SmartOS supports both nginx stable and nginx mainline, because stable is for those who don't want third-party modules to break when they update, and mainline is for those who want new features. But right now, especially mainline-1.9 is getting a little long in the tooth compared to 1.11.

**Comment by mamash** [comment]
Thanks, updated www/nginx to 1.10.1 and www/nginx-devel to 1.11.1, just in time for the pre-2016Q2 freeze.
