### ISSUE TITLE
mysql-server-5.6.28: my.cnf incorrectly placed in /opt/local instead of /opt/local/etc

### ISSUE THREAD

**Issue by peterkelm** [TritonDataCenter/pkgsrc-legacy#378]
When installing mysql-server-5.6.28 from Joyent pkgsrc (http://pkgsrc.joyent.com/packages/SmartOS/2015Q4) „my.cnf“ is placed in /opt/local instead of /opt/local/etc

Accordingly, /opt/local/my.cnf isn’t even looked at as it is not in one of the default locations. From  „mysqld —help“: „Default options are read from the following files in the given order: /etc/my.cnf /etc/mysql/my.cnf /opt/local/etc/my.cnf ~/.my.cnf“

**Comment by mamash** [comment]
Thanks, Peter. I committed a fix to upstream pkgsrc trunk today, so it will show up in 2016Q2.

The MySQL upstream intentionally uses $PREFIX ($basedir) as the right location for my.cnf. I patched that to play along with the pkgsrc expectations. (MySQL prior to 5.6 did not try to install any designated my.cnf file.)

**Comment by peterkelm** [comment]
Filip,

Thanks for the update. I’ll test it out when 2016Q2 becomes available.

Best regards,

Peter
