### ISSUE TITLE
Openldap server won't start after stopping

### ISSUE THREAD

**Issue by pmcx** [TritonDataCenter/pkgsrc-legacy#379]
Freshly installed smartos zone (088b97b0-e1a1-11e5-b895-9baa2086eb33  base-64-lts  15.4.1).
Installed openldap packages from joyent repository.

Openldap-server doesn't ship with smf manifest so I imported one. 
No changes in slapd.conf yet.
Imported smf and openldap started. Then I disabled service and re-enabled again. Service was in maintenance mode.
The file /var/openldap/openldap-data/lock.mdb blocked starting process. When I removed it, openldap started.

Same happened when started slapd process manually.

[openldap.xml.txt](https://github.com/joyent/pkgsrc/files/316506/openldap.xml.txt)
[openldap-installation.txt](https://github.com/joyent/pkgsrc/files/316511/openldap-installation.txt)

**Comment by benjamin-bergia** [comment]
Same issue here.
Tested on 2016Q1 and 2015Q4.

**Comment by mamash** [comment]
Thanks, looking at http://www.openldap.org/lists/openldap-bugs/201512/msg00042.html now.

**Comment by mamash** [comment]
This is the full bug report:

http://www.openldap.org/its/index.cgi/Incoming?id=8339;selectid=8339

**Comment by jperkin** [comment]
This is now resolved, including a new SMF manifest, with these upstream commits

http://mail-index.netbsd.org/pkgsrc-changes/2016/06/17/msg142430.html
http://mail-index.netbsd.org/pkgsrc-changes/2016/06/17/msg142431.html

I backported these patches to 2016Q1, look for the 'nb2' revisions of openldap-client and openldap-server.
