### ISSUE TITLE
sngl can't install ruby193-base package

### ISSUE THREAD

**Issue by bixu** [TritonDataCenter/pkgsrc-legacy#38]
[root@2adfc7b0-1eb0-4d8d-aeeb-5a2fc034f1c1 ~]# pkgin install ruby193-base
calculating dependencies... done.

nothing to upgrade.
2 packages to be installed: libyaml-0.1.4 ruby193-base-1.9.3p385 (6672K to download, 20M to install)

proceed ? [Y/n] Y
downloading packages...
ruby193-base-1.9.3p385 is not available on the repository
proceed ? [y/N]

**Comment by jperkin** [comment]
You need to do a 'pkgin update' first, the ruby package was recently updated to p392 and the p385 package no longer exists (though it's probably a bug that we delete obsolete packages, need to do more testing to verify there are no issues caused by us leaving them there).
