### ISSUE TITLE
ruby gems broken

### ISSUE THREAD

**Issue by brianewell** [TritonDataCenter/pkgsrc-legacy#381]
Instance: base-64-lts v15.4.1
Pkgin repo: 2015Q4/x86_64
Package: ruby22-2.2.4

The gem command fails to install gems, instead throwing the following exception:

`# gem install rails`
`ERROR:  Loading command: install (LoadError)`
`ld.so.1: ruby22: fatal: relocation error: file /opt/local/lib/ruby/2.2.0/x86_64-solaris2.11/openssl.so: symbol SSLv2_method: referenced symbol not found - /opt/local/lib/ruby/2.2.0/x86_64-solaris2.11/openssl.so`
`ERROR:  While executing gem ... (NoMethodError)`
`undefined method 'invoke_with_build_args' for nil:NilClass`

**Comment by brianewell** [comment]
Manually updating OpenSSL to 1.0.2h (from the default 1.0.2g) resolved this problem for me.

**Comment by mamash** [comment]
Good old erroneous auto-close by GitHub.

**Comment by mamash** [comment]
The proper fix should have been to bump the revision of ruby-base (and other packages consuming libssl/libcrypto), but we failed to do that last time OpenSSL was updated. I'm going to close this down now as doing it now would probably not be worth the effort. It was a one-time bug in the process.
