### ISSUE TITLE
Install https://github.com/joyent/sdc-nfs via pkgsrc

### ISSUE THREAD

**Issue by jacques** [TritonDataCenter/pkgsrc-legacy#383]
Seems to not install out of the box on SmartOS instances on Joyent.  Would be useful having this available for in pod deploys and rely on manta for filestore backups.

**Comment by mamash** [comment]
Sadly, npm apps/modules cannot be reliably packaged with pkgsrc.

Also, this builds & runs just fine for me, as long as you install gmake, gcc47/gcc49 and nodejs-0.10 which are required.
