### ISSUE TITLE
Please add dovecot-pgsql to latest dovecot2

### ISSUE THREAD

**Issue by TyrfingMjolnir** [TritonDataCenter/pkgsrc-legacy#385]
# cat /var/log/maillog | grep pgsql
2016-07-07T18:45:56+00:00 mta01 dovecot: [ID 583609 mail.crit] auth: Fatal: Unknown database driver 'pgsql'

**Comment by TyrfingMjolnir** [comment]
Tried to add +=pgsql
Appeared to compile just fine, with pgsql mentioned as enabled.
Package installed fine in a new zone.
Dovecot works, but pgsql does not work when installed in a new system.

There is no doveconf -m to show modules like postconf -m

**Comment by TyrfingMjolnir** [comment]
pgsql validates: # pkg_info -Q PKG_OPTIONS dovecot
gssapi ldap pam pgsql sqlite ssl tcpwrappers

FTR:
# pkgin list | grep dovec
dovecot-2.2.21nb1    Secure IMAP and POP3 server

**Comment by mamash** [comment]
I believe Jonathan added the option to 2016Q2, and I'm working on fixing this in trunk by splitting off dovecot-pgsql etc. packages, because enforcing a postgresql-client dependency on everyone is tough.

**Comment by TyrfingMjolnir** [comment]
There is an issue with the name

# ./sbin/dovecot --build-options
Build options: ioloop=poll ipv6 openssl io_block_size=8192
Mail storages: shared mdbox sdbox maildir mbox cydir imapc pop3c raw fail
SQL drivers: mysql postgresql sqlite
Passdb: checkpassword ldap pam passwd passwd-file shadow sql
Userdb: checkpassword ldap passwd prefetch passwd-file sql

The name is usually pgsql, here it says pgsql, but I finally got it working somehow.

Making separate builds is nice, will you build all of these?

dovecot-redis
dovecot-pgsql
dovecot-mysql
dovecot-ldap

What about 
dovecot-jdbc?

**Comment by jperkin** [comment]
Confirmed via IRC that enabling the 'pgsql' option does allow the postgresql backend to be used. This will be enabled by default in the 2016Q2 packages.
