### ISSUE TITLE
Unknown Puppet subcommand 'puppet21'

### ISSUE THREAD

**Issue by huncutek** [TritonDataCenter/pkgsrc-legacy#394]
Hi!
I installed ruby21-puppet-3.8.6 package from repository, but when I would like to run puppet command, I can see only:

`Error: Unknown Puppet subcommand 'puppet21'`

Even if I use correct subcomand, like `puppet help` or `puppet doc`.
Tried that on two OmniOS r151014 LTS fully updated with latest version of pkgin (2016Q2).
Thank you very much for any help.
Filip Marvan

**Comment by mamash** [comment]
This is fixed in trunk pkgsrc now and the fix will show up in 2016Q3.
