### ISSUE TITLE
libgcrypt-config --libs gives output incompatible with /usr/bin/ld

### ISSUE THREAD

**Issue by breiter** [TritonDataCenter/pkgsrc-legacy#400]
My Makefile contains `LIBS += $(shell libgcrypt-config --libs) $(CRYPTO_LDADD)` which normally works find. However with libgcrypt from pkgsrc on OS X 10.11 this fails.

```
cc  -L/opt/pkg/lib -o vpnc sysdep.o vpnc-debug.o isakmp-pkt.o tunip.o config.o dh.o math_group.o supp.o decrypt-utils.o crypto.o crypto-gnutls.o vpnc.o -L/opt/pkg/lib -Wl,-R/opt/pkg/lib -lgcrypt -lgpg-error -L/opt/pkg/lib -lgnutls  
ld: unknown option: -R/opt/pkg/lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [vpnc] Error 1
```

Issue is that `libgcrypt-config --libs` generates a `-Wl,-R/opt/pkg/lib` arguments for `ld` that doesn't work.

```
$ libgcrypt-config --libs
-L/opt/pkg/lib -Wl,-R/opt/pkg/lib -lgcrypt -lgpg-error
```

This patch fixes the problem:

```
--- libgcrypt-config.0  2016-08-23 01:06:32.000000000 +0200
+++ libgcrypt-config    2016-08-23 01:06:38.000000000 +0200
@@ -17,7 +17,7 @@
 version="1.7.2"
 includedir="${prefix}/include"
 libdir="${exec_prefix}/lib"
-gpg_error_libs="-Wl,-R/opt/pkg/lib -L/opt/pkg/lib -lgpg-error"
+gpg_error_libs="-L/opt/pkg/lib -lgpg-error"
 gpg_error_cflags="-I/opt/pkg/include"

 # libgcrypt values.
@@ -155,7 +155,7 @@

     # Set up `libdirs'.
     if test "x$libdir" != "x/usr/lib" -a "x$libdir" != "x/lib"; then
-   libdirs="-L$libdir -Wl,-R${exec_prefix}/lib"
+   libdirs="-L$libdir"
     fi

     # Set up `libs_final'.
```

However that file is generated from `src/ibgcrypt-config.in` I think by some M4 macro but I haven't figured out what goes wrong in the original build to generate a `libgcrypt-config` script that is incompatible with `/usr/bin/ld`.

**Comment by breiter** [comment]
@jperkin FYI. I don't think the "pttree script for printing HDF5 file contents as a pretty ASCII tree" in py-pytables has anything to do with this libgcyrpt issue.

**Comment by mamash** [comment]
Good old erroneous auto-close by GitHub.

**Comment by mamash** [comment]
The patch that introduced the hard coded -R search flag came through pkgsrc, but a smart $COMPILER_RPATH_FLAG wrapper should have been used instead that substitutes the proper flag as needed. I fixed this in upstream CVS today.
