### ISSUE TITLE
documentation or way to find out what options a binary package was compiled with?

### ISSUE THREAD

**Issue by jf** [TritonDataCenter/pkgsrc-legacy#404]
sorry if this has been asked before, but a quick search within the issues didn't reveal anything. As per subject, is there a way (documentation or otherwise) to find out what options a binary package was built with? This helps both in education (what was this package built with?), and in deciding whether or not to go with a source install instead.

**Comment by drscream** [comment]
Builds created by Joyent or @jperkin you could find more details in the following repository: https://github.com/joyent/pkgbuild

It contains details for the pkg options which are used on different releases and operating systems: https://github.com/joyent/pkgbuild/tree/master/include/pkgoptions

**Comment by jperkin** [comment]
There's pkgbuild as explained above which contains all the configs we use, or alternatively you can query an installed package to see which options it was built with using `pkg_info`, for example:

```
$ pkg_info -Q PKG_OPTIONS mutt
gpgme mutt-hcache mutt-smtp ncursesw sasl smime ssl tokyocabinet
```

You can use `pkg_info -B` to print out other bits of information about the package too.

**Comment by jf** [comment]
Great, thanks, guys. Thank you for the detail!
