### ISSUE TITLE
base-multiarch-lts 15.4.1 unzip-6.0nb6 and zip-3.0nb3 can't read zips >2G

### ISSUE THREAD

**Issue by jessegit** [TritonDataCenter/pkgsrc-legacy#409]
Both unzip -l 2Gfile.zip and zip -vT 2Gfile.zip fail.

Zip will happily create a file >2G.

**Comment by jperkin** [comment]
Fixed in http://mail-index.netbsd.org/pkgsrc-changes/2016/09/13/msg146417.html and will be available in 2016Q3. Thanks!
