### ISSUE TITLE
lmdb suffers from ITS#8339

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc-legacy#411]
http://www.openldap.org/lists/openldap-bugs/201512/msg00042.html

In short, this means that on illumos systems, the lmdb libraries will always consider an on-disk database to be corrupted.

The upstream commit that fixes this is http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=commit;h=21ed2bd4c939ac9516d14933eeb3130990df7cde

This should be backported to the 2015Q4 LTS release. Without it, openldap-server is completely broken.

**Comment by mamash** [comment]
Strange, I have a feeling of déjà vu about encountering this issue before, but I can't find any trace anywhere. I'll pursue a fix for this.

**Comment by jperkin** [comment]
I already fixed this in 6908691f8afc2711996aa3fe6529c7980e3c35ab which is backported to 2015Q4, so I'm a bit confused as to why this isn't working.

**Comment by jperkin** [comment]
Oh, hmm, something is wrong with my clone it seems, and this never got pushed:

```
$ git checkout joyent/release/2015Q4
Switched to branch 'joyent/release/2015Q4'
Your branch and 'origin/joyent/release/2015Q4' have diverged,
and have 11683 and 455 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
```

I'll fix this up.

**Comment by mamash** [comment]
OK, that explains why I couldn't find it.

**Comment by mamash** [comment]
Jonathan brought in the lost commit and the rebuild from Sep 22 should have fixed this, looked for a bumped openldap package in 2015Q4.
