### ISSUE TITLE
http2 broke in nginx

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc-legacy#414]
SmartOS, 2015Q4, updated from nginx-1.9.5nb1 to nginx-1.11.1.

```
nginx: [emerg] the "http2" parameter requires ngx_http_v2_module in /opt/local/etc/nginx/sites.d/200-zonena.me:2
```

**Comment by mamash** [comment]
This was caused by a strange git mismerge. I just requeued 2015Q4 with a fix, the bumped nginx package should have http2 included.

**Comment by mamash** [comment]
Please retry with nginx-1.11.1nb1 just published.
