### ISSUE TITLE
Get the content of a file into the SMF exec_method

### ISSUE THREAD

**Issue by benjamin-bergia** [TritonDataCenter/pkgsrc-legacy#418]
I am trying to get the graceful restart to work in my haproxy manifest. My current methods are: 
`<exec_method name='start' type='method' exec='/opt/local/sbin/haproxy -f /opt/local/etc/haproxy.cfg -D -p /var/run/haproxy.pid' timeout_seconds='60'/>`

`<exec_method name='stop' type='method' exec=':kill' timeout_seconds='60'/>`

`<exec_method name='refresh' type='method' exec='/opt/local/sbin/haproxy -f /opt/local/etc/haproxy.cfg -sf $(/usr/bin/cat /var/run/haproxy.pid)' timeout_seconds='60'/>`

I know that the environment used by exec is very limited and the `$(/usr/bin/cat ...` part doesn't seem to work properly. Is there any way to get the content from `/var/run/haproxy.pid` as an argument ?

**Comment by mamash** [comment]
No, you'd have to write a script for that and use it instead.

**Comment by benjamin-bergia** [comment]
Ok, thank you
