### ISSUE TITLE
pkgin repositories list in /opt/local/etc/pkgin/repositories.conf contains same pkgsrc URI twice

### ISSUE THREAD

**Issue by marcovl71** [TritonDataCenter/pkgsrc-legacy#42]
This occurs after creating a new joyent brand zone from both image_uuids ee1fb198-5fe1-11e2-9cce-e319fd47df7b (multiarch-12.4.1) and c91b3752-79c5-11e2-ad33-67667b9ee2c2 (trunk-0.99.0) on platform joyent_20130222T000747Z

http://pkgsrc.smartos.org/packages/SmartOS/2012Q4-multiarch/All listed twice on multiarch
http://pkgsrc.smartos.org/packages/SmartOS/trunk/All listed twice on trunk

**Comment by mamash** [comment]
This should no longer apply to any recent image.
