### ISSUE TITLE
Missing package: mongodb?

### ISSUE THREAD

**Issue by baskerville** [TritonDataCenter/pkgsrc-legacy#422]
I'm getting the following error message when trying to do a full upgrade:

```
pkgin: mongodb-3.2.9 has no associated repository
```

**Comment by jperkin** [comment]
There's currently an issue with the boost-libs upgrade which is masking the build of mongodb:

http://us-east.manta.joyent.com/pkgsrc/public/reports/Darwin/trunk/x86_64/20161022.1552/boost-libs-1.62.0/install.log

I'll take a look at fixing this.
