### ISSUE TITLE
watchman is broken (and old too)

### ISSUE THREAD

**Issue by jf** [TritonDataCenter/pkgsrc-legacy#423]
Broken:

It seems like some patch is in order somewhere (I haven't found the appropriate place to patch yet, or else I'd submit a patch), but running `watchman watch $SOMEDIR` causes

```
$ watchman watch /tmp
1477691528: tid=2012794880 unable to talk to your watchman on /Users/pbulk/build/sysutils/watchman/work/.destdir/var/run/watchman/jf!
```

It appears that watchman is taking a cue from its build directory (and hence the `/Users/pbulk/build/sysutils/watchman/work/.destdir` prefix)

Old:

watchman is currently at 4.7.0 (see https://github.com/facebook/watchman/releases), vs 3.1 in pkgsrc.

**Comment by mamash** [comment]
Yep, that broke in 2015 with an ill-formed substitution on the part of pkgsrc. I'll fix that and update the package too.

**Comment by jf** [comment]
Thanks, @mamash. I was painfully working my way through coming up with a working patch... but just realized that I could have simply gotten some clue from homebrew's own handling. If you're stuck, https://github.com/Homebrew/homebrew-core/blob/master/Formula/watchman.rb should come in handy (`--prefix` and `--enable-statedir` look great!)

**Comment by mamash** [comment]
I fixed the 3.1 package in upstream pkgsrc trunk now.

I'll keep this pending for the update. Upstream has stopped maintaining SunOS support and diverted greatly from keeping things portable, so SunOS/SmartOS compatibility has been lost. I'll see if there's hope of reconciling the conflicts.

**Comment by jf** [comment]
Thanks, @mamash. One question about SunOS/SmartOS: is the family officially supported? (I had the impression it was from http://pkgsrc.net/#platforms, and http://wiki.netbsd.org/pkgsrc/how_to_use_pkgsrc_on_solaris/#index3h1). If compatibility can't be fixed, what happens with regards to versioning? Will pkgsrc still use 3.1 in its tree... but Illumos et al use a separate tree with an older version?

**Comment by mamash** [comment]
I only intend to give it a fair try to fix SunOS support. Otherwise I'll just update and SunOS week lose watchman until somebody cares enough to dedicate the effort needed.

pkgsrc platform support doesn't by far mean that all its packages will build and work on all supported platforms.

F.
1. 10. 2016 v 7:18, jf notifications@github.com:

**Comment by mamash** [comment]
I made the update today, so 4.7.0 should hit the OS X packages in a few days.

There's just too much effort involved to make the code fully portable at this point:

https://github.com/facebook/watchman/issues/322
