### ISSUE TITLE
ruby193-puppet-0.25.5nb1 has /opt/csw prefix configured in /opt/local/lib/svc/method/svc-puppetmasterd instead of /opt/local

### ISSUE THREAD

**Issue by marcovl71** [TritonDataCenter/pkgsrc-legacy#43]
using http://pkgsrc.smartos.org/packages/SmartOS/2012Q4-multiarch/All
ruby193-puppet-0.25.5nb1 contains /opt/local/lib/svc/method/svc-puppetmasterd method file but it contains /opt/csw as the prefix instead of /opt/local
Said method file is being used in /opt/local/share/examples/ruby193-puppet/svc/puppetmasterd.xml as it's start and stop method

**Comment by mamash** [comment]
This is now OBE, as upstream pkgsrc was updated to 3.1.1 last month. I haven't tried that package yet, but it's an entire overhaul of the ancient 0.25.5 that was there before. The new version will part of the next package set (2013Q2) in early July, so let's focus on that (I'll try to test it soon).
