### ISSUE TITLE
Missing or wrong dependency with package Grace

### ISSUE THREAD

**Issue by jypelait** [TritonDataCenter/pkgsrc-legacy#432]
The installation of Grace fails and the error log gives this info:

_pkg_add: no pkg found for 'pdflib>=4.0.3nb16', sorry.
pkg_add: Can't install dependency pdflib>=4.0.3nb16
pkg_add: 1 package addition failed_

There isn't pdflib package available but there is package pdflib-lite. Should the dependency be that one?
For example thats marked as dependency when installing Grace via Homebrew.

**Comment by mamash** [comment]
Possibly.

The (full) pdflib package has a restrictive license that prohibits any redistribution. So the automated build system allows it to be used as a build time dependency, but will not upload it to any public repository.

**Comment by jypelait** [comment]
Okay, its understandable if license somehow restricts softwares distribution.
And I forgot to mention that I encountered this with macOS Sierra 10.12.1.

Is it possible to change the dependency from pdflib to pdflib-lite?

Actually the Grace itself doesn't really need the pdf* dependencies at all and as a workaround a user can install the grace with _$ pkg_add -f grace_ and it works. But I think its not a very functional way to do it... :)

**Comment by mamash** [comment]
After some testing, I changed the dependency to pdflib-lite today. Also updated grace to the latest (5.1.25). It may take a few days to hit the Darwin trunk package repository.
