### ISSUE TITLE
Path typo in https://pkgsrc.joyent.com/

### ISSUE THREAD

**Issue by jcea** [TritonDataCenter/pkgsrc-legacy#433]
In https://pkgsrc.joyent.com/ you say:

```
# vi /opt/pkg/etc/mk.conf.local
```

It should be 

```
# vi /opt/local/pkg/etc/mk.conf.local
```

You have to add the "local" path component.

**Comment by jperkin** [comment]
This isn't actually incorrect, we use different prefixes for different package sets.  `/opt/local` happens to be what we use on SmartOS (for historical reasons), but we use `/opt/pkg` on Darwin, etc.  Documentation specific to SmartOS should use `/opt/local` (and if it doesn't then that definitely is a bug) but for this example there is no correct path - it's merely showing how one can easily change package options.
