### ISSUE TITLE
No signature found

### ISSUE THREAD

**Issue by baskerville** [TritonDataCenter/pkgsrc-legacy#439]
I've tried to upgrade today and I ended up with 17 errors (one error for each package installation failure). The error message that appear in `pkg_install-err.log` repeated 17 times is:
```
pkg_add: unable to verify signature: No signature found
```

Setting `VERIFIED_INSTALLATION=never` doesn't help.

**Comment by baskerville** [comment]
In addition, there seem to be a major design flaw in `pkgin`: if `pkg_add` fails the removal of the previous version should be undone.

And since this isn't the case, 17 packages have been removed from my system, because of the `pkgin upgrade` failure.

**Comment by jperkin** [comment]
Could you give me an example package to test? Also is there anything else in the log? One of the known issues is if the system time is incorrect and thinks that the signature date is in the future it will fail.

**Comment by baskerville** [comment]
Here's the full log:
```
---Dec 03 21:34:04: removing youtube-dl-20161021.1...
---Dec 03 21:34:07: removing w3m-0.5.3nb18...
---Dec 03 21:34:08: removing vim-8.0.0021...
---Dec 03 21:34:11: removing py35-pip-8.1.2...
---Dec 03 21:34:13: removing poppler-utils-0.46.0...
---Dec 03 21:34:14: removing pkglint-5.4.10...
---Dec 03 21:34:14: removing nodejs-7.0.0...
---Dec 03 21:34:20: removing msmtp-1.6.5nb1...
---Dec 03 21:34:22: removing mpv-0.21.0...
---Dec 03 21:34:23: removing mercurial-3.9.2...
---Dec 03 21:34:23: removing mediainfo-0.7.81...
---Dec 03 21:34:24: removing ImageMagick-7.0.3.4...
---Dec 03 21:34:27: removing cmake-3.6.2nb1...
---Dec 03 21:34:33: removing vim-share-8.0.0021...
---Dec 03 21:34:36: removing poppler-0.46.0...
---Dec 03 21:34:36: removing py27-mercurial-3.9.2...
---Dec 03 21:34:39: installing vim-share-8.0.0086...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing poppler-0.48.0...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing py27-mercurial-4.0...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing youtube-dl-20161118...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing w3m-0.5.3.0.20161120...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing vim-8.0.0086...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing py35-pip-9.0.0...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing poppler-utils-0.48.0...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing pkglint-5.4.11...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing nodejs-7.2.0...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing msmtp-1.6.6...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing mpv-0.22.0...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing mercurial-4.0...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing mediainfo-0.7.90...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing ImageMagick-7.0.3.6...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:39: installing libuv-1.10.0...
pkg_add: unable to verify signature: No signature found
---Dec 03 21:34:40: installing cmake-3.7.0...
pkg_add: unable to verify signature: No signature found
```

I can, for example, install`yacas` successfully but installing `poppler` will fail and produce the aforementioned error.

**Comment by jperkin** [comment]
That's really odd, and I can't reproduce (I'm assuming this is Darwin from your previous bug reports but it's helpful to explicitly state for each bug report as we support lots of different OS/branches), e.g.:

```
$ pkgin in vim-share
calculating dependencies... done.

nothing to upgrade.
1 packages to be installed (6684K to download, 20M to install):

vim-share-8.0.0086

proceed ? [Y/n]
downloading packages...
vim-share-8.0.0086.tgz                                                        100% 6684KB   2.2MB/s   1.7MB/s   00:03
installing packages...
installing vim-share-8.0.0086...
pkg_install warnings: 0, errors: 0
reading local summary...
processing local summary...
marking vim-share-8.0.0086 as non auto-removable
```

or if I install manually via `pkg_add`:

```
$ pkg_add -U https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/vim-share-8.0.0086.tgz
$ echo $?
0
```

Is it possible there is something corrupting the downloads? Are you able to check `/var/db/pkgin/cache/vim-share-8.0.0086.tgz` on your host and see what file it is?  On the host I just tested on:

```
$ ls -l /var/db/pkgin/cache/vim-share-8.0.0086.tgz
-rw-r--r-- 1 root wheel 6844554 Dec  4 16:58 /var/db/pkgin/cache/vim-share-8.0.0086.tgz
$ shasum /var/db/pkgin/cache/vim-share-8.0.0086.tgz
8687ceafdded1acc72c8d5dde9cf18ef37840404  /var/db/pkgin/cache/vim-share-8.0.0086.tgz
```

A valid package should be an `ar(1)` archive of a tarball and the signature files, e.g.:

```
$ ar tv /var/db/pkgin/cache/vim-share-8.0.0086.tgz
rw-r--r--       0/0         13679 Nov 26 09:12 2016 +PKG_HASH
rw-r--r--       0/0           801 Nov 26 09:12 2016 +PKG_GPG_SIGNATURE
rw-r--r--       0/0       6829839 Nov 26 09:12 2016 vim-share-8.0.0086.tmp.tgz
```

Thanks.

**Comment by baskerville** [comment]
Yes, I'm on *Darwin*.

The `shasum` and `ar` outputs match.

But this fails:
```
$ pkg_add -U https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/vim-share-8.0.0086.tgz
SSL support disabled
SSL support disabled
pkg_add: Can't process https://pkgsrc.joyent.com:443/packages/Darwin/trunk/x86_64/All/vim-share-8*: Authentication error
pkg_add: no pkg found for 'https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/vim-share-8.0.0086.tgz', sorry.
pkg_add: 1 package addition failed
```

**Comment by jperkin** [comment]
Ah, you're still using the non-HTTPS package tools, in which case you'd need to use http:// (but should otherwise work ok).  As the shasum matches then you can just do `pkg_add  -U /var/db/pkgin/cache/vim-share-8.0.0086.tgz` for the purpose of this test.

Note that if you want to upgrade to the HTTPS-aware package tools then follow the "64-bit (upgrade)" link on https://pkgsrc.joyent.com/install-on-osx/ though this shouldn't be a factor in what we're currently debugging.

Thanks!

**Comment by baskerville** [comment]
```
$ pkg_add -v /var/db/pkgin/cache/vim-share-8.0.0086.tgz
pkg_add: unable to verify signature: No signature found
```

**Comment by jperkin** [comment]
Ok, thanks, that's just really odd. I'm going to have to have a think about what might be going wrong here and get back to you with some additional things to try.

**Comment by baskerville** [comment]
Thanks, I noticed that the `+PKG_GPG_SIGNATURES` files of the packages that don't work don't have a `Version: GnuPG v1` line while the ones that work do.

**Comment by jperkin** [comment]
Oh, great catch! Yes it appears as though they changed the output between gnupg 1.4.20 and 1.4.21 and the latter has been used to sign the most recent packages.

There was a change in netpgpverify's handling of signatures a while back, so could I ask you to follow the "64-bit (upgrade)" instructions on https://pkgsrc.joyent.com/install-on-osx/ to see if that fixes the problem? That would then explain why it works for me and not you.

**Comment by baskerville** [comment]
Unfortunately, the script failed quickly because there's no `bootstrap-trunk-x86_64-20161011-upgrade.tar.gz` in `https://pkgsrc.joyent.com/packages/Darwin/bootstrap-upgrade/`…

**Comment by jperkin** [comment]
Ugh, sorry, I uploaded it to the wrong directory. For now you can grab it directly from https://pkgsrc-us-east-1.joyent.com/packages/Darwin/bootstrap-upgrade/bootstrap-trunk-x86_64-20161011-upgrade.tar.gz or wait 30 mins for the other mirrors to catch up.

**Comment by baskerville** [comment]
It worked!

**Comment by jperkin** [comment]
Great, thanks for being so patient! We'll try to ensure upgrades are a bit more robust in future.

**Comment by baskerville** [comment]
Two comments regarding the upgrade script:
- `gpg --recv-keys 0x1F32A9AD` doesn't work, I have to specify a `--keyserver` to make it work.
- `gpg --verify ${UPGRADE_TAR}{.asc,}` works within most shells, but will not work within a shell script.
