### ISSUE TITLE
openssl doesn't compile

### ISSUE THREAD

**Issue by xmerlin** [TritonDataCenter/pkgsrc-legacy#44]
branch joyent/release/2012Q4

openssl doesn't compile

http://pastebin.com/dJW53fWV

**Comment by mamash** [comment]
That's another reason why the wiki page you're following doesn't mention 2012Q4 yet - the 'pk' repo comes with extra patches that do not work with openssl in 2012Q4. You can locally remove /opt/pk/patches/security/openssl and rebuild.

I'm sorry, I do not have plans to update pk for 2012Q4 - we stopped using it for 2012Q4, so we'll likely rewrite the docs to work with pkgsrc only (no extra repo), or maybe document how to use pbulk (what we use for automated package building).

-F
1. 3. 2013 v 22:38, Christian Zoffoli notifications@github.com:

**Comment by xmerlin** [comment]
ok ..is it "safe" to use pk to build things and/or to test some new packages=

**Comment by mamash** [comment]
Yes, it should be OK. I may revisit and just remove the biggest obstacles with 2012Q4, because I'm not sure how long it will take for the new docs to show up.

-F
1. 3. 2013 v 22:49, Christian Zoffoli notifications@github.com:

**Comment by xmerlin** [comment]
ok thank you, I'm rebuilding all ... I'll keep you posted

**Comment by xmerlin** [comment]
pk cannot create the openssl package --> http://pastebin.com/wgNJUhGG

**Comment by mamash** [comment]
Won't fix. Please use other approaches to build packages (rather than pk):

http://www.perkin.org.uk/posts/pkgsrc-on-smartos-zone-creation-and-basic-builds.html
http://www.perkin.org.uk/posts/distributed-chrooted-pkgsrc-bulk-builds.html
