### ISSUE TITLE
percona-server-5.7.14 DB wrong DB initialisation

### ISSUE THREAD

**Issue by infinity202** [TritonDataCenter/pkgsrc-legacy#441]
The Percona MySQL server installation uses the wrong database initialisation which results in an unusable database system, since no root password is generated. 

The installer generates the following warning: --bootstrap is deprecated. Please consider using --initialize instead 

While it uses the “—bootstrap” function to initialize the databases it skips the generation of a temporary root password in the /var/log/mysql/error.log file. 
After starting percona it is impossible to log in to the database. 

When I halt the percona db and remove the /var/mysql database directories and rerun the database initialisation with “mysqld --initialize --user=mysql --datadir=/var/mysql” it does generate the temporary root password in the logfile. 

Furthermore it would be nice that my.cnf is adjusted:

Remove bind-address = 127.0.0.1
Remove skip_name_resolve

Especially the last line, since the root user is inserted as root@localhost and not as root@127.0.0.1 , so even with the temporary password you can still not log in.

**Comment by mamash** [comment]
It is actually intended that no password is generated, which means you can log in without a password specified. That, together with the default localhost-only bind allows a user to deploy a MySQL instance in the cloud, configure it with automation tools without having to dig up random passwords in log files, yet not risk having the instance sniffed out on the public interface.

I am going to change the init sequence from legacy mysql_install_db to the new --initialize-insecure command nevertheless, as part of an update across the Percona packages.

**Comment by mamash** [comment]
The 2016Q4 package set already has an updated Percona 5.7 package with --initialize-insecure used instead of the old deprecated mysql_install_db. The rest of the initial setup remains in effect, as intended.
