### ISSUE TITLE
Fish shell

### ISSUE THREAD

**Issue by jackturnbull** [TritonDataCenter/pkgsrc-legacy#444]
Hello all, first off quick thanks for the good work - I've just got myself a new macbook and I've been looking for nice replacement to brew and I think this hits the mark! Thanks for providing a nice alternative!

I can see the fish shell is in [pkgsrc itself](http://pkgsrc.se/branch=pkgsrc-2016Q3/shells/fish) (although a little outdated) although I'm getting no hits for it within pkgin. Couldn't find the latest bulk build report to check the errors so unsure how much work this would take.

Possible to get a new build of this added to the Darwin repo, provided its not too much work?

**Comment by mamash** [comment]
The fish shell was recently updated to latest in pkgsrc. I just found a minor installation problem on Darwin and fixed it, so fish-2.5.0 should show up in the osx/trunk release in a couple of days.
