### ISSUE TITLE
Upgrading instructions and the version of pkgsrc

### ISSUE THREAD

**Issue by yb66** [TritonDataCenter/pkgsrc-legacy#446]
Hi,

I'm trying the [pkgsrc 64-bit upgrade](https://pkgsrc.joyent.com/install-on-osx/#64bit-upgrade) for Max OSX 10.9 and it says:

    # If you are upgrading from pkgsrc-2015Q[23] then use this upgrade kit first.  This
    # will switch you over to the trunk package repository.
    <snip>
    # Otherwise if you are upgrading from a previous trunk release use this kit

How would I know? `pkgin -v` gives me `pkgin 0.9.4 for Darwin-13.4.0 x86_64 (using SQLite 3.12.2)`. The trunk branch doesn't appear to have any tags so I'm wondering where I'd find out.

Regards,
iain

**Comment by jperkin** [comment]
You can use e.g.

```
$ tail -1 /opt/pkg/etc/pkgin/repositories.conf
```

or

```
$ grep PKG_PATH /opt/pkg/etc/pkg_install.conf
```

to see which repository you are using.  If using `trunk` then you can tell whether it's an older trunk kit as it will be using `http` rather than `https`.

**Comment by yb66** [comment]
Thank you.
