### ISSUE TITLE
Link to public key

### ISSUE THREAD

**Issue by yb66** [TritonDataCenter/pkgsrc-legacy#448]
Hi,

I had problems obtaining your public key from keyservers (GPG is such a friendly suite of programs;) and then had to really search around to find your public key in text format so that I could get rid of signing errors on install. I'd humbly suggest that it would be helpful to post a link to it on https://pkgsrc.joyent.com/, if only because that's a useful place to have it and cuts out any worries about getting the right one.

Thanks for all the work you put into this project, I'm finding it helpful.

Regards,
yb66

**Comment by jperkin** [comment]
Fixed, and making its way around the pkgsrc.joyent.com mirrors, thanks!
