### ISSUE TITLE
isc-dhcpd DLPI Open

### ISSUE THREAD

**Issue by goberle** [TritonDataCenter/pkgsrc-legacy#45]
The isc-dhcpd package get by pkgin in isc-dhcpd seem to not work in a zone.
On launch I get this error : Can't open DLPI device for net0: Is a directory.
I think it was trying to open /dev/net0 instead of /dev/net/net0.

I found a way to fix it quickly for my need:

In common/dlpi.c : 
l.133 : #define DLPI_DEVDIR "/dev/" 
need to be relplace by 
l.133 : #define DLPI_DEVDIR "/dev/net/"

and in the dlpiopen function
l.804 : while (cp < ep)
need to be replaced by
l.804 : while (cp <= ep)

**Comment by mamash** [comment]
Actually, this came up at Illumos before, and here's a better patch shown right at the top of the page:

http://echelog.com/logs/browse/illumos/1329606000

http://pastie.org/3410759

I'll integrate this into pkgsrc.

**Comment by goberle** [comment]
Oh great ! Thx for the patch :)

**Comment by mamash** [comment]
I backported the patch to 2013Q1 and the isc-dhc\* packages there were rebuilt (x86_64 build done, i386 build just finishing).
