### ISSUE TITLE
Landing page's OS X install instructions might miss sudo on "pkgin search "^ffmpeg[0-9]$"

### ISSUE THREAD

**Issue by neonsoftware** [TritonDataCenter/pkgsrc-legacy#450]
Hi, 

on ```OSX 10.10.5```, fresh install, following [pkgsrc.joyent.com/install-on-osx](https://pkgsrc.joyent.com/install-on-osx/), line ```pkgin search "^ffmpeg[0-9]$"``` fails to constructs database (apologies for not having saved the exact output), while it works if executed with ```sudo```. 

Is it a miss in the instructions page 📚 (which actually uses ```sudo```on all other commands after) or is there a real fresh install problem underneath ?

[loving the sw though 👍, great job]

**Comment by jperkin** [comment]
You'll need to perform an initial `pkgin update` using sudo to fetch the remote repository information and store it locally, but after that you should be able to use the search functionality as a normal user (root is only required to be able to write to `/var/db/pkg`).  I'll see about an extra update command to avoid this.

**Comment by neonsoftware** [comment]
Correct, `pkgin search` works without `sudo` afterwards. 
Great, if [pkgsrc.joyent.com/install-on-osx](https://pkgsrc.joyent.com/install-on-osx/) would include the update before the search, that would be seamless

**Comment by jperkin** [comment]
Fixed in https://github.com/joyent/pkgsrc.joyent.com/commit/ed1c9d44e55371727b609c24d1ef2031238c02ef, this will be live within the next 30 minutes.

**Comment by neonsoftware** [comment]
Super 👍  Have an outstanding day
