### ISSUE TITLE
macOS curl should be built with http2 by default also

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc-legacy#451]
And if not too outrageous, please back port to 2016Q4 LTS.

**Comment by jperkin** [comment]
This should have been done as part of SWSUP-567. If it didn't work properly let me know.

**Comment by bahamat** [comment]
Yep, you're right. I had tried it and got an error, but I tried it again just now and it worked. I must have accidentally used the platform curl.

Sorry for the noise, and thanks!

**Comment by bahamat** [comment]
Found it...It's the macOS build that doesn't have it.

```
% uname -v
Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64
% pkg_info -e curl
curl-7.52.1
% /opt/pkg/bin/curl -i --http2 https://www.joyent.com/
curl: (1) Unsupported protocol
```

Whereas on SmartOS:

```
$ cat /etc/product
Name: Joyent Instance
Image: base-64-lts 16.4.0
Documentation: https://docs.joyent.com/images/smartos/base
$ pkg_info -e curl
curl-7.52.1
$ /opt/local/bin/curl -is --http2 https://www.joyent.com/ | head -2
HTTP/2 200 
date: Mon, 16 Jan 2017 05:41:36 GMT
```

**Comment by mamash** [comment]
I see this was done last month, closing.
