### ISSUE TITLE
all packages under /packages/Linux/el6/trunk/x86_64/All/ un-installable

### ISSUE THREAD

**Issue by worr** [TritonDataCenter/pkgsrc-legacy#452]
All of the packages appear to be signed with a key id of 4735b9a256aaacaf, which is not the key id of the joyent pkgsrc key, and the repo does not include pkgsrc-gnupg-keys. I'm not able to (safely) install any of these packages.

From the title, this is rhel6 x86_64. There are other linux repos that do not have this problem, but they all have much older versions of packages.

**Comment by jperkin** [comment]
Yeh, I just need to publish the newer bootstraps which include the Linux PGP key. I'll try to do that today.

**Comment by jperkin** [comment]
This is going to take a little longer, and will require a full rebuild of the package sets, as I've just realised they were missing some `PKG_OPTIONS` settings. Once that's done I can generate the correct bootstraps.

**Comment by jperkin** [comment]
This was completed a while back with the release of the 20170127 bootstrap kits. Closing issue.
