### ISSUE TITLE
Upgrading openssl on OSX breaks pkgsrc

### ISSUE THREAD

**Issue by anadrome** [TritonDataCenter/pkgsrc-legacy#462]
Reproducible on a fresh install from bootstrap-trunk-x86_64-20161011.tar.gz, on Mac OSX El Capitan (10.11.6) as follows:

1. Install the bootstrap

2. pkgin update; pkgin upgrade (completes successfully)

````
2 packages to be upgraded:

pkgin-0.9.4nb3 sqlite3-3.14.2

2 packages to be installed (0B to download, 47K to install):

sqlite3-3.16.2 pkgin-0.9.4nb4
````

3. pkgin full-upgrade (fails, leaving pkgsrc in a broken state with dylib errors)

````
2 packages to be upgraded:

openssl-1.0.2jnb1 xz-5.2.2

2 packages to be installed (0B to download, 37K to install):

xz-5.2.3 openssl-1.0.2k
````

It seems what happens is that when pkgin attempts to upgrade openssl-1.0.2jnb1 to openssl-1.0.2k, the initial step of removing openssl-1.0.2jnb1 breaks all the pkgsrc tools:

````
---Feb 02 18:25:27: installing openssl-1.0.2k...
dyld: Library not loaded: /opt/pkg/lib/libssl.1.0.0.dylib
  Referenced from: /opt/pkg/sbin/pkg_add
  Reason: image not found
dyld: Library not loaded: /opt/pkg/lib/libssl.1.0.0.dylib
  Referenced from: /opt/pkg/sbin/pkg_info
  Reason: image not found
````

Subsequently nothing works until blowing away /opt/pkg and reinstalling from the bootstrap:

````
$ pkgin
dyld: Library not loaded: /opt/pkg/lib/libcrypto.1.0.0.dylib
  Referenced from: /opt/pkg/bin/pkgin
  Reason: image not found
Trace/BPT trap: 5
````

**Comment by jperkin** [comment]
Hmm, somehow that bootstrap kit has lost the statically linked OpenSSL libraries. Sorry, that sucks. I will try to get a replacement out ASAP. Until then a workaround would be to upgrade OpenSSL in place using 'pkg_add -U openssl', but I appreciate that's no good for systems that are already broken.

**Comment by jperkin** [comment]
The build host is currently in the middle of a bulk build and I will wait until that completes before issuing new bootstrap kits to ensure consistency.  In the meantime if you have a host which is affected by this, the workaround is:

```console
$ curl -O https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/pkg_install-20160410nb1.tgz

$ ar xv pkg_install-20160410nb1.tgz
x - +PKG_HASH
x - +PKG_GPG_SIGNATURE
x - pkg_install-20160410nb1.tmp.tgz

$ tar zxvf ../pkg_install-20160410nb1.tmp.tgz sbin
x sbin/audit-packages
x sbin/download-vulnerability-list
x sbin/pkg_add
x sbin/pkg_admin
x sbin/pkg_create
x sbin/pkg_delete
x sbin/pkg_info

$ mv sbin/pkg_* /opt/pkg/sbin/
```

That will install the statically linked `pkg_*` tools and should return you to a working state.

**Comment by jperkin** [comment]
This was completed a while ago with the release of the 20170205 kits.  Closing issue.
