### ISSUE TITLE
newer weechat need -lresolv on sunos too

### ISSUE THREAD

**Issue by nshalman** [TritonDataCenter/pkgsrc-legacy#464]
I was trying to compile weechat 1.7 manually in a SmartOS zone.
It wouldn't finish compiling until I did the equivalent of https://github.com/joyent/pkgsrc/commit/601b2d6091a6556fac7eb4a46c5ec667e5fa47b0

Didn't have time to test in pkgsrc but didn't want to forget.

**Comment by mamash** [comment]
Thanks, confirmed. I just applied that change to upstream trunk.

**Comment by nshalman** [comment]
Thanks @mamash. That's good enough for me. :)
