### ISSUE TITLE
varnish 3 is unsupported, should be updated to 4.1.5 (current)

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc-legacy#466]
And please include in 2016Q4.

**Comment by mamash** [comment]
Yes, I briefly tried, but 4.1.5 (and 5.0.0 for that matter) builds with errors and then most tests fail. I'll see where I can take this.

**Comment by mamash** [comment]
I got 4 & 5 close to working on SmartOS/x86_64 for the moment, hang on.

**Comment by mamash** [comment]
I added both varnish 4.1.5 and 5.0.0 to 2016Q4 today, both 32- and 64-bit branches. All test suites completely successfully. Right now the packages build from pkgsrc-wip, but I'll commit the changes into the main tree later on.
