### ISSUE TITLE
Missing Package: modular-xorg

### ISSUE THREAD

**Issue by Jaso-N7** [TritonDataCenter/pkgsrc-legacy#469]
Hi guys,

First off, great work, keep it up!
On to the subject matter, was this left out by mistake or removed on purpose? I am unable to find "modular-xorg" in the SmartOS/illumos 2016Q4 package listings, it is present in 2016Q3.

I still tried to get an X session started up regardless and I am getting the error "$DISPLAY is not set or cannot connect to the X server". Is there a workaround I can use in the meantime?

Regards

**Comment by jperkin** [comment]
It's currently being masked by the failure of "x11/xf86-video-ati6", I am looking to see if we can either fix that driver so it builds or remove it (it's been abandoned by upstream).

**Comment by Jaso-N7** [comment]
Sorry to hear that. I am grateful for the update though, I know you guys will figure out the best possible solution and am looking forward to it. I will revert to 2016Q3 in the meantime.

**Comment by jperkin** [comment]
I backported a fix from trunk so these packages are now available in 2016Q4.

**Comment by Jaso-N7** [comment]
Thank you so very much, I am updating right now. Keep up the amazing effort and work!
