### ISSUE TITLE
bash: words: bad array subscript

### ISSUE THREAD

**Issue by neatonk** [TritonDataCenter/pkgsrc-legacy#471]
There is a known bug in the bash-completion which causes the "bash: words: bad array subscript" error when bash completion is activated without have typed anything yet. 

This has been fixed elsewhere and a simple patch is available.

- https://bugs.launchpad.net/ubuntu/+source/bash-completion/+bug/1289597
- http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/bash-completion/trusty/view/45/debian/patches/words_bad_array_subscript.patch

Please let me know if you need any additional information.

**Comment by jperkin** [comment]
Thanks! I've committed this fix to pkgsrc trunk.
