### ISSUE TITLE
ups-nut missing ups-nut-usb

### ISSUE THREAD

**Issue by nahall** [TritonDataCenter/pkgsrc-legacy#472]
I have been using the ups-nut package under the SmartOS 2014Q2 pkgsrc bootstrap, and it has been working fine for 2 years with a cyberpower UPS connected over USB. Today I upgraded to the 2016Q4 bootstrap and was reinstalling packages and now ups-nut is missing /opt/tools/libexec/nut/usbhid-ups. 

Looking upstream, it looks like they separated the package out so now that is contained in ups-nut-usb, and I see that SmartOS had the ups-nut-usb package in pkgsrc in 2016Q1, but for some reason it was removed in 2016Q4. Can it be put back in the 2016Q4 repository? Thanks.

**Comment by jperkin** [comment]
This was already available in the main repos, so I guess you mean the tools set - I've added it, along with the `-cgi` and `-snmp` packages, and they should be available now.

**Comment by nahall** [comment]
Yes, you were right, I'm using the tools repos in the global zone (needed to be in the global zone because of the UPS). Thanks for adding it!
