### ISSUE TITLE
mpv in Darwin 2015Q3 but not in trunk

### ISSUE THREAD

**Issue by melloc** [TritonDataCenter/pkgsrc-legacy#475]
The `mpv` package shows up in Darwin [2015Q3](https://pkgsrc.joyent.com/packages/Darwin/2015Q3/x86_64/All/), but not in [trunk](https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/). I don't know if this is because the build started failing, or something else.

**Comment by jperkin** [comment]
This failed on the most recent build, I'll get it fixed for the next update.

**Comment by mamash** [comment]
mpv shows as available in trunk now
