### ISSUE TITLE
[Hipster] Fluxbox is an ancient version - 1.3.2

### ISSUE THREAD

**Issue by willbprog127** [TritonDataCenter/pkgsrc-legacy#479]
Greetings and thank you for pkgsrc!

The most currently available Fluxbox is 1.3.7, however the version in pkgsrc is extremely old (`Fluxbox 1.3.2 : (c) 2001-2011 Fluxbox Team`).

Is there any chance at updating this?

Thank you! :-)

**Comment by jperkin** [comment]
As it happens this was updated last month, and will be in the 2017Q1/17.1.x release due in the next week or so.

**Comment by willbprog127** [comment]
@jperkin Thank you :-)
