### ISSUE TITLE
trunk image does not honour resolvers = [ "1.2.3.4", "5.6.7.8"  ]

### ISSUE THREAD

**Issue by jessegit** [TritonDataCenter/pkgsrc-legacy#48]
creating a new zone with
    vmadm create <<EOF
    {
      "alias": "test"
      ,"hostname": "test"
      ,"zfs_root_compression": "on"
      ,"autoboot": false
      ,"brand": "joyent"
      ,"dataset_uuid": "c91b3752-79c5-11e2-ad33-67667b9ee2c2"
      ,"max_physical_memory": 4096
      ,"max_swap": 65536
      ,"quota": 42
      ,"dns_domain": "company.com"
      ,"resolvers": [ "1.2.3.4", "8.8.8.8" ]
      ,"nics": [
        {
          "nic_tag": "nat0"
          ,"ip": "176.16.0.2"
          ,"netmask": "255.240.0.0"
          ,"gateway": "172.16.0.1"
          ,"primary": true
        }
      ]
    }
    EOF

sets resolv.conf to
    nameserver 8.8.8.8
    nameserver 8.8.4.4

**Comment by mamash** [comment]
Irrelevant to pkgsrc.
