### ISSUE TITLE
[SmartOS] Installing collectd with bootstrap-2016Q4-tools

### ISSUE THREAD

**Issue by jjlawren** [TritonDataCenter/pkgsrc-legacy#481]
Looks like the collectd* packages are not included in the minimal tools release. Seems like other monitoring-style packages are included such as apcupsd, cacti, smartmontools, and ups-nut*. Would it be possible to include collectd in the tools release?

**Comment by jperkin** [comment]
I've added these to the tools list, and they are available in the 2017Q1 repository.  I'll push them to the 2016Q4 repository too shortly.
