### ISSUE TITLE
Zero MQ is linked against wrong stdc (?)

### ISSUE THREAD

**Issue by RantyDave** [TritonDataCenter/pkgsrc-legacy#487]
Specifically that when pyzmq-16.0.2 tries to link against it fails with:

```
gcc -m64 build/temp.solaris-2.11-i86pc.64bit-3.6/scratch/vers.o -L/opt/local/lib -Wl,-R/opt/local/lib -lzmq -o build/temp.solaris-2.11-i86pc.64bit-3.6/scratch/vers

    Undefined                   first referenced
     symbol                         in file

    ceil                                /opt/local/lib/libzmq.so
    std::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const /opt/local/lib/libzmq.so
    std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /opt/local/lib/libzmq.so
    std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, unsigned long) /opt/local/lib/libzmq.so
    std::ios_base::ios_base()           /opt/local/lib/libzmq.so
    std::ios_base::~ios_base()          /opt/local/lib/libzmq.so
```

Which looks very much like linking against stdc and not stdc++.

Building from source (zeromq-4.2.2 with `pkgin libsodium`), config:

`./configure --with-libsodium --prefix=/opt/local`

...then running `pip3.6 install pyzmq` works just fine.

**Comment by mamash** [comment]
Just guessing you found this in 2017Q1/x86_64? We hit this earlier in the 2017Q1/tools package set and I just realized two days ago it affected the x86_64 package set as well. It will auto-correct with the next rebuild and that's when py-zmq will successfully build too as a package.

For some reason, with the initial 2017Q1 build the zeromq package built with *no* libgcc/libstdc++ runtime linking at all.

**Comment by RantyDave** [comment]
No stdc at all? That's quite impressive - almost like making antimatter. I'll click "close" then :)

**Comment by mamash** [comment]
I ran a rebuild earlier today and 2017Q1/x86_64 should be all good now.
