### ISSUE TITLE
keychain needs to be run with bash

### ISSUE THREAD

**Issue by jclulow** [TritonDataCenter/pkgsrc-legacy#488]
In image `base-multiarch-lts 16.4.1`, it appears that `keychain` has the wrong interpreter line.  It uses `/bin/sh`, but that's `ksh93` and the script has some `bash`-isms like `local`.  I think this is related to, or a regression of, joyent/pkgsrc#190?

**Comment by jperkin** [comment]
Yeh, our change was reverted.  I've put it back with some additional comments, and will backport this to 2016Q4.

**Comment by jperkin** [comment]
This is now available as `keychain-2.8.3nb1`.
