### ISSUE TITLE
Update CouchDB to 1.3.0

### ISSUE THREAD

**Issue by mmalecki** [TritonDataCenter/pkgsrc-legacy#49]
Newest release is CouchDB 1.3.0. Would be great to be able to use that on Joyent.

**Comment by jperkin** [comment]
This is done - http://mail-index.netbsd.org/pkgsrc-changes/2013/04/24/msg088329.html

Packages will be available in pkgsrc-2013Q2 (image version 13.2.x)

**Comment by mmalecki** [comment]
Thank you, Jonathan!
