### ISSUE TITLE
IPerf3 missing from SmartOS GZ tools

### ISSUE THREAD

**Issue by Smithx10** [TritonDataCenter/pkgsrc-legacy#491]
While trying to debug network speeds, I ran into the fact that the SmartOS GZ Tools don't have iperf3.

**Comment by jperkin** [comment]
This (and version 2) is now available in 2016Q4. Only v2 is available in 2017Q1 at present, I'm looking into a build issue with iperf3 for that repository now.

**Comment by jperkin** [comment]
This was all done last week.
