### ISSUE TITLE
[want] watch in gz-tools

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/pkgsrc-legacy#494]
Sometimes I want to watch something form the gz, we have watch inside zones from the GNU world.
It would be nice to have in the gz too.

```while [ 1 ]; do XXX && sleep N ; done```

Is just not the same, especially the lack of '-d' in that one :)

**Comment by mamash** [comment]
Added to 2017Q1/tools just now.

**Comment by mamash** [comment]
The 2016Q4 tool set will update with the next 2016Q4 rebuild.
