### ISSUE TITLE
Want sysutils/ddrescue added to SmartOS GZ tools set

### ISSUE THREAD

**Issue by dcarosone** [TritonDataCenter/pkgsrc-legacy#495]
Recovering disks with media errors works well with zfs, but not always with some disks that like to hang or otherwise misbehave when accessing bad areas.  Decoupling the zfs recovery from the physical disk by imaging with ddrescue is useful.

(redirected from https://github.com/joyent/rfd/commit/89c291c64c2fd38cdd90d3aac18abd660a6ad6f4#commitcomment-21777391)

**Comment by mamash** [comment]
Added to 2017Q1/tools just now.

**Comment by mamash** [comment]
The 2016Q4 tool set will update with the next 2016Q4 rebuild.
