### ISSUE TITLE
SmartOS GZ tools has ansible, should be ansible2

### ISSUE THREAD

**Issue by dcarosone** [TritonDataCenter/pkgsrc-legacy#496]
(alternately, this might be better done by just moving ansible2 -> ansible; I'm not really sure why they're separate in pkgsrc.  I strongly doubt anyone still wants the older version)

**Comment by mamash** [comment]
Added to 2017Q1 just now.

**Comment by mamash** [comment]
The 2016Q4 tool set will update with the next 2016Q4 rebuild.
