### ISSUE TITLE
pkgin needs to return nonzero exit status on search failure

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#50]
Currently, pkgin se behaves as follows:

root at 6c4c79d6-ac48-11e2-a228-bb5fd3fe0c7b in ~
# pkgin se no-such-pkg

No results found for no-such-pkg
root at 6c4c79d6-ac48-11e2-a228-bb5fd3fe0c7b in ~
# echo $?

0

The same zero exit status is provided when the search succeeds.  This makes it difficult to detect whether the package exists in the repo, and impossible to do so in a Stable fashion since the human-readable output format may change.  The correct behaviour is to exit with some (any, really) non-zero exit status when a matching package is not found in the repository.

**Comment by iMilnb** [comment]
Noted, I'll fix this, thanks for the report!

**Comment by iMilnb** [comment]
This issue is fixed in github master branch, I'll make it available as pkgin 0.6.3.2 real soon.

**Comment by mamash** [comment]
Fixed in 2013Q2 pkgin.
