### ISSUE TITLE
Cherrypick lang/go mmap patch...

### ISSUE THREAD

**Issue by sean-** [TritonDataCenter/pkgsrc-legacy#504]
We should cherrypick the mmap(2) patch that officially landed in Go.

We should replace the contents of https://github.com/joyent/pkgsrc/blob/trunk/lang/go/patches/patch-src_runtime_mem__bsd.go with https://github.com/golang/go/commit/13cdd814ea0e8ef165ab54802f9f102b8b690df7

CC @jperkin

**Comment by mamash** [comment]
Sean, I made this change per your suggestion earlier:

https://github.com/jsonn/pkgsrc/blob/trunk/lang/go/patches/patch-src_runtime_mem__bsd.go

Is it the same fix and will it work until we hit 1.9? I cherry-picked that change over to 2016Q4.

**Comment by sean-** [comment]
@mamash It's *slightly* different in that `_EAGAIN` doesn't exist on the BSDs.  The patch that is in place works just fine for Illumos, but I'd rather track what's been officially upstreamed because it's been verified in the official Go test environment.

https://github.com/golang/go/commit/13cdd814ea0e8ef165ab54802f9f102b8b690df7#diff-0551b4988cf924970084df57358d1181R62

**Comment by mamash** [comment]
OK cool, I'll align the patch and make note to drop it with 1.9.

**Comment by sean-** [comment]
It looks like this was done in d26605e9d97bae77bdac8c40d47d99ac739df64f, thanks @mamash
