### ISSUE TITLE
[darwin] fontconfig 2.12.1

### ISSUE THREAD

**Issue by baskerville** [TritonDataCenter/pkgsrc-legacy#506]
There's a [nasty bug](https://bugs.freedesktop.org/show_bug.cgi?id=97546) in *fontconfig 2.12.1*.

It would be great to patch *2.12.1* or to provide a way to downgrade to *2.12.0*.

**Comment by jperkin** [comment]
Fixed in pkgsrc [here](http://mail-index.netbsd.org/pkgsrc-changes/2017/05/30/msg157518.html), this will make its way into OSX packages over the next week.

**Comment by baskerville** [comment]
Great.
