### ISSUE TITLE
[darwin] Missing package: gtk3

### ISSUE THREAD

**Issue by baskerville** [TritonDataCenter/pkgsrc-legacy#508]

**Comment by jperkin** [comment]
Currently blocked on [libepoxy](http://us-east.manta.joyent.com/pkgsrc/public/reports/Darwin/trunk/x86_64/20170525.1631/libepoxy-1.4.1/install.log) failure.

**Comment by mamash** [comment]
Just checked and this seems to have been resolved meanwhile.
