### ISSUE TITLE
Test net/mosh 1.3.1rc2

### ISSUE THREAD

**Issue by sean-** [TritonDataCenter/pkgsrc-legacy#509]
There were a few portability fixes that went into mosh after 1.3.0 as part of mobile-shell/mosh#875 .  Can we get a test build of mosh 1.3.1rc2 before mosh kicks out a release on their end?  Ideally this build will work when we hit our next quarterly release.

**Comment by mamash** [comment]
The build of 1.3.1rc2 succeeds, not all the bundled tests finish properly though. But those didn't even with 1.2.6 so probably not a big deal.

Anythign specific I should be looking for?

**Comment by sean-** [comment]
Does it work?  If there's a pkg someplace I'll pull it down and give it a quick twirl.  There was a slight irritation where the motd would be printed twice on login (and some other termios sync issue where the session would get out of sync).

**Comment by mamash** [comment]
I was able to connect, didn't go further. I'll give you a binary, just hang on for a bit.

**Comment by mamash** [comment]
To be used on a 2016Q4 VM:

```pkg_add http://us-east.manta.joyent.com/Joyent_Dev/public/bits/mosh-1.3.1rc2.tgz```

**Comment by sean-** [comment]
I'm using this now and it looks good, thank you!  Some of the terminal sync quirks that I would occasionally run into with the previous version seem to be gone, too.  Thanks!
