### ISSUE TITLE
pkgin happily exits with status 0 when asked to install nonexistent package

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#51]
Similar to #50, pkgin also exits with 0 status when asked to install a nonexistent package.
# pkgin in no-such-pkg

no-such-pkg is not available on the repository
calculating dependencies... done.
nothing to do.
root at ba48f39e in ~/git/smartos-live/projects/illumos-extra/perl/perl-5.12.3-32strap on master
# echo $?

0

This needs to exist with nonzero status since it failed to do what was requested.  Indeed, if any listed package fails to install for any reason, a nonzero exit status is warranted.

**Comment by iMilnb** [comment]
Fixed on github, will be part of next release. Thanks for pointing this out!

**Comment by mamash** [comment]
Fixed in 2013Q2 pkgin.
