### ISSUE TITLE
Upgrade netatalk

### ISSUE THREAD

**Issue by konobi** [TritonDataCenter/pkgsrc-legacy#52]
Current netatalk version in 2013Q1 is netatalk-2.2.1nb11 which is a couple of years old now. Can we get an upgrade to version 3.0.3 please?

There is now more specific solaris functionality:

./configure --with-bdb=/opt/local --with-init-style=solaris --with-init-dir=/var/svc/manifest/network/ --prefix=/opt/local

Thanks!

**Comment by mamash** [comment]
Erroneous Github auto-close.

**Comment by mamash** [comment]
We do carry netatalk-3.1.x since 2013Q4 now.
