### ISSUE TITLE
No signature found on 32-bit install

### ISSUE THREAD

**Issue by galgot** [TritonDataCenter/pkgsrc-legacy#529]
Hi,
I have the same problem as here :
[issue #439](https://github.com/joyent/pkgsrc-legacy/issues/439)
But on a Mac OSX 10.6 , 32-bit installation,
with bootstrap-trunk-i386-20160509.tar.gz.
I get :

> pkg_add: unable to verify signature: No signature found

for any installation I try.
None of the solutions on issues #439 thread linked above works for me.

any ideas ?

**Comment by jperkin** [comment]
I'm going to be producing a new 32-bit install kit once the current build has completed, which will resolve these issues.

**Comment by galgot** [comment]
Thanks .

**Comment by jperkin** [comment]
I've released a new 20171120 bootstrap kit which should resolve all outstanding issues.

**Comment by galgot** [comment]
Works fine now. Thank you.
