### ISSUE TITLE
pkgin install mysql-server-5.5 before client will install incompatible mysql-client-5.6

### ISSUE THREAD

**Issue by kevpie** [TritonDataCenter/pkgsrc-legacy#55]
2013Q1 on SmartOS 13.1.0 image.

mysql-server-5.5 fails to install and run with mysql-client-5.6.

Show server versions

```
[root@localhost ~]# pkgin se mysql-server    
mysql-server-5.5.30  MySQL 5, a free SQL database (server)
mysql-server-5.1.67nb1  MySQL 5, a free SQL database (server)
mysql-server-5.0.96nb1  MySQL 5, a free SQL database (server)

=: package is installed and up-to-date
<: package is installed but newer version is available
>: installed package has a greater version than available package
```

Show client versions

```
[root@localhost ~]# pkgin se mysql-client
mysql-client-5.6.10  MySQL 5, a free SQL database (client)
mysql-client-5.5.30  MySQL 5, a free SQL database (client)
mysql-client-5.1.67nb1  MySQL 5, a free SQL database (client)
mysql-client-5.0.96nb2  MySQL 5, a free SQL database (client)

=: package is installed and up-to-date
<: package is installed but newer version is available
>: installed package has a greater version than available package
```

Show pkgin intending to install 5.6 client as dependency for 5.5 server

```
[root@localhost ~]# pkgin in mysql-server-5.5
calculating dependencies... done.

nothing to upgrade.
2 packages to be installed: mysql-client-5.6.10 mysql-server-5.5.30 (0B to download, 219M to install)
```

Several problems were encountered under this senario.  Simply installing the 5.5 client before the 5.5 server was the work around.

Symptoms experienced were.
A. pkgin in mysql-server-5.5 reported missing my-default.cnf file.
pkgin in mysql-server-5.5.30 complains with

```
"FATAL ERROR: Could not find my-default.cnf"
```

after resolving A by copying my-small.cnf to my-default.cnf the following also happened.

B. mysql failed to start due to missing 'mysql.host' table. 
as well as mysql entering maintenance mode.

```
[ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.host' doesn't exist
```

Possible Recommendation:
Exclude 5.6 and higher from  mysql-server-5.5 and mysql-client-5.5 compatible pkgin versions.

**Comment by mamash** [comment]
I rebuilt the packages yesterday, fixing the loose dependency pattern. There's a new rebuild in progress right now that adds SMF support for mysql-server-5.6, too.
