### ISSUE TITLE
Recent libevent update breaks memcached

### ISSUE THREAD

**Issue by stevenwilliamson** [TritonDataCenter/pkgsrc-legacy#560]
`pkgin in libevent-2.1.8nb1` results in memcached failing due to it relying on an older libevent at least on 2015Q4/2016Q4

```
ld.so.1: memcached: fatal: libevent-2.0.so.5: open failed: No such file or directory
```

**Comment by mamash** [comment]
I'm sorry about that, I missed the lib version update in libevent in the previous backport. I just ran a recursive revbump in 2016Q4 and 2015Q4, can you update your packages? The problem should be gone.
