### ISSUE TITLE
couldn't install Minix3 in VirtualBox

### ISSUE THREAD

**Issue by sowbhagya4u** [TritonDataCenter/pkgsrc-legacy#569]
When I try to run
pkgin update

VM screen is stuck at 100%. Could not proceed further.
![Screenshot 2022-11-17 002241](https://user-images.githubusercontent.com/102467754/202363056-a078fbd9-4b17-46a1-b5fa-aa0972fec8e8.jpg)

![image](https://user-images.githubusercontent.com/102467754/202362880-d1faa916-7fac-4fc0-a69b-8e9b145f748e.png)

**Comment by jperkin** [comment]
At this point Minix is dead, and the last release ships an incredibly old version of pkgin. There's not really much anyone can do about this.
