### ISSUE TITLE
[Update Request] Update DNSMasq to latest. v2.64 does not cache DNS due to bug

### ISSUE THREAD

**Issue by exabrial** [TritonDataCenter/pkgsrc-legacy#57]
Hello everyone :) Just a request to please update DNSMasq to the latest available (v2.66 at the time of the writing). The currently available version v2.64 from pkgin contains a bug where DNSMasq actually performs no DNS caching, which defeats the purpose of DNSMasq. 

Source: http://www.thekelleys.org.uk/dnsmasq/CHANGELOG

**Comment by rmustacc** [comment]
See https://github.com/joyent/pkgsrc/issues/56.

**Comment by exabrial** [comment]
My Bad, thank you!!
