### ISSUE TITLE
R has done itself a mischief with LD_LIBRARY_PATH in base:13.1.0

### ISSUE THREAD

**Issue by jclulow** [TritonDataCenter/pkgsrc-legacy#58]
I installed the `R` package using `pkgin` in a `base 13.1.0` image...

```
[root@test0 ~]# sm-summary | grep ^Image
Image               base 13.1.0
[root@test0 ~]# pkgin list | grep ^R
R-2.15.1nb2          Statistical language for data analysis and graphics
```

Unfortunately, it doesn't seem to work:

```
[root@test0 ~]# R
ld.so.1: R: fatal: libgcc_s.so.1: version 'GCC_4.5.0' not found (required by file /opt/local/gcc47/i386-sun-solaris2.11/lib/./libgfortran.so.3)
ld.so.1: R: fatal: libgcc_s.so.1: open failed: No such file or directory
Killed
```

Digging in, it looks like the RPATH _is_ correctly set during the build:

```
[root@test0 ~]# elfdump /opt/local/lib/R/bin/exec/R  | grep RPATH
       [7]  RPATH             0x402               /opt/local/gcc47/i386-sunsolaris2.11/lib/.:/opt/local/gcc47/lib/.:/opt/local/lib:/opt/local/lib/R/lib
```

It appears that R is doing something foolish with `LD_LIBRARY_PATH` as a result of the file `/opt/local/lib/R/etc/ldpaths`, which gets sourced somewhere in the process of starting the program.  If I truncate this file, R works again (at least trivially.)

**Comment by mamash** [comment]
This is no longer an issue in 2013Q2.
