### ISSUE TITLE
expat missing /lib/64 libs

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#6]
running in an oi_151a7 minimal zone, certain packages reclaim libexpat.so, but it seems to be missing some pieces parts...

```
root@devzone:~# pkgin in expat
calculating dependencies... done.
/usr/lib/64/libexpat.so.1, needed by expat-2.1.0 is not present in this system.

nothing to upgrade.
nothing to install.
root@devzone:~# pkgin pc expat
Information for http://pkgsrc.smartos.org/packages/illumos/2012Q3/All/expat-2.1.0.tgz:
Files:
/opt/pkg/bin/xmlwf
/opt/pkg/include/expat.h
/opt/pkg/include/expat_external.h
/opt/pkg/lib/libexpat.la
/opt/pkg/lib/libexpat.a
/opt/pkg/lib/libexpat.so
/opt/pkg/lib/libexpat.so.1
/opt/pkg/lib/libexpat.so.1.6.0
/opt/pkg/lib/pkgconfig/expat.pc
/opt/pkg/man/man1/xmlwf.1
/opt/pkg/share/doc/html/expat/reference.html
/opt/pkg/share/doc/html/expat/style.css
root@devzone:~# pkgin update
database for http://pkgsrc.smartos.org/packages/illumos/2012Q3/All is up-to-date

```

**Comment by mamash** [comment]
Let me confirm with jperkin, I've had a patch for this (the package is actually not missing anything, it's just an erroneous reference in the meta information). You should still be able to install the package with 'pkg_add expat', but pkgin adds an extra level of checks.

**Comment by ghost** [comment]
ok, thanks. the following seemed to do the trick (by the way, I was in the process of trying exactly this to see):

```
root@devzone:~# pkg_add http://pkgsrc.smartos.org/packages/illumos/2012Q3/textproc/expat
```

**Comment by ghost** [comment]
just a sidenote, this seems to have messed up pkgin royally.  can't update any more.
tried a pkg_admin rebuild then tried again:

```
richard@devzone:~$ sudo pkgin update     
^C
richard@devzone:~$ ping free.fr
free.fr is alive
richard@devzone:~$ sudo pkgin update
^C
richard@devzone:~$ sudo pkgin update -v
^C
richard@devzone:~$ sudo pkg_admin rebuild 

Stored 18731 files and 3 explicit directories from 200 packages in /var/opt/pkg/db/pkg/pkgdb.byfile.db.
Done.
richard@devzone:~$ sudo pkgin update
reading local summary...
processing local summary...
updating database: 100%

```

and seems to hang... but completes after a long long while (updated).

**Comment by mamash** [comment]
Hm that's odd, because there is absolutely nothing non-standard about using pkg_add. In fact, the pkg_\* tools are native to pkgsrc, whereas pkgin is 3rd party (and pkgin itself calls onto pkg_\* tools to do its job). Sounds like an unrelated pkgin mischief, can you try 'pkgin -f update'? Worst case, you can always 'rm /var/opt/pkg/db/pkgin/pkgin.db' and let it refresh again, you won't lose anything that way.

**Comment by mamash** [comment]
Fixed a long time ago.
