### ISSUE TITLE
php53-ffmpeg fails to load

### ISSUE THREAD

**Issue by kevpie** [TritonDataCenter/pkgsrc-legacy#60]
Tested in 13.1.0 base64 SmartOS machine and on Manta.

Steps to reproduce.
Login using the Manta login shell `mlogin` and try to load the extension.

```
<user>@manta # php -dextension=ffmpeg.so -i
ld.so.1: php: fatal: relocation error: file /opt/local/lib/php/20090630/ffmpeg.so: symbol avcodec_init: referenced symbol not found
Killed
```

**Comment by mamash** [comment]
I committed a fix into upstream pkgsrc. Should be resolved with the next rebuild of 2013Q3/2013Q4.
