### ISSUE TITLE
Upgrade `ffmpeg` to 2.0

### ISSUE THREAD

**Issue by mmalecki** [TritonDataCenter/pkgsrc-legacy#65]
ffmpeg 2.0 was released [recently](http://www.ffmpeg.org/download.html#release_2.0).

**Comment by wclr** [comment]
Currently installed version is 0.7.8, that is more than 2 years old, many media standards and functions unsupported or work improperly.

**Comment by peteryorke** [comment]
Filip can comment on 2.0 availability but the Joyent pkgsrc is up to 1.2

http://pkgsrc.joyent.com/packages/SmartOS/2013Q1/i386/All/ffmpeg-20130315.1.2.tgz

On Fri, Jul 26, 2013 at 8:40 AM, Alex Osh notifications@github.com wrote:

> Currently installed version is 0.7.8, that is more than 2 years old, many
> media standards and functions unsupported or work improperly.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joyent/pkgsrc/issues/65#issuecomment-21628703
> .

## 

Peter Yorke
Joyent Cloud / node.js
pyorke@joyent.com
www.joyentcloud.com

**Comment by wclr** [comment]
How's it going with that issue?

**Comment by mamash** [comment]
ffmpeg 2 will be part of the 2013Q3 package set (in the works ATM).
