### ISSUE TITLE
nginx misses smf manifest

### ISSUE THREAD

**Issue by Licenser** [TritonDataCenter/pkgsrc-legacy#69]
in 13.2.0 nginx has no manifest any more. 

[root@23dd5888-ee79-40bd-a4ae-67190e5d4a8b ~]# svcs -a | grep nginx
[root@23dd5888-ee79-40bd-a4ae-67190e5d4a8b ~]#

**Comment by AlainODea** [comment]
From the discussion on smartos-discuss, the issue appears to be that the package nginx-1.4 has SMF while the package nginx-1.5 doesn't.  nginx 1.5 is a dev release.  I suggest that the package nginx-1.5 be renamed to nginx-dev-1.5.  That way users can still get it, but recognize that they are explicitly choosing a dev release and users that want stable don't have to specify an explicit version.

**Comment by chorrell** [comment]
The solution we've adopted for now is to just include the SMF as part of the nginx-1.5.0 package. The nginx site doesn't really indicate if it's experimental (no warnings or disclaimers) and it seems like people are using it in production (even the nginx site).

`pkgin update` should get you the updated nginx package with the SMF manifest.

**Comment by mamash** [comment]
Correction: you'll need to uninstall nginx-1.5.0 and reinstall it, as the package name/version stays the same.

**Comment by AlainODea** [comment]
@chorrell nginx [mainline, stable, and legacy are listed on the download page](http://nginx.org/en/download.html).  Unfortunately there is no definition of these terms given and no indication if there are consequences for using mainline.  nginx is pretty mature now so I doubt they'd be making breaking changes in mainline :)

**Comment by chorrell** [comment]
Agreed!
