### ISSUE TITLE
2013Q3 nrsysmond 1.3.0 should be smf enabled

### ISSUE THREAD

**Issue by kevpie** [TritonDataCenter/pkgsrc-legacy#76]
New Relic System Monitor
missing smf manifest.xml and smf enablement bits.

2013Q2 nrsysmond-1.3.0.tgz correct
2013Q3 nrsysmond-1.3.0.tgz broken

http://pkgsrc.joyent.com/packages/SmartOS/2013Q2/x86_64/All/
http://pkgsrc.joyent.com/packages/SmartOS/2013Q3/x86_64/All/

**Comment by mamash** [comment]
Thanks, that was a regression due to a SMF support makeover implemented in 2013Q3. We have queued up a rebuild with a fix. I should add that the 2013Q3 package set is far from complete or supported at this point, we're still fixing build failures and checking for bugs.
