### ISSUE TITLE
pkgsrc bash has problems with locale

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#8]
fighting the better part of the day trying to sort locale issues with ssh/sshd in a oi_151a7 local zone, and finally I believe the culprit is pkgsrc bash.
If I sudo pkgin install bash, then add /opt/pkg/bin/bash to /etc/shells and finally do a 
usermod -s /opt/pkg/bin/bash <user>, then when I log in (in this case via ssh) it ignores LANG and LC_ALL.
Is there something special to do here, or is this the reason /usr/bin/bash is forced in /etc/opt/pkg/mk.conf?

**Comment by jperkin** [comment]
I can't speak to the locale issue, but it's not related to why
/usr/bin/bash is used in mk.conf, that is simply setting the default
shell in pkgsrc.

Ordinarily it'd be /bin/sh but the ksh93 in illumos has bugs so it's
better to use bash.

## 

Jonathan Perkin       www.perkin.org.uk
github.com/jperkin  twitter.com/jperkin
