### ISSUE TITLE
PKG_FAIL_REASON: requires a working dlopen()

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#9]
Quite happy with the progress using pkgsrc illumos in zones... single X apps seem ok with ssh  -X and even
tried some window managers like evilwm in conjonction with a Xephyr display... quite cool actually.
But now I"d like to try working on building some packages from joyent/pkgsrc... 

While I can seem to build ok in the global zone, in the local zone, with my home directory lofs in, can't seem to advance at all.  To pick an example, archivers/star, in which a simple bmake and consequently sudo bmake install, all is well.

In my zone I get the following:

```
richard@devzone:~/src/pkgsrc$ cd archivers/star/
richard@devzone:~/src/pkgsrc/archivers/star$ ls
DESCR     distinfo  Makefile  patches   PLIST
richard@devzone:~/src/pkgsrc/archivers/star$ bmake
WARNING: [license.mk] Every package should define a LICENSE.
ERROR: This package has set PKG_FAIL_REASON:
ERROR: star-1.4.3nb4 requires a working dlopen().
*** Error code 255

Stop.
bmake: stopped in /home/richard/src/pkgsrc/archivers/star
```

Before going into more detail, is there any hints as to whether there is a minimal set of illumos packages that need to be installed, I've compared the pkgsrc packages with pkgin ls output and there isn't any substantial difference..

Thanks in advance

**Comment by ghost** [comment]
found it, need to have system/header installed

```
$sudo pkg install system/header
```

sorry for the noise

[update] plus $sudo pkg install pkg://openindiana.org/developer/library/lint
this is to get over 

```
ld: fatal: file crt1.o: open failed: No such file or directory
```

but now I'm getting (in src/pkgsrc/archivers/pax/work/libnbcompat):

```
cr libnbcompat.a glob.o md5c.o md5hl.o rmd160.o rmd160hl.o sha1.o sha1hl.o sha2.o sha2hl.o vis.o unvis.o fgetln.o fparseln.o lchflags.o lchmod.o lutimes.o setgroupent.o setpassent.o shquote.o strmode.o setmode.o pwcache.o fts.o
bmake: exec(cr) failed (No such file or directory)
```

[update later]
it was looking for 'ar' ...turns out if I sudo pkgin in coreutils and then add /opt/pkg/gnu/bin to my path, I seem to be able to get considerably further, that is with the addition of $sudo pkg install pkg:/system/library/math/header-math

It seems pkg/gnu/bin is more and more important to a number of packages.

[another update] this opt/pkg/gnu stuff is sad news, caused a bunch of other problems.  took it out of my path and did a $sudo pkg install pkg:/developer/object-file and finally seemed to build and install ok.

This is scary, when to put /opt/pkg/gnu/bin in the path?  I'm not sure it"s ready for when bmake will be run in a pkgsrc directory.

**[updated 6 nov]**

As indicated in another issue, I believe the key is putting `/usr/xpg4/bin` in the path instead of either `/usr/gnu/bin` or `/opt/pkg/gnu/bin`.  Oddly enough, `/usr/xpg4/bin/ar` is installed by default, thus the need to install `pkg:/developer/object-file` just to get `/usr/bin/ar` is largely eliminated.

**Comment by cmbalingit619** [comment]
richard@devzone:~/src/pkgsrc$ cd archivers/star/
richard@devzone:~/src/pkgsrc/archivers/star$ ls
DESCR     distinfo  Makefile  patches   PLIST
richard@devzone:~/src/pkgsrc/archivers/star$ bmake
WARNING: [license.mk] Every package should define a LICENSE.
ERROR: This package has set PKG_FAIL_REASON:
ERROR: star-1.4.3nb4 requires a working dlopen().
*** Error code 255

Stop.
bmake: stopped in /home/richard/src/pkgsrc/
